:sparkles: implemented kurl and kurlFile

diff --git a/valet.d/core b/valet.d/core
--- a/valet.d/core
+++ b/valet.d/core
@@ -22,6 +22,8 @@ fi
 # to be fast, we do not create anything until we really need it
 # this could lead to issues, altough it is very unlikely
 _TEMPORARY_PREFIX="${TMPDIR:-/tmp}/temp-"
+_TEMPORARY_WORK_FILE="${_TEMPORARY_PREFIX}${BASHPID}.valet-work"
+while [ -e "${_TEMPORARY_WORK_FILE}" ]; do _TEMPORARY_WORK_FILE+="x"; done
 _TEMPORARY_STDOUT_FILE="${_TEMPORARY_PREFIX}${BASHPID}.valet-stdout"
 while [ -e "${_TEMPORARY_STDOUT_FILE}" ]; do _TEMPORARY_STDOUT_FILE+="x"; done
 _TEMPORARY_STDERR_FILE="${_TEMPORARY_PREFIX}${BASHPID}.valet-stderr"
@@ -807,19 +809,106 @@ function invoke3var() {
   invoke5var "${failIfFails}" "${acceptableErrorCodes}" "" "" "$@" || return $?
 }
 
-
 # This function is a wrapper around curl.
 # It allows you to check the http status code and return 1 if it is not acceptable.
+# It invokes curl with the following options (do not repeat them): -sSL -w "%{http_code}" -o $2.
 #
-# $1: a list of http status codes that are acceptable, comma separated
+# $1: a list of http status codes that are acceptable, comma separated (default to 200,201,202,204,301,304,308)
 # $2: the file in which to save the output of curl
+# $3+: options for curl
 #
 # Returns:
 #  The exit code of the function is 0 if the http status code is acceptable, 1 otherwise.
 #  The content of stderr in the global variable LAST_RETURNED_VALUE.
+#  The http status code in the global variable LAST_RETURNED_VALUE2.
 #
 # Usage:
 #  kurlFile "200,201" "/filePath" "https://example.com" || fail "The curl command failed."
+function kurlFile() {
+  local acceptableStatusCodes outputFile url
+  acceptableStatusCodes="${1:-200,201,202,204,301,304,308}"
+  outputFile="${2}"
+  shift 2
+
+  # call curl
+  local -i exitCode=0
+  local httpStatusCode errors
+  invoke5var "false" "0" "false" "" "curl" "--silent" "--show-error" "--location" "--write-out" "%{http_code}" "--output" "${outputFile}" "$@" || exitCode=$?
+  httpStatusCode="${LAST_RETURNED_VALUE}"
+  errors="${LAST_RETURNED_VALUE2}"
+
+  # if debug mode is on, print info on what happened
+  if isDebugEnabled; then
+    local url="$*"
+    url="http${url##*http}"
+    url="${url%% *}"
+    url="${url%% \'}"
+
+    local debugMessage="The curl command for url ⌜${url}⌝ ended with exit code ⌜${exitCode}⌝, the http return code was ⌜${httpStatusCode}⌝."
+    if [[ -n "${errors}" ]]; then
+      debugMessage+=$'\n'"⌜stderr⌝:"$'\n'"${errors}"
+    fi
+    debug "${debugMessage}"
+  fi
+
+  # if the error code is acceptable, then we set it to 0
+  if [[ ",${acceptableStatusCodes}," == *",${httpStatusCode},"* ]]; then
+    exitCode=0
+    debug "The http return code ⌜${httpStatusCode}⌝ is acceptable and exit code has been reset to 0 from ⌜${exitCode}⌝."
+  else
+    exitCode=1
+    debug "The http return code ⌜${httpStatusCode}⌝ is not acceptable and exit code has set to 1 from ⌜${exitCode}⌝."
+  fi
+
+  LAST_RETURNED_VALUE="${errors}"
+  LAST_RETURNED_VALUE2="${httpStatusCode}"
+  return ${exitCode}
+}
+
+# This function is a wrapper around curl.
+# It allows you to check the http status code and return 1 if it is not acceptable.
+# It invokes curl with the following options (do not repeat them): -sSL -w "%{http_code}" -o "tempfile".
+#
+# $1: a list of http status codes that are acceptable, comma separated (default to 200,201,202,204,301,304,308)
+# $2+: options for curl
+#
+# Returns:
+#  The exit code of the function is 0 if the http status code is acceptable, 1 otherwise.
+#  The content of the request in the global variable LAST_RETURNED_VALUE.
+#  The content of stderr in the global variable LAST_RETURNED_VALUE2.
+#  The http status code in the global variable LAST_RETURNED_VALUE3.
+#
+# Usage:
+#  kurl "200,201" "https://example.com" || fail "The curl command failed."
+function kurl() {
+  local acceptableStatusCodes
+  acceptableStatusCodes="${1}"
+  shift
+
+  # reset the temporary file, only if needed
+  [[ -s "${_TEMPORARY_WORK_FILE}" ]] && : > "${_TEMPORARY_WORK_FILE}"
+
+  local exitCode errors httpStatusCode
+  kurlFile "${acceptableStatusCodes}" "${_TEMPORARY_WORK_FILE}" "$@" || exitCode=$?
+  errors="${LAST_RETURNED_VALUE}"
+  httpStatusCode="${LAST_RETURNED_VALUE2}"
+
+  local stdout
+  if [ -s "${_TEMPORARY_WORK_FILE}" ]; then
+    IFS= read -rd '' stdout < "${_TEMPORARY_WORK_FILE}" || true
+  fi
+
+  if isDebugEnabled; then
+    if [[ -n "${stdout}" ]]; then
+      debug "⌜curl stdout⌝:"$'\n'"${stdout}"
+    fi
+  fi
+
+  LAST_RETURNED_VALUE="${stdout:-}"
+  LAST_RETURNED_VALUE2="${errors}"
+  LAST_RETURNED_VALUE3="${httpStatusCode}"
+  return $exitCode
+}
 
 
 #===============================================================
