:construction: working on autocompletion

diff --git a/valet.d/lib-autocompletion b/valet.d/lib-autocompletion
--- a/valet.d/lib-autocompletion
+++ b/valet.d/lib-autocompletion
@@ -11,10 +11,16 @@ source interactive
 
 # ## autocompletion::start
 #
-# Displays an autocompletion box starting at a given location. Allows
+# Displays an autocompletion input starting at a given location. Allows
 # the user to type a text in the given row betwen a starting column and
 # ending column (included). Longer text are shifted to fit between
 # the two columns.
+#
+# This component is a replacement for the `read -e` command, which allows
+# to limit the input to a single line and to provide autocompletion.
+#
+# The autocompletion box can be hidden, or displayed below/above the input text
+# depending on the space available on the screen.
 #
 # The user can type character to filter down a list of suggestions,
 # navigate up and down between suggestions, insert a suggestion using
@@ -26,6 +32,10 @@ source interactive
 #
 # The multiple options allows to use this function to ask for any user input
 # as long as it is on a single line.
+#
+# You can define several callback functions that are called on different events:
+#
+# - `autocompletionOnTextUpdate`: Called when the text is updated (after each key press).
 #
 # - $1: **start line** _as int_:
 #       The line/row at which the autocompleted text starts (this is used to
@@ -76,6 +86,9 @@ source interactive
 #
 # Returns:
 #
+# - $?:
+#   - 0: The user pressed ENTER to validate the text.
+#   - 1: The user pressed ESC to close the text box.
 # - `RETURNED_VALUE`: The entered value (or empty).
 # - `RETURNED_VALUE2`: The string displayed on the screen between the 2 columns at the
 #                      moment when the autocompletion was closed.
@@ -123,6 +136,7 @@ function autocompletion::start() {
 
   AUTOCOMPLETION_FILTERED_ITEMS=()
 
+  AUTOCOMPLETION_KILLED_STRING=""
 
   # set up colors
   if [[ ${VALET_CONFIG_ENABLE_COLORS:-} == "true" ]]; then
@@ -149,7 +163,6 @@ function autocompletion::start() {
     AUTOCOMPLETION_COLOR_COUNT_RESET="${VALET_CONFIG_AUTOCOMPLETION_COUNT_RESET:-""}"
   fi
 
-
   if [[ ${AUTOCOMPLETION_SHOW_LEFT_CURSORS} == "true" ]]; then
     AUTOCOMPLETION_LEFT_CURSOR_PROMPT="${AUTOCOMPLETION_COLOR_STATIC}${VALET_CONFIG_INTERACTIVE_SELECTED_ITEM_CHARACTER:-">"} ${AUTOCOMPLETION_COLOR_STATIC_RESET}"
     AUTOCOMPLETION_LEFT_CURSOR_PROMPT_LENGTH=2
@@ -164,34 +177,59 @@ function autocompletion::start() {
 
   AUTOCOMPLETION_CLOSE_INTERACTIVE_SESSION=false
 
+  if command -v autocompletionOnTextUpdate &>/dev/null; then
+    AUTOCOMPLETION_HAS_ON_TEXT_UPDATE="true"
+  else
+    AUTOCOMPLETION_HAS_ON_TEXT_UPDATE="false"
+  fi
+
   # before starting to wait for inputs, we clear up the key pressed
   interactive::clearKeyPressed
+  # setup the terminal to be ready for readline
+  interactive::sttyInit
+  # rebind some keys to call the callback function interactiveOnKeyBindingPress
+  interactive::rebindKeymap
+  # define the callback function called when a special key is pressed
+  # shellcheck disable=SC2317
+  function interactiveOnKeyBindingPress() { autocompletionOnKeyPressed "${1}"; }
 
   drawPrompt
   drawAutocompletionBox
 
   # main loop
   while true; do
-    if interactive::waitForChar -t 0.05; then
-      onKeyPressed "${LAST_KEY_PRESSED}"
+    if interactive::waitForKeyPress -t 0.2; then
+      autocompletionOnKeyPressed "${LAST_KEY_PRESSED}"
     fi
 
     # break if fd 1 is closed or does not refer to a terminal.
     if [[ ! -t 1 || ${AUTOCOMPLETION_CLOSE_INTERACTIVE_SESSION} == "true" ]]; then break; fi
   done
 
-  RETURNED_VALUE="${AUTOCOMPLETION_USER_STRING}"
+  interactive::sttyRestore
+
   if ((AUTOCOMPLETION_FINAL_SELECTION_INDEX >= 0)); then
+    RETURNED_VALUE="${AUTOCOMPLETION_USER_STRING}"
     RETURNED_VALUE2="${AUTOCOMPLETION_ORIGINAL_ITEMS[${AUTOCOMPLETION_FINAL_SELECTION_INDEX}]}"
+    RETURNED_VALUE3=${AUTOCOMPLETION_FINAL_SELECTION_INDEX}
   else
-    RETURNED_VALUE2=""
+    return 1
   fi
-  RETURNED_VALUE3=${AUTOCOMPLETION_FINAL_SELECTION_INDEX}
+
+  # clean up
+  unset -f autocompletionOnTextUpdate 2>/dev/null || :
+
+  return 0
 }
 
-# compute the size of the autocompletion box and top/left location
-# AUTOCOMPLETION_HEIGHT / AUTOCOMPLETION_TOP
-# AUTOCOMPLETION_WIDTH / AUTOCOMPLETION_LEFT
+# Compute the size and position of the autocompletion box.
+#
+# Returns:
+#
+# - `AUTOCOMPLETION_HEIGHT`: The height of the autocompletion box.
+# - `AUTOCOMPLETION_TOP`: The top position of the autocompletion box.
+# - `AUTOCOMPLETION_WIDTH`: The width of the autocompletion box.
+# - `AUTOCOMPLETION_LEFT`: The left position of the autocompletion box.
 function autocompletionComputeSize() {
   local maxLines="${1:-9999}"
   local forceBelow="${2:-}"
@@ -236,13 +274,37 @@ function autocompletionComputeSize() {
 }
 
 # Called when a key is pressed.
-function onKeyPressed() {
-  case ${LAST_KEY_PRESSED} in
-  ESC)
-    AUTOCOMPLETION_CLOSE_INTERACTIVE_SESSION=true
-    return 0
+function autocompletionOnKeyPressed() {
+  case "${1}" in
+
+  # autocompletion boc
+  PAGE_UP)
+    changeSelectedItemIndex -10
+    drawAutocompletionBox
     ;;
-  $'\n')
+  PAGE_DOWN)
+    changeSelectedItemIndex 10
+    drawAutocompletionBox
+    ;;
+  HOME | CTRL+UP)
+    changeSelectedItemIndex -99999
+    drawAutocompletionBox
+    ;;
+  END | CTRL+DOWN)
+    changeSelectedItemIndex 99999
+    drawAutocompletionBox
+    ;;
+  UP)
+    changeSelectedItemIndex -1
+    drawAutocompletionBox
+    ;;
+  DOWN)
+    changeSelectedItemIndex 1
+    drawAutocompletionBox
+    ;;
+
+  # validate or exit
+  $'\n' | CTRL+M | CTRL+J | NEWLINE)
     # if we selected index is within the range of the filtered items
     # we can return the corresponding index in the original items
     getCurrentInitialItemsIndex
@@ -254,85 +316,149 @@ function onKeyPressed() {
     AUTOCOMPLETION_CLOSE_INTERACTIVE_SESSION=true
     return 0
     ;;
-  PAGE_DOWN)
-    changeSelectedItemIndex 10
-    drawAutocompletionBox
-    ;;
-  PAGE_UP)
-    changeSelectedItemIndex -10
-    drawAutocompletionBox
-    ;;
-  UP)
-    changeSelectedItemIndex -1
-    drawAutocompletionBox
-    ;;
-  DOWN)
-    changeSelectedItemIndex 1
-    drawAutocompletionBox
-    ;;
-  RIGHT)
-    changePromptCursorIndex 1
+  TAB | CTRL+I)
     drawPrompt
     ;;
-  LEFT)
+  ESC)
+    AUTOCOMPLETION_CLOSE_INTERACTIVE_SESSION=true
+    return 0
+    ;;
+
+  # move the cursor
+  CTRL+A)
+    changePromptCursorIndex -9999999
+    drawPrompt
+    ;;
+  CTRL+E)
+    changePromptCursorIndex 9999999
+    drawPrompt
+    ;;
+  LEFT | CTRL+B)
     changePromptCursorIndex -1
     drawPrompt
     ;;
-  DEL)
+  RIGHT | CTRL+F)
+    changePromptCursorIndex 1
+    drawPrompt
+    ;;
+  CTRL+LEFT)
+    # move to beggining of the previous word
+    local -i index=${AUTOCOMPLETION_PROMPT_INDEX}
+    index+=-1
+    while [[ ${index} -gt 0 && ${AUTOCOMPLETION_USER_STRING:index:1} =~ [[:space:]] ]]; do
+      index+=-1
+    done
+    while [[ ${index} -gt 0 && ${AUTOCOMPLETION_USER_STRING:index:1} =~ [^[:space:]] ]]; do
+      if [[ ${index} -ge 1 && ${AUTOCOMPLETION_USER_STRING:$((index - 1)):1} =~ [[:space:]] ]]; then
+        break
+      fi
+      index=$((index - 1))
+    done
+    AUTOCOMPLETION_PROMPT_INDEX=$((index >= 0 ? index : 0))
+    drawPrompt
+    ;;
+  CTRL+RIGHT)
+    # move to the end of the next word
+    local -i index=${AUTOCOMPLETION_PROMPT_INDEX}
+    index+=1
+    while [[ ${index} -lt ${#AUTOCOMPLETION_USER_STRING} && ${AUTOCOMPLETION_USER_STRING:index:1} =~ [[:space:]] ]]; do
+      index+=1
+    done
+    while [[ ${index} -lt ${#AUTOCOMPLETION_USER_STRING} && ${AUTOCOMPLETION_USER_STRING:index:1} =~ [^[:space:]] ]]; do
+      if [[ ${index} -le ${#AUTOCOMPLETION_USER_STRING} && ${AUTOCOMPLETION_USER_STRING:$((index + 1)):1} =~ [[:space:]] ]]; then
+        break
+      fi
+      index=$((index + 1))
+    done
+    AUTOCOMPLETION_PROMPT_INDEX=$((index <= ${#AUTOCOMPLETION_USER_STRING} ? index : ${#AUTOCOMPLETION_USER_STRING}))
+    drawPrompt
+    ;;
+
+  # modify the text
+  CTRL+K)
+    # kill the line from cursor to the end
+    if ((AUTOCOMPLETION_PROMPT_INDEX > 0)); then
+      AUTOCOMPLETION_KILLED_STRING="${AUTOCOMPLETION_USER_STRING:${AUTOCOMPLETION_PROMPT_INDEX}}"
+      AUTOCOMPLETION_USER_STRING="${AUTOCOMPLETION_USER_STRING:0:${AUTOCOMPLETION_PROMPT_INDEX}}"
+    else
+      AUTOCOMPLETION_USER_STRING=""
+    fi
+    drawPrompt
+    drawAutocompletionBox
+    ;;
+  CTRL+Y)
+    # yank the killed string at cursor position
+    if [[ -n ${AUTOCOMPLETION_KILLED_STRING:-} ]]; then
+      autocompletionInsertTextAtCursorPosition "${AUTOCOMPLETION_KILLED_STRING}"
+      drawPrompt
+      drawAutocompletionBox
+    fi
+    ;;
+  DEL | CTRL+D)
     # delete the character under the cursor
     local tempUserString
-    if (( AUTOCOMPLETION_PROMPT_INDEX > 0 )); then
+    if ((AUTOCOMPLETION_PROMPT_INDEX > 0)); then
       tempUserString="${AUTOCOMPLETION_USER_STRING:0:${AUTOCOMPLETION_PROMPT_INDEX}}"
     else
       tempUserString=""
     fi
-    if (( AUTOCOMPLETION_PROMPT_INDEX < ${#AUTOCOMPLETION_USER_STRING} - 1 )); then
+    if ((AUTOCOMPLETION_PROMPT_INDEX < ${#AUTOCOMPLETION_USER_STRING} - 1)); then
       tempUserString+="${AUTOCOMPLETION_USER_STRING:$((AUTOCOMPLETION_PROMPT_INDEX + 1))}"
     fi
     AUTOCOMPLETION_USER_STRING="${tempUserString}"
     drawPrompt
+    drawAutocompletionBox
+    ;;
+  CTRL+BACKSPACE | CTRL+W)
+    # delete the word before the cursor
+    local -i index=${AUTOCOMPLETION_PROMPT_INDEX}
+    while [[ ${index} -gt 0 && ${AUTOCOMPLETION_USER_STRING:index:1} =~ [[:space:]] ]]; do
+      index+=-1
+    done
+    while [[ ${index} -gt 0 && ${AUTOCOMPLETION_USER_STRING:index:1} =~ [^[:space:]] ]]; do
+      index+=-1
+    done
+    AUTOCOMPLETION_USER_STRING="${AUTOCOMPLETION_USER_STRING:0:${index}}"
+    AUTOCOMPLETION_PROMPT_INDEX=${index}
+    drawPrompt
+    drawAutocompletionBox
+    ;;
+  BACKSPACE | CTRL+H)
+    # delete the character before the cursor
+    if ((AUTOCOMPLETION_PROMPT_INDEX > 0)); then
+      if ((AUTOCOMPLETION_PROMPT_INDEX > 1)); then
+        AUTOCOMPLETION_USER_STRING="${AUTOCOMPLETION_USER_STRING:0:$((AUTOCOMPLETION_PROMPT_INDEX - 1))}${AUTOCOMPLETION_USER_STRING:${AUTOCOMPLETION_PROMPT_INDEX}}"
+      else
+        AUTOCOMPLETION_USER_STRING="${AUTOCOMPLETION_USER_STRING:${AUTOCOMPLETION_PROMPT_INDEX}}"
+      fi
+    fi
+    changePromptCursorIndex -1
+    drawPrompt
+    drawAutocompletionBox
     ;;
   *)
     # Case of keys that are supposed to only affect the search string
-    case ${LAST_KEY_PRESSED} in
-    BACKSPACE)
-      # delete the character before the cursor
-      if (( AUTOCOMPLETION_PROMPT_INDEX > 0 )); then
-        if (( AUTOCOMPLETION_PROMPT_INDEX > 1 )); then
-          AUTOCOMPLETION_USER_STRING="${AUTOCOMPLETION_USER_STRING:0:$((AUTOCOMPLETION_PROMPT_INDEX - 1))}${AUTOCOMPLETION_USER_STRING:${AUTOCOMPLETION_PROMPT_INDEX}}"
-        else
-          AUTOCOMPLETION_USER_STRING="${AUTOCOMPLETION_USER_STRING:${AUTOCOMPLETION_PROMPT_INDEX}}"
-        fi
-      fi
-      changePromptCursorIndex -1
+    # insert the character at the cursor position
+    if [[ -n ${LAST_KEY_PRESSED} ]]; then
+      autocompletionInsertTextAtCursorPosition "${LAST_KEY_PRESSED}"
       drawPrompt
       drawAutocompletionBox
-      ;;
-    # CTRL+A
-    $'\001')
-      changePromptCursorIndex -9999999
-      drawPrompt
-      ;;
-    # CTRL+E
-    $'\005')
-      changePromptCursorIndex 9999999
-      drawPrompt
-      ;;
-    # normal key
-    ?)
-      # insert the character at the cursor position
-      if (( AUTOCOMPLETION_PROMPT_INDEX > 0 )); then
-        AUTOCOMPLETION_USER_STRING="${AUTOCOMPLETION_USER_STRING:0:${AUTOCOMPLETION_PROMPT_INDEX}}${LAST_KEY_PRESSED}${AUTOCOMPLETION_USER_STRING:${AUTOCOMPLETION_PROMPT_INDEX}}"
-      else
-        AUTOCOMPLETION_USER_STRING="${LAST_KEY_PRESSED}${AUTOCOMPLETION_USER_STRING}"
-      fi
-      changePromptCursorIndex ${#LAST_KEY_PRESSED}
-      drawPrompt
-      drawAutocompletionBox
-      ;;
-    esac
+    fi
     ;;
   esac
+}
+
+# Insert a text at the cursor position.
+#
+# - $1: **text** _as string_:
+#       The text to insert.
+function autocompletionInsertTextAtCursorPosition() {
+  if ((AUTOCOMPLETION_PROMPT_INDEX > 0)); then
+    AUTOCOMPLETION_USER_STRING="${AUTOCOMPLETION_USER_STRING:0:${AUTOCOMPLETION_PROMPT_INDEX}}${1}${AUTOCOMPLETION_USER_STRING:${AUTOCOMPLETION_PROMPT_INDEX}}"
+  else
+    AUTOCOMPLETION_USER_STRING="${1}${AUTOCOMPLETION_USER_STRING}"
+  fi
+  changePromptCursorIndex ${#1}
 }
 
 # Draw the prompt line
@@ -342,16 +468,24 @@ function drawPrompt() {
   fi
 
   autocompletionGetDisplayedPromptString
-  printf '%s' "${AC__CURSOR_HIDE}${AC__CURSOR_MOVE__}$((AUTOCOMPLETION_TOP));$((AUTOCOMPLETION_LEFT))${__AC__TO}${AC__ERASE__}$((AUTOCOMPLETION_WIDTH))${__AC_CHARS}"$'\r'"${AUTOCOMPLETION_LEFT_CURSOR_PROMPT}${AUTOCOMPLETION_COLOR_PROMPT}${RETURNED_VALUE}${AUTOCOMPLETION_COLOR_PROMPT_RESET}${AC__CURSOR_MOVE__}$((AUTOCOMPLETION_TOP));$((AUTOCOMPLETION_LEFT_CURSOR_PROMPT_LENGTH + AUTOCOMPLETION_LEFT + RETURNED_VALUE2))${__AC__TO}${AC__CURSOR_SHOW}"
+  # AUTOCOMPLETION_WIDTH / AUTOCOMPLETION_LEFT
+  printf '%s' "${AC__CURSOR_HIDE}${AC__CURSOR_MOVE__}$((AUTOCOMPLETION_START_LINE));$((AUTOCOMPLETION_START_COLUMN))${__AC__TO}${AC__ERASE__}$((AUTOCOMPLETION_STOP_COLUMN - AUTOCOMPLETION_START_COLUMN + 1 + AUTOCOMPLETION_LEFT_CURSOR_PROMPT_LENGTH))${__AC_CHARS}"$'\r'"${AUTOCOMPLETION_LEFT_CURSOR_PROMPT}${AUTOCOMPLETION_COLOR_PROMPT}${RETURNED_VALUE}${AUTOCOMPLETION_COLOR_PROMPT_RESET}${AC__CURSOR_MOVE__}$((AUTOCOMPLETION_START_LINE));$((AUTOCOMPLETION_START_COLUMN + AUTOCOMPLETION_LEFT_CURSOR_PROMPT_LENGTH + RETURNED_VALUE2))${__AC__TO}${AC__CURSOR_SHOW}"
+
+  if [[ ${AUTOCOMPLETION_HAS_ON_TEXT_UPDATE} == "true" ]]; then
+    autocompletionOnTextUpdate
+  fi
 }
 
 # This method uses the following global variables:
+#
 # - AUTOCOMPLETION_USER_STRING
 # - AUTOCOMPLETION_PROMPT_INDEX
 # - AUTOCOMPLETION_PROMPT_WIDTH
+#
 # It returns the prompt string to display and the relative position
 # of the cursor whithin this prompt string.
 # It correctly cuts the user string and adds the necessary ellipsis
+#
 # - RETURNED_VALUE: the string to display
 # - RETURNED_VALUE2: the position of the cursor within this string
 function autocompletionGetDisplayedPromptString() {
@@ -432,7 +566,7 @@ function drawAutocompletionBox() {
     return 0
   fi
 
-return 0
+  return 0
 
   local IFS
   local toPrint="${AC__CURSOR_HIDE}${AUTOCOMPLETION_COLOR_RESET_TEXT}"
