:sparkles: cache directory for local state

diff --git a/valet b/valet
--- a/valet
+++ b/valet
@@ -1,5 +1,11 @@
 #!/usr/bin/env bash
 set -Eeu -o pipefail
+
+if [[ ${BASH_VERSINFO[0]:-0} -lt 5 ]]; then
+  echo "Bash 5 or higher is required to run valet."
+  exit 1
+fi
+
 : "---
 command: valet
 function: this
