:art: prefixing function with namespace

diff --git a/valet.d/commands.d/self-build b/valet.d/commands.d/self-build
--- a/valet.d/commands.d/self-build
+++ b/valet.d/commands.d/self-build
@@ -79,16 +79,16 @@ function selfBuild() {
       shift
       outputFile="${1}"
       ;;
-    -*) fail "Unknown option ⌜${1}⌝." ;;
-    *) fail "This command takes no arguments." ;;
+    -*) log::error "Unknown option ⌜${1}⌝." ;;
+    *) log::error "This command takes no arguments." ;;
     esac
     shift
   done
 
-  getUserDirectory && userDirectory="${userDirectory:-${LAST_RETURNED_VALUE}}"
+  core::getUserDirectory && userDirectory="${userDirectory:-${LAST_RETURNED_VALUE}}"
   outputFile="${outputFile:-${userDirectory}/commands}"
 
-  toAbsolutePath "${VALET_HOME}" && VALET_HOME="${LAST_RETURNED_VALUE}"
+  io::toAbsolutePath "${VALET_HOME}" && VALET_HOME="${LAST_RETURNED_VALUE}"
 
   # list all the files in which we need to find command definitions
   local -a commandDefinitionFiles
@@ -104,7 +104,7 @@ function selfBuild() {
     for file in "${userDirectory}"/**; do
       # if directory, skip
       if [[ -d "${file}" ]]; then continue; fi
-      debug "Considering file: ⌜${file}⌝."
+      log::debug "Considering file: ⌜${file}⌝."
       # skip all files not ending with .sh
       if [[ "${file}" != *".sh" ]]; then continue; fi
       # skip everything under tests.d
@@ -113,12 +113,12 @@ function selfBuild() {
     done
     shopt -u globstar
   else
-    warn "Skipping user directory ⌜${userDirectory}⌝ because it does not exist."
+    log::warning "Skipping user directory ⌜${userDirectory}⌝ because it does not exist."
   fi
 
-  if isDebugEnabled; then
+  if log::isDebugEnabled; then
     local IFS=$'\n'
-    debug "Will extract command definitions from the following files:"$'\n'"${commandDefinitionFiles[*]}"
+    log::debug "Will extract command definitions from the following files:"$'\n'"${commandDefinitionFiles[*]}"
     unset IFS
   fi
 
@@ -137,13 +137,13 @@ function selfBuild() {
   unset CMD_COMMANDS_HIDDEN_MENU_BODY
 
   if [[ -n "${SELF_BUILD_ERRORS:-}" ]]; then
-    fail "The valet user commands have not been successfully built. Please check the following errors:"$'\n'"${SELF_BUILD_ERRORS}"
+    log::error "The valet user commands have not been successfully built. Please check the following errors:"$'\n'"${SELF_BUILD_ERRORS}"
   fi
 
   writeCommandDefinitionVariablesToFile "${outputFile}"
   bumpValetBuildVersion
 
-  succeed "The valet user commands have been successfully built"
+  log::success "The valet user commands have been successfully built"
 }
 
 #===============================================================
@@ -170,7 +170,7 @@ function summarize() {
   message+=$'\n'"== List of all the hidden commands =="$'\n\n'
   message+="${CMD_COMMANDS_HIDDEN_MENU_BODY}"$'\n'
 
-  inform "${message}"
+  log::info "${message}"
 }
 
 # Bump the valet build version by one patch.
@@ -180,7 +180,7 @@ function bumpValetBuildVersion() {
 
   IFS= read -rd '' currentVersion <"${versionFile}" || true
 
-  bumpSemanticVersion "${currentVersion}" "patch" "false"
+  string::bumpSemanticVersion "${currentVersion}" "patch" "false"
 
   echo -n "${LAST_RETURNED_VALUE}" >"${versionFile}"
 }
@@ -193,41 +193,41 @@ function extractCommandDefinitionsToVariables() {
   while [[ $# -gt 0 ]]; do
     local file="${1}"
     shift
-    inform "Extracting commands from ⌜${file}⌝."
+    log::info "Extracting commands from ⌜${file}⌝."
     extractCommandYamls "${file}"
     local content
     for content in "${LAST_RETURNED_VALUE_ARRAY[@]}"; do
 
-      if isDebugEnabled; then debug "Extracting command definition for: ⌜${content%%$'\n'*}...⌝."; fi
+      if log::isDebugEnabled; then log::debug "Extracting command definition for: ⌜${content%%$'\n'*}...⌝."; fi
 
       extractCommandDefinitionToVariables "${content}"
 
       local function command
-      trimAll "${TEMP_CMD_BUILD_function:-}" && function="${LAST_RETURNED_VALUE}"
-      trimAll "${TEMP_CMD_BUILD_command:-}" && command="${LAST_RETURNED_VALUE}"
+      string::trimAll "${TEMP_CMD_BUILD_function:-}" && function="${LAST_RETURNED_VALUE}"
+      string::trimAll "${TEMP_CMD_BUILD_command:-}" && command="${LAST_RETURNED_VALUE}"
 
       # trim the leading "valet" from the command
       command="${command#valet }"
       command="${command#valet}"
 
-      inform "                         ├── ⌜${command}⌝."
+      log::info "                         ├── ⌜${command}⌝."
 
-      toAbsolutePath "${file}" && TEMP_CMD_BUILD_fileToSource="${LAST_RETURNED_VALUE}"
+      io::toAbsolutePath "${file}" && TEMP_CMD_BUILD_fileToSource="${LAST_RETURNED_VALUE}"
       TEMP_CMD_BUILD_fileToSource="${TEMP_CMD_BUILD_fileToSource#"${VALET_HOME}"/}"
 
-      if isDebugEnabled; then
-        captureOutput declare -p ${!TEMP_CMD_BUILD_*}
-        debug "Declared variables for this command:"$'\n'"${LAST_RETURNED_VALUE}"
+      if log::isDebugEnabled; then
+        io::captureOutput declare -p ${!TEMP_CMD_BUILD_*}
+        log::debug "Declared variables for this command:"$'\n'"${LAST_RETURNED_VALUE}"
       fi
 
       # make sure that all these arrays exists and have the same size
-      makeArraysSameSize TEMP_CMD_BUILD_options_name TEMP_CMD_BUILD_options_description TEMP_CMD_BUILD_options_noEnvironmentVariable
-      makeArraysSameSize TEMP_CMD_BUILD_arguments_name TEMP_CMD_BUILD_arguments_description
-      makeArraysSameSize TEMP_CMD_BUILD_examples_name TEMP_CMD_BUILD_examples_description
+      array::makeArraysSameSize TEMP_CMD_BUILD_options_name TEMP_CMD_BUILD_options_description TEMP_CMD_BUILD_options_noEnvironmentVariable
+      array::makeArraysSameSize TEMP_CMD_BUILD_arguments_name TEMP_CMD_BUILD_arguments_description
+      array::makeArraysSameSize TEMP_CMD_BUILD_examples_name TEMP_CMD_BUILD_examples_description
 
-      if isDebugEnabled; then
-        captureOutput declare -p ${!TEMP_CMD_BUILD_*}
-        debug "Declared variables for this command:"$'\n'"${LAST_RETURNED_VALUE}"
+      if log::isDebugEnabled; then
+        io::captureOutput declare -p ${!TEMP_CMD_BUILD_*}
+        log::debug "Declared variables for this command:"$'\n'"${LAST_RETURNED_VALUE}"
       fi
 
       # verify that the command definition is valid
@@ -300,7 +300,7 @@ function declareFinalCommandDefinitionCommonVariables() {
   done
   parentCommand="${parentCommand# }"
   if [[ -n "${parentCommand}" ]]; then
-    if ! appendToArrayIfNotPresent CMD_ALL_MENU_COMMANDS_ARRAY "${parentCommand# }"; then
+    if ! array::appendToArrayIfNotPresent CMD_ALL_MENU_COMMANDS_ARRAY "${parentCommand# }"; then
       declare -g "CMD_FUNCTION_NAME_${parentCommand//[-[:space:]]/_}"="_menu"
     fi
   fi
@@ -357,7 +357,7 @@ function declareFinalCommandDefinitionHelpVariables() {
       optionValue="${TEMP_CMD_BUILD_options_name[index]}"
       if [[ ${optionValue} == *"<"* ]]; then optionValue="<${optionValue##*<}"; else optionValue="true"; fi
       extractFirstLongNameFromOptionString "${TEMP_CMD_BUILD_options_name[index]}"
-      kebabCaseToSnakeCase "${LAST_RETURNED_VALUE}"
+      string::kebabCaseToSnakeCase "${LAST_RETURNED_VALUE}"
       TEMP_CMD_BUILD_options_description[index]+=$'\n'"This option can be set by exporting the variable VALET_${LAST_RETURNED_VALUE}='${optionValue}'."
     fi
   done
@@ -397,11 +397,11 @@ function declareFinalCommandDefinitionParserVariables() {
       optionHasValue="false"
     fi
     option="${option//,/ }"
-    trimAll "${option}" && option="${LAST_RETURNED_VALUE}"
+    string::trimAll "${option}" && option="${LAST_RETURNED_VALUE}"
     extractFirstLongNameFromOptionString "${option}" && optionName="${LAST_RETURNED_VALUE}"
-    kebabCaseToCamelCase "${optionName}" && optionNameCc="${LAST_RETURNED_VALUE}"
+    string::kebabCaseToCamelCase "${optionName}" && optionNameCc="${LAST_RETURNED_VALUE}"
     if [[ "${optionNoEnvVar}" != "true" ]]; then
-      kebabCaseToSnakeCase "${optionName}" && optionNameSc="VALET_${LAST_RETURNED_VALUE}"
+      string::kebabCaseToSnakeCase "${optionName}" && optionNameSc="VALET_${LAST_RETURNED_VALUE}"
     else
       optionNameSc=""
     fi
@@ -426,7 +426,7 @@ function declareFinalCommandDefinitionParserVariables() {
         argument="${argument//\?/}"
         nbOptionalArguments+=1
       fi
-      kebabCaseToCamelCase "${argument}" && argumentNameCc="${LAST_RETURNED_VALUE}"
+      string::kebabCaseToCamelCase "${argument}" && argumentNameCc="${LAST_RETURNED_VALUE}"
 
       eval "CMD_ARGS_NAME_${function}+=(\"${argumentNameCc}\")"
     done
@@ -450,7 +450,7 @@ function declareFinalCommandDefinitionParserVariables() {
 # shellcheck disable=SC2034
 function declareOtherCommmandVariables() {
   # sort commands in alphabetical order
-  sortArray CMD_ALL_COMMANDS_ARRAY
+  array::sortArray CMD_ALL_COMMANDS_ARRAY
 
   CMD_COMMANDS_MENU_BODY=""
   CMD_COMMANDS_HIDDEN_MENU_BODY=""
@@ -552,7 +552,7 @@ function verifyCommandDefinition() {
       optionNames="${optionNames%%<*}"
     fi
     optionNames="${optionNames//,/ }"
-    trimAll "${optionNames}" && optionNames=" ${LAST_RETURNED_VALUE} "
+    string::trimAll "${optionNames}" && optionNames=" ${LAST_RETURNED_VALUE} "
     # remove the first short option
     optionNames="${optionNames/ -? /}"
     # if there still are short options, it means that there are more than one or that one has more than one character
diff --git a/valet.d/commands.d/self-test-utils b/valet.d/commands.d/self-test-utils
--- a/valet.d/commands.d/self-test-utils
+++ b/valet.d/commands.d/self-test-utils
@@ -34,7 +34,7 @@ function endTest() {
   resetFdRedirection
 
   {
-    debug "Ended test ⌜${testTitle}⌝ with exit code ⌜${exitCode}⌝."
+    log::debug "Ended test ⌜${testTitle}⌝ with exit code ⌜${exitCode}⌝."
 
     # write the test title
     printf "%s\n\n" "### ${testTitle:-test}"
@@ -79,21 +79,16 @@ function endTest() {
 
 function runCoreTests() {
   if [[ ! -d "${VALET_HOME}/tests.d" ]]; then
-    fail "The valet core tests directory ⌜${VALET_HOME}/tests.d⌝ does not exist, can't run core tests."
+    log::error "The valet core tests directory ⌜${VALET_HOME}/tests.d⌝ does not exist, can't run core tests."
   fi
 
   local originalUserDirectory="${VALET_USER_DIRECTORY:-}"
 
   # we will run some example commands so we need to set the correct user directory and commands
   export VALET_USER_DIRECTORY="${VALET_HOME}/tests.d/0000-self-build"
-  local var
-  for var in ${!CMD_*}; do
-    unset "${var}"
-  done
-  unset _CMD_INCLUDED
-  sourceUserCommands
+  core::reloadUserCommands
 
-  inform "Running all test suites in directory ⌜${VALET_HOME}/tests.d⌝."
+  log::info "Running all test suites in directory ⌜${VALET_HOME}/tests.d⌝."
   runTestSuites "${VALET_HOME}/tests.d"
 
   VALET_USER_DIRECTORY="${originalUserDirectory}"
@@ -109,10 +104,10 @@ function runCoreTests() {
 function runTestSuites() {
   local testsDirectory="${1}"
 
-  createTempFile && _TEST_STANDARD_OUTPUT_FILE="${LAST_RETURNED_VALUE}"
-  createTempFile && _TEST_STANDARD_ERROR_FILE="${LAST_RETURNED_VALUE}"
-  createTempFile && _TEST_REPORT_FILE="${LAST_RETURNED_VALUE}"
-  createTempFile && _TEST_TEMP_FILE="${LAST_RETURNED_VALUE}"
+  io::createTempFile && _TEST_STANDARD_OUTPUT_FILE="${LAST_RETURNED_VALUE}"
+  io::createTempFile && _TEST_STANDARD_ERROR_FILE="${LAST_RETURNED_VALUE}"
+  io::createTempFile && _TEST_REPORT_FILE="${LAST_RETURNED_VALUE}"
+  io::createTempFile && _TEST_TEMP_FILE="${LAST_RETURNED_VALUE}"
 
   local -i failedTestSuites nbTestSuites
   failedTestSuites=0
@@ -128,16 +123,16 @@ function runTestSuites() {
 
     # skip if the test directory does not match the include pattern
     if [[ -n "${INCLUDE_PATTERN:-}" && ! ("${testDirectoryName}" =~ ${INCLUDE_PATTERN}) ]]; then
-      debug "Skipping test ⌜${testDirectoryName##*/}⌝ because it does not match the include pattern."
+      log::debug "Skipping test ⌜${testDirectoryName##*/}⌝ because it does not match the include pattern."
       continue
     fi
     # skip if the test directory matches the exclude pattern
     if [[ -n "${EXCLUDE_PATTERN:-}" && "${testDirectoryName}" =~ ${EXCLUDE_PATTERN} ]]; then
-      debug "Skipping test ⌜${testDirectoryName##*/}⌝ because it matches the exclude pattern."
+      log::debug "Skipping test ⌜${testDirectoryName##*/}⌝ because it matches the exclude pattern."
       continue
     fi
 
-    inform "Running test suite ⌜${testDirectory##*/}⌝."
+    log::info "Running test suite ⌜${testDirectory##*/}⌝."
 
     # write the test suite title
     printf "%s\n\n" "# Test suite ${testDirectory##*/}" >"${_TEST_REPORT_FILE}"
@@ -147,7 +142,7 @@ function runTestSuites() {
       # skip if not a file
       if [[ ! -e "${testScript}" ]]; then continue; fi
 
-      inform "Running test       ├── ⌜${testScript##*/}⌝."
+      log::info "Running test       ├── ⌜${testScript##*/}⌝."
 
       runTest "${testDirectory}" "${testScript}"
     done
@@ -157,9 +152,9 @@ function runTestSuites() {
     nbTestSuites+=1
 
     if [[ "${exitCode}" -eq 0 ]]; then
-      succeed "Test suite ${testDirectory##*/} passed."
+      log::success "Test suite ${testDirectory##*/} passed."
     else
-      warn "Test suite ${testDirectory##*/} failed."
+      log::warning "Test suite ${testDirectory##*/} failed."
       failedTestSuites+=1
     fi
   done
@@ -173,11 +168,11 @@ function runTestSuites() {
       failMessage+=$'\n'"You should review the difference in the logs above or by comparing each ⌜**.received.md⌝ files with ⌜**.approved.md⌝ files."
       failMessage+=$'\n'"If the differences are legitimate, then approve the changes by running this command again with the option ⌜-a⌝."
     fi
-    fail "${failMessage}"
+    log::error "${failMessage}"
   elif [[ nbTestSuites -gt 0 ]]; then
-    succeed "A total of ⌜${nbTestSuites}⌝ tests passed!"
+    log::success "A total of ⌜${nbTestSuites}⌝ tests passed!"
   else
-    warn "No tests were found."
+    log::warning "No tests were found."
   fi
 
 }
@@ -210,11 +205,11 @@ function runTest() {
 
   resetFdRedirection
 
-  trap onExitInternal EXIT
+  trap main::onExitInternal EXIT
 
   # test if the user forgot to call endTest
   if [[ -s "${_TEST_STANDARD_OUTPUT_FILE}" || -s "${_TEST_STANDARD_ERROR_FILE}" ]]; then
-    fail "The test script ⌜${testScript}⌝ did not call endTest OR it had outputs after the last endTest call."
+    log::error "The test script ⌜${testScript}⌝ did not call endTest OR it had outputs after the last endTest call."
   fi
 
 }
@@ -229,22 +224,22 @@ function compareWithApproved() {
   receivedFile="${testDirectory}/results.received.md"
 
   if [[ ! -f "${approvedFile}" ]]; then
-    debug "🧪 ${testName}: no approved file, creating one."
+    log::debug "🧪 ${testName}: no approved file, creating one."
     : >"${approvedFile}"
   fi
 
   if diff --color -u "${approvedFile}" "${receivedFileToCopy}" 1>&2; then
-    debug "🧪 ${testName}: OK, equal to approved file."
+    log::debug "🧪 ${testName}: OK, equal to approved file."
     rm -f "${receivedFile}" 2>/dev/null || true
     return 0
   else
     echo "${receivedFile} is different than ${approvedFile} (see above)" 1>&2
-    warn "🧪 ${testName}: KO, differs from approved file (see difference above)." | tee >(cat >&2)
+    log::warning "🧪 ${testName}: KO, differs from approved file (see difference above)." | tee >(cat >&2)
   fi
 
   # if the option is activated, we approve the received file
   if [[ ${AUTO_APPROVE:-false} == "true" ]]; then
-    inform "🧪 ${testName}: Auto-approving"
+    log::info "🧪 ${testName}: Auto-approving"
     cp -f "${receivedFileToCopy}" "${approvedFile}"
     rm -f "${receivedFile}" 2>/dev/null || true
   else
@@ -262,14 +257,14 @@ function onExitTest() {
   resetFdRedirection
 
   local message="The program is exiting during a test with code ${rc}."$'\n'
-  readFile "${_TEST_STANDARD_ERROR_FILE}"
+  io::readFile "${_TEST_STANDARD_ERROR_FILE}"
   message+="Current test error output: ⌜${LAST_RETURNED_VALUE}⌝"$'\n'
   message+="If you expect the tested function/program to exit/fail, then run it in a subshell like that:"$'\n'"(myFunctionThatFails)"
 
-  warn "${message}"
+  log::warning "${message}"
 
   ERROR_DISPLAY=1
-  onExitInternal
+  main::onExitInternal
 }
 
 # After this function call, everything written to stdout and stderr will be redirected
@@ -289,9 +284,9 @@ function setFdRedirection() {
     ORIGINAL_VALET_DO_NOT_USE_LOCAL_BIN="${VALET_DO_NOT_USE_LOCAL_BIN:-}"
   fi
   export VALET_LOG_LEVEL="info"
-  setLogLevel info &>/dev/null
+  log::setLevel info &>/dev/null
   export VALET_NO_COLOR="true"
-  setLogColors
+  log::setColors
   export VALET_NO_TIMESTAMP="true"
   export VALET_NO_ICON="true"
   export VALET_NO_WRAP="true"
@@ -300,7 +295,7 @@ function setFdRedirection() {
   export _COLUMNS=9999
   export VALET_DO_NOT_USE_LOCAL_BIN="true"
   if [[ -z "${SIMPLIFIED_LOG_LINE_FUNCTION:-}" ]]; then
-    createLogLineFunction
+    log::createPrintFunction
     SIMPLIFIED_LOG_LINE_FUNCTION="${LOG_LINE_FUNCTION}"
   fi
   eval "${SIMPLIFIED_LOG_LINE_FUNCTION}"
@@ -315,10 +310,10 @@ function resetFdRedirection() {
 
   # reset the original logs
   export VALET_LOG_LEVEL="${ORIGINAL_LOG_LEVEL}"
-  setLogLevel "${ORIGINAL_LOG_LEVEL}" &>/dev/null
+  log::setLevel "${ORIGINAL_LOG_LEVEL}" &>/dev/null
   export VALET_NO_COLOR="${ORIGINAL_VALET_NO_COLOR}"
   export VALET_DO_NOT_USE_LOCAL_BIN="${ORIGINAL_VALET_DO_NOT_USE_LOCAL_BIN}"
-  setLogColors
+  log::setColors
   eval "${ORIGINAL_LOG_LINE_FUNCTION}"
 }
 
@@ -328,11 +323,11 @@ function setGlobalOptions() {
     AUTO_APPROVE="true"
   fi
   if [[ -n "${include:-}" ]]; then
-    inform "Including only test suites that match the pattern ⌜${include}⌝."
+    log::info "Including only test suites that match the pattern ⌜${include}⌝."
     INCLUDE_PATTERN="${include}"
   fi
   if [[ -n "${exclude:-}" ]]; then
-    inform "Excluding all test suites that match the pattern ⌜${exclude}⌝."
+    log::info "Excluding all test suites that match the pattern ⌜${exclude}⌝."
     EXCLUDE_PATTERN="${exclude}"
   fi
 }
diff --git a/valet.d/lib-interactive b/valet.d/lib-interactive
--- a/valet.d/lib-interactive
+++ b/valet.d/lib-interactive
@@ -5,7 +5,7 @@ set -Eeu -o pipefail
 
 # in CI mode, we do not allow to go interactive because it would make the job hang forever
 if [[ ${VALET_CI_MODE:-false} == "true" ]]; then
-  fail "CI/CD mode is activated, interactive mode has been started but we cannot run fzf or we would make the job hang forever."
+  log::error "CI/CD mode is activated, interactive mode has been started but we cannot run fzf or we would make the job hang forever."
 fi
 
 # shellcheck source=lib-ansi-codes
@@ -116,10 +116,10 @@ function fullScreenInteractive() {
   # we still need to export the terminal size but in addition, we need to redraw.
   # Note: SIGWINCH does not interrupt a read command and wait for it to complete so we need
   # to set a timeout on read to allow this refresh.
-  trap 'exportTerminalSize; redraw' SIGWINCH
+  trap 'system::exportTerminalSize; redraw' SIGWINCH
 
   # still need to handle the exit, but we also need to reset the terminal when exiting.
-  trap 'resetTerminal; onExitInternal' EXIT
+  trap 'resetTerminal; main::onExitInternal' EXIT
 
   setupTerminal
   redraw
@@ -133,11 +133,11 @@ function fullScreenInteractive() {
     if [[ ! -t 1 || ${CLOSE_INTERACTIVE_SESSION} == "true" ]]; then break; fi
   done
 
-  trap 'exportTerminalSize' SIGWINCH
-  trap 'onExitInternal' EXIT
+  trap 'system::exportTerminalSize' SIGWINCH
+  trap 'main::onExitInternal' EXIT
   resetTerminal
 
-  inform "Bye!"
+  log::info "Bye!"
 }
 
 # Ask the user to yes or no.
@@ -148,12 +148,12 @@ function fullScreenInteractive() {
 #  True or false in the global variable LAST_RETURNED_VALUE.
 #
 # Usage:
-#  promptYesNo "Do you want to continue?" && local answer="${LAST_RETURNED_VALUE}"
-function promptYesNo() {
+#  interactive::promptYesNo "Do you want to continue?" && local answer="${LAST_RETURNED_VALUE}"
+function interactive::promptYesNo() {
   local prompt
   prompt="${1}"
 
-  showFzf "yes-no" "" "${prompt}" ''
+  fzf::showFzf "yes-no" "" "${prompt}" ''
 
   # we keep only the selected value, i.e. the 2nd line
   LAST_RETURNED_VALUE="${LAST_RETURNED_VALUE#*$'\n'}"
diff --git a/valet.d/lib-io b/valet.d/lib-io
--- a/valet.d/lib-io
+++ b/valet.d/lib-io
@@ -12,8 +12,8 @@ set -Eeu -o pipefail
 #   LAST_RETURNED_VALUE: The absolute path of the file.
 #
 # Usage:
-#   toAbsolutePath "myFile" && local myFileAbsolutePath="${LAST_RETURNED_VALUE}"
-function toAbsolutePath() {
+#   io::toAbsolutePath "myFile" && local myFileAbsolutePath="${LAST_RETURNED_VALUE}"
+function io::toAbsolutePath() {
   local file="${1%/}"
 
   if [[ ${file} == "/"* ]]; then
@@ -42,7 +42,7 @@ function toAbsolutePath() {
 # $2: the acceptable error codes, comma separated (if the error code is matched, then set the output error code to 0)
 # $3: true/false to indicate if the 4th argument represents a file path or directly the content for stdin
 # $4: the stdin (can be empty)
-# $5: the executable to invoke
+# $5: the executable to io::invoke
 # $6+: the arguments to pass to the executable
 #
 # Returns:
@@ -51,10 +51,10 @@ function toAbsolutePath() {
 #   The stderr file of the executable in the global variable LAST_RETURNED_VALUE2.
 #
 # Usage:
-#   invoke5 "false" "130,2" "false" "This is the stdin" "fzf" "--height=10" || fail "fzf failed."
+#   io::invoke5 "false" "130,2" "false" "This is the stdin" "fzf" "--height=10" || log::error "fzf failed."
 #   stdoutFilePath="${LAST_RETURNED_VALUE}"
 #   stderrFilePath="${LAST_RETURNED_VALUE2}"
-function invoke5() {
+function io::invoke5() {
   local failIfFails acceptableErrorCodes stdInFromFile stdIn executable
   failIfFails="${1}"
   acceptableErrorCodes="${2}"
@@ -63,18 +63,18 @@ function invoke5() {
   executable="${5}"
   shift 5
 
-  getCommandFullPath "${executable}"
+  io::getCommandLocalPath "${executable}"
   executable="${LAST_RETURNED_VALUE}"
 
   # if debug mode is on, print some info
-  if isDebugEnabled; then
+  if log::isDebugEnabled; then
     local debugMessage="Executing the command ⌜${executable}⌝."$'\n'
     debugMessage+="Fail if it fails: ⌜${failIfFails}⌝"$'\n'
     debugMessage+="Acceptable error codes: ⌜${acceptableErrorCodes}⌝"$'\n'
     debugMessage+="Standard stream from file: ⌜${stdInFromFile}⌝"$'\n'
     debugMessage+="Standard stream: ⌜${stdIn}⌝"$'\n'
     debugMessage+="Extra parameters: ⌜${*}⌝"
-    debug "${debugMessage}"
+    log::debug "${debugMessage}"
   fi
 
   # execute the executable
@@ -101,25 +101,25 @@ function invoke5() {
   if [[ ${failIfFails} == "true" && exitCode -ne 0 ]]; then shouldFail=true; fi
 
   # fail if needed or we are debug mode; display all the debug information that could be useful
-  if isDebugEnabled || [[ ${shouldFail} == "true" ]]; then
+  if log::isDebugEnabled || [[ ${shouldFail} == "true" ]]; then
 
     # append std out
     if [[ -s "${_TEMPORARY_STDOUT_FILE}" ]]; then
-      readFile "${_TEMPORARY_STDOUT_FILE}" 5000
+      io::readFile "${_TEMPORARY_STDOUT_FILE}" 5000
       if [[ "${#LAST_RETURNED_VALUE}" -ge 5000 ]]; then LAST_RETURNED_VALUE+="... (truncated)"; fi
       debugMessage+=$'\n'"Standard output:"$'\n'"⌜${LAST_RETURNED_VALUE}⌝"
     fi
     # append stderr
     if [[ -s "${_TEMPORARY_STDERR_FILE}" ]]; then
-      readFile "${_TEMPORARY_STDERR_FILE}" 5000
+      io::readFile "${_TEMPORARY_STDERR_FILE}" 5000
       if [[ "${#LAST_RETURNED_VALUE}" -ge 5000 ]]; then LAST_RETURNED_VALUE+="... (truncated)"; fi
       debugMessage+=$'\n'"Error output:"$'\n'"⌜${LAST_RETURNED_VALUE}⌝"
     fi
 
     if [[ ${shouldFail} == "true" ]]; then
-      fail "${debugMessage}"
+      log::error "${debugMessage}"
     else
-      debug "${debugMessage}"
+      log::debug "${debugMessage}"
     fi
   fi
 
@@ -133,7 +133,7 @@ function invoke5() {
 #
 # $1: true/false to indicate if the function should fail in case the execution fails
 # $2: the acceptable error codes, comma separated (if the error code is matched, then set the output error code to 0)
-# $3: the executable to invoke
+# $3: the executable to io::invoke
 # $4+: the arguments to pass to the executable
 #
 # Returns:
@@ -142,16 +142,16 @@ function invoke5() {
 #   The stderr file of the executable in the global variable LAST_RETURNED_VALUE2.
 #
 # Usage:
-#   invoke3 "false" "false" "fzf" "--height=10" || fail "fzf failed."
+#   io::invoke3 "false" "false" "fzf" "--height=10" || log::error "fzf failed."
 #   stdoutFilePath="${LAST_RETURNED_VALUE}"
 #   stderrFilePath="${LAST_RETURNED_VALUE2}"
-function invoke3() {
+function io::invoke3() {
   local failIfFails acceptableErrorCodes executable
   failIfFails="${1}"
   acceptableErrorCodes="${2}"
   shift 2
 
-  invoke5 "${failIfFails}" "${acceptableErrorCodes}" "" "" "$@" || return $?
+  io::invoke5 "${failIfFails}" "${acceptableErrorCodes}" "" "" "$@" || return $?
 }
 
 # This function call an executable and its arguments.
@@ -161,7 +161,7 @@ function invoke3() {
 # $2: the acceptable error codes, comma separated (if the error code is matched, then set the output error code to 0)
 # $3: true/false to indicate if the 4th argument represents a file path or directly the content for stdin
 # $4: the stdin (can be empty)
-# $5: the executable to invoke
+# $5: the executable to io::invoke
 # $6+: the arguments to pass to the executable
 #
 # Returns:
@@ -170,18 +170,18 @@ function invoke3() {
 #   The content of stderr in the global variable LAST_RETURNED_VALUE2.
 #
 # Usage:
-#   invoke5var "false" "130,2" "false" "This is the stdin" "fzf" "--height=10" || fail "fzf failed."
+#   io::invoke5var "false" "130,2" "false" "This is the stdin" "fzf" "--height=10" || log::error "fzf failed."
 #   stdout="${LAST_RETURNED_VALUE}"
 #   stderr="${LAST_RETURNED_VALUE2}"
-function invoke5var() {
+function io::invoke5var() {
   local -i exitCode=0
-  invoke5 "$@" || exitCode=$?
+  io::invoke5 "$@" || exitCode=$?
   local stdOutFile="${LAST_RETURNED_VALUE}"
   local stdErrFile="${LAST_RETURNED_VALUE2}"
 
-  readFile "${stdErrFile}"
+  io::readFile "${stdErrFile}"
   LAST_RETURNED_VALUE2="${LAST_RETURNED_VALUE}"
-  readFile "${stdOutFile}"
+  io::readFile "${stdOutFile}"
 
   return ${exitCode}
 }
@@ -191,7 +191,7 @@ function invoke5var() {
 #
 # $1: true/false to indicate if the function should fail in case the execution fails
 # $2: the acceptable error codes, comma separated (if the error code is matched, then set the output error code to 0)
-# $3: the executable to invoke
+# $3: the executable to io::invoke
 # $4+: the arguments to pass to the executable
 #
 # Returns:
@@ -200,16 +200,16 @@ function invoke5var() {
 #   The content of stderr in the global variable LAST_RETURNED_VALUE2.
 #
 # Usage:
-#   invoke3var "false" "130,2" "fzf" "--height=10" || fail "fzf failed."
+#   io::invoke3var "false" "130,2" "fzf" "--height=10" || log::error "fzf failed."
 #   stdout="${LAST_RETURNED_VALUE}"
 #   stderr="${LAST_RETURNED_VALUE2}"
-function invoke3var() {
+function io::invoke3var() {
   local failIfFails acceptableErrorCodes executable
   failIfFails="${1}"
   acceptableErrorCodes="${2}"
   shift 2
 
-  invoke5var "${failIfFails}" "${acceptableErrorCodes}" "" "" "$@" || return $?
+  io::invoke5var "${failIfFails}" "${acceptableErrorCodes}" "" "" "$@" || return $?
 }
 
 # This function call an executable and its arguments.
@@ -221,18 +221,19 @@ function invoke3var() {
 #  The content of stderr in the global variable LAST_RETURNED_VALUE2.
 #
 # Usage:
-#  invoke git add --all
-function invoke() {
-  invoke5var "true" "0" "" "" "$@"
+#  io::invoke git add --all
+function io::invoke() {
+  io::invoke5var "true" "0" "" "" "$@"
 }
 
 # Will return the full path of the given command if it is found in the bin folder of valet.
+# Will return the command as is if it is not found.
 #
 # $1: the command to find
 #
 # Usage:
-#   getCommandFullPath "fzf" && local fullPath="${LAST_RETURNED_VALUE}"
-function getCommandFullPath() {
+#   io::getCommandLocalPath "fzf" && local fullPath="${LAST_RETURNED_VALUE}"
+function io::getCommandLocalPath() {
   local executable="${1}"
   local possibleExecutablePath="${VALET_BIN_PATH:-"${VALET_HOME}/bin"}/${executable}"
   if [[ "${VALET_DO_NOT_USE_LOCAL_BIN:-false}" != "true" && -x "${possibleExecutablePath}" ]]; then
@@ -254,15 +255,15 @@ function getCommandFullPath() {
 #   The error output of the command in the global variable LAST_RETURNED_VALUE2.
 #
 # Usage:
-#   captureOutput "ls -l" && local lsOutput="${LAST_RETURNED_VALUE}"
-function captureOutput() {
+#   io::captureOutput "ls -l" && local lsOutput="${LAST_RETURNED_VALUE}"
+function io::captureOutput() {
   local -i exitCode=0
   "$@" 1> "${_TEMPORARY_STDOUT_FILE}" 2> "${_TEMPORARY_STDERR_FILE}" || exitCode=$?
 
-  readFile "${_TEMPORARY_STDERR_FILE}"
+  io::readFile "${_TEMPORARY_STDERR_FILE}"
   LAST_RETURNED_VALUE2="${LAST_RETURNED_VALUE}"
 
-  readFile "${_TEMPORARY_STDOUT_FILE}"
+  io::readFile "${_TEMPORARY_STDOUT_FILE}"
 
   return ${exitCode}
 }
@@ -280,9 +281,9 @@ function captureOutput() {
 #   The content of the file in the global variable LAST_RETURNED_VALUE.
 #
 # Usage:
-#   readFile "/path/to/file" && local fileContent="${LAST_RETURNED_VALUE}"
-#   readFile "/path/to/file" 500 && local fileContent="${LAST_RETURNED_VALUE}"
-function readFile() {
+#   io::readFile "/path/to/file" && local fileContent="${LAST_RETURNED_VALUE}"
+#   io::readFile "/path/to/file" 500 && local fileContent="${LAST_RETURNED_VALUE}"
+function io::readFile() {
   local filePath="${1}"
   local -i maxCharacters="${2:-0}"
 
@@ -297,4 +298,33 @@ function readFile() {
   else
     read -rd '' LAST_RETURNED_VALUE < "${filePath}" || true
   fi
+}
+
+# Check last return code and fail (exit) if it is an error
+# $1: the return code
+# $2+ : the error message to display in case of error
+#
+# Usage:
+#   command_that_could_fail || checkAndlog::error "$?" "The command that could fail has failed!"
+function io::checkAndFail() {
+  if [[ "${1:-}" != "0" ]]; then
+    shift
+    log::error "$*"
+  fi
+  return 0
+}
+
+# Check last return code and return an error code if error
+# $1: the last return code
+# $2+ : the warning message to display in case of error
+#
+# Usage:
+#   command_that_could_fail || checkAndlog::warning "$?" "The command that could fail has failed!" || return "0"
+function io::checkAndWarn() {
+  if [[ "${1:-}" != "0" ]]; then
+    shift
+    log::warning "$*"
+    return 1
+  fi
+  return 0
 }
diff --git a/valet.d/lib-kurl b/valet.d/lib-kurl
--- a/valet.d/lib-kurl
+++ b/valet.d/lib-kurl
@@ -8,7 +8,7 @@ source io
 
 # This function is a wrapper around curl.
 # It allows you to check the http status code and return 1 if it is not acceptable.
-# It invokes curl with the following options (do not repeat them): -sSL -w "%{http_code}" -o ${2}.
+# It io::invokes curl with the following options (do not repeat them): -sSL -w "%{http_code}" -o ${2}.
 #
 # $1: true/false to indicate if the function should fail in case the execution fails
 # $2: a list of http status codes that are acceptable, comma separated (default to 200,201,202,204,301,304,308)
@@ -21,8 +21,8 @@ source io
 #  The http status code in the global variable LAST_RETURNED_VALUE2.
 #
 # Usage:
-#  kurlFile "true" "200,201" "/filePath" "https://example.com" || fail "The curl command failed."
-function kurlFile() {
+#  kurl::toFile "true" "200,201" "/filePath" "https://example.com" || log::error "The curl command failed."
+function kurl::toFile() {
   local failIfFails acceptableStatusCodes outputFile url
   failIfFails="${1:-false}"
   acceptableStatusCodes="${2:-200,201,202,204,301,304,308}"
@@ -32,7 +32,7 @@ function kurlFile() {
   # call curl
   local -i exitCode=0
   local httpStatusCode errors
-  invoke5var "false" "0" "false" "" "curl" "--silent" "--show-error" "--location" "--write-out" "%{http_code}" "--output" "${outputFile}" "$@" || exitCode=$?
+  io::invoke5var "false" "0" "false" "" "curl" "--silent" "--show-error" "--location" "--write-out" "%{http_code}" "--output" "${outputFile}" "$@" || exitCode=$?
   httpStatusCode="${LAST_RETURNED_VALUE}"
   errors="${LAST_RETURNED_VALUE2}"
 
@@ -41,20 +41,20 @@ function kurlFile() {
   url="${url%% *}"
   url="${url%% \'}"
 
-  debug "The curl command for url ⌜${url}⌝ ended with exit code ⌜${exitCode}⌝, the http return code was ⌜${httpStatusCode}⌝."
+  log::debug "The curl command for url ⌜${url}⌝ ended with exit code ⌜${exitCode}⌝, the http return code was ⌜${httpStatusCode}⌝."
 
   # if the error code is acceptable, then we set it to 0
   if [[ ,${acceptableStatusCodes}, == *",${httpStatusCode},"* ]]; then
     exitCode=0
-    debug "The http return code ⌜${httpStatusCode}⌝ is acceptable and exit code has been reset to 0 from ⌜${exitCode}⌝."
+    log::debug "The http return code ⌜${httpStatusCode}⌝ is acceptable and exit code has been reset to 0 from ⌜${exitCode}⌝."
   else
     exitCode=1
     local message="The http return code ⌜${httpStatusCode}⌝ is not acceptable for url ⌜${url}⌝."
     if [[ ${failIfFails} == "true" ]]; then
       message+=$'\n'"Error output:"$'\n'"⌜${errors}⌝"
-      fail "${message}"
+      log::error "${message}"
     fi
-    debug "${message}"
+    log::debug "${message}"
   fi
 
   LAST_RETURNED_VALUE="${errors}"
@@ -64,7 +64,7 @@ function kurlFile() {
 
 # This function is a wrapper around curl.
 # It allows you to check the http status code and return 1 if it is not acceptable.
-# It invokes curl with the following options (do not repeat them): -sSL -w "%{http_code}" -o "tempfile".
+# It io::invokes curl with the following options (do not repeat them): -sSL -w "%{http_code}" -o "tempfile".
 #
 # $1: true/false to indicate if the function should fail in case the execution fails
 # $2: a list of http status codes that are acceptable, comma separated (default to 200,201,202,204,301,304,308)
@@ -77,8 +77,8 @@ function kurlFile() {
 #  The http status code in the global variable LAST_RETURNED_VALUE3.
 #
 # Usage:
-#  kurl false 200,201 https://example.com || fail "The curl command failed."
-function kurl() {
+#  kurl::toVar false 200,201 https://example.com || log::error "The curl command failed."
+function kurl::toVar() {
   local acceptableStatusCodes
   failIfFails="${1:-false}"
   acceptableStatusCodes="${2:-}"
@@ -89,16 +89,11 @@ function kurl() {
 
   local -i exitCode=0
   local errors httpStatusCode
-  kurlFile "${failIfFails}" "${acceptableStatusCodes}" "${_TEMPORARY_WORK_FILE}" "$@" || exitCode=$?
+  kurl::toFile "${failIfFails}" "${acceptableStatusCodes}" "${_TEMPORARY_WORK_FILE}" "$@" || exitCode=$?
   errors="${LAST_RETURNED_VALUE}"
   httpStatusCode="${LAST_RETURNED_VALUE2}"
 
-  local stdout
-  if [[ -s "${_TEMPORARY_WORK_FILE}" ]]; then
-    IFS= read -rd '' stdout < "${_TEMPORARY_WORK_FILE}" || true
-  fi
-
-  LAST_RETURNED_VALUE="${stdout:-}"
+  io::readFile "${_TEMPORARY_WORK_FILE}"
   LAST_RETURNED_VALUE2="${errors}"
   LAST_RETURNED_VALUE3="${httpStatusCode}"
   return ${exitCode}
