:recycle: massive refacto

diff --git a/libraries.d/core b/libraries.d/core
--- a/libraries.d/core
+++ b/libraries.d/core
@@ -8,7 +8,50 @@
 # >>> Core utilities
 #===============================================================
 
-# ## exit
+# ## core::parseShellParameters
+#
+# Parses the shell parameters passed as arguments and sets the REPLY variable to a string that can be
+# evaluated to set the local variables required in the calling function.
+#
+# This should be called when you need to parse the arguments of a function that has a finite number of arguments
+# (i.e. that uses $@ or $*) in which case we expect the shell parameters to be passed after a separator `---`.
+#
+# - $@: arguments _as any_:
+#       The arguments to parse.
+#
+# Returns:
+#
+# - ${REPLY}: The string to evaluate to set the local variables.
+#
+# ```bash
+# core::parseShellParameters 1 2 3 --- myOption=one
+# eval "${REPLY}"
+# # REPLY will be: local myOption="one"; set -- "${@:1:3}"
+# ```
+function core::parseShellParameters() {
+  local param
+  local -i nb=0
+  for param; do
+    if [[ ${param} == "---" ]]; then
+      break
+    fi
+    nb+=1
+  done
+  if (($# == nb)); then
+    # no separators, only arguments
+    REPLY=":"
+    return 0
+  elif (($# - 1 == nb)); then
+    # a separator but no options after it
+    REPLY="set -- \"\${@:1:${nb}}\""
+    return 0
+  fi
+  shift "$((nb + 1))"
+  local IFS=$' '
+  REPLY="local ${*@Q}; set -- \"\${@:1:${nb}}\""
+}
+
+# ## core::exit
 #
 # Exits the program with the given exit code.
 #
@@ -18,13 +61,33 @@
 # - $1: exit code _as int_:
 #       (optional) the exit code to use, should be between 0 and 255
 #       (defaults to 0)
-# - ${_OPTION_SILENT} _as bool_:
+# - ${silent} _as bool_:
 #       (optional) If true, will not print the exit message and call stack for non zero exit codes.
 #       (defaults to false)
 #
 # ```bash
-# exit 0
+# core::exit 0
+# core::exit 0 silent=true
 # ```
+function core::exit() {
+  local \
+    exitCode="${1:-0}" \
+    silent="false" \
+    IFS=$' '
+  shift 1
+  eval "local a= ${*@Q}"
+
+  _OPTION_SILENT="${silent}" exit "${exitCode}"
+}
+
+# ## exit (private)
+#
+# Exits the program with the given exit code.
+#
+# We replace the builtin exit command to make sure that we can correctly capture where
+# the exit was called and print the call stack.
+#
+# See core::exit.
 function exit() {
   local -i exitCode="${1:-0}"
   local silent="${_OPTION_SILENT:-false}"
@@ -34,7 +97,7 @@ function exit() {
     log::printCallStack 2
   fi
 
-  if [[ ${exitCode} != "0" && ${GLOBAL_EXPECTED_EXIT:-} != "true" && ${silent} != "true" ]];  then
+  if [[ ${exitCode} != "0" && ${GLOBAL_EXPECTED_EXIT:-} != "true" && ${silent} != "true" ]]; then
     log::print "ERROR" "${ICON_EXIT:-}" "EXIT" "Explicit exit with code ${exitCode}, stack:"
     log::printCallStack 2
   fi
@@ -48,22 +111,30 @@ function exit() {
 #
 # Displays an error message and then exit the program with error.
 #
-# - $@: **message** _as string_:
-#       the error message to display
-# - ${_OPTION_EXIT_CODE} _as int_:
+# - $1: **message** _as string_:
+#       The error message to display
+# - ${exitCode} _as int_:
 #       (optional) the exit code to use, should be between 1 and 255
 #       (defaults to 1)
 #
 # ```bash
 # core::fail "This is an error message."
+# core::fail "This is an error message." exitCode=255
 # ```
 function core::fail() {
-  log::print "ERROR" "${ICON_ERROR:-}" "FAIL" "$@"
+  local \
+    message="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}" \
+    exitCode=1
+  shift 1
+  local IFS=$' '
+  eval "local a= ${*@Q}"
+
+  log::print "ERROR" "${ICON_ERROR:-}" "FAIL" "${message}"
   if log::isDebugEnabled; then
     log::printCallStack 2
   fi
   # shellcheck disable=SC2034
-  _OPTION_SILENT=true exit "${_OPTION_EXIT_CODE:-1}"
+  _OPTION_SILENT=true exit "${exitCode}"
 }
 
 # ## source
@@ -81,30 +152,32 @@ function core::fail() {
 # - ${_OPTION_EXIT_IF_NOT_FOUND} _as bool_:
 #       (optional) Fail the program if we do not find a file to source.
 #       Otherwise we simply return 1.
-#       (defaults to false)
-# - ${_OPTION_RETURN_CODE_ALREADY_INCLUDED} _as int_:
+#       (defaults to true)
+# - ${_OPTION_RETURN_CODE_IF_ALREADY_INCLUDED} _as int_:
 #       (optional) The function return code if the given file or library was already
 #       included.
 #       (defaults to 0)
 #
 # ```bash
-#   source string
-#   source ./my/path
+# source string
+# source ./my/path
+# _OPTION_EXIT_IF_NOT_FOUND=false _OPTION_RETURN_CODE_IF_ALREADY_INCLUDED=2 source ./my/path
 # ```
 #
 # > - The file can be relative to the current script (script that calls this function).
 # > - Use `builtin source` if you want to include the file even if it was already included.
 function source() {
-  local pathOrName="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
-  shift
-  local exitIfNotFound="${_OPTION_EXIT_IF_NOT_FOUND:-true}"
-  local -i returnCodeIfAlreadyIncluded="${_OPTION_RETURNED_CODE_ALREADY_INCLUDED:-0}"
+  local \
+    pathOrName="${1}" \
+    exitIfNotFound="${_OPTION_EXIT_IF_NOT_FOUND:-true}" \
+    returnCodeIfAlreadyIncluded="${_OPTION_RETURN_CODE_IF_ALREADY_INCLUDED:-0}"
+  shift 1
 
   # if the name does not start with . or /, we assume it is a library name
   if [[ ${pathOrName:0:1} != [./] ]]; then
     # quick check if it is already included
     if [[ ${_CORE_INCLUDED_LIBRARIES:-} == *$'\n'"${pathOrName}"$'\n'* ]]; then
-      return ${returnCodeIfAlreadyIncluded}
+      return "${returnCodeIfAlreadyIncluded}"
     fi
 
     local -i sourcedFiles=0
@@ -134,7 +207,7 @@ function source() {
 
   # quick check if the file is already included
   if [[ ${_CORE_INCLUDED_FILES:-} == *$'\n'"${pathOrName}"$'\n'* ]]; then
-    return ${returnCodeIfAlreadyIncluded}
+    return "${returnCodeIfAlreadyIncluded}"
   fi
 
   # source a file next to the file that calls this function
@@ -180,7 +253,7 @@ function source() {
 # ```
 function include() {
   local name
-  for name in "$@"; do
+  for name; do
     # shellcheck disable=SC1090
     source "${name}"
   done
@@ -229,7 +302,7 @@ function core::resetIncludedFile() {
 # printf '%s\n' "The version of Valet is ⌜${REPLY}⌝."
 # ```
 function core::getVersion() {
-  # shellcheck source=lib-fs
+  # shellcheck disable=SC1091
   source fs
   fs::readFile "${GLOBAL_INSTALLATION_DIRECTORY}/version"
 }
@@ -379,7 +452,7 @@ function core::createSavedFilePath() {
 #
 # Dumps information about the current bash session into a new file.
 #
-# - ${_OPTION_DUMP_SUFFIX} _as string_:
+# - ${dumpSuffix} _as string_:
 #       (optional) The suffix for the file to create.
 #       (defaults to an empty string)
 #
@@ -391,19 +464,33 @@ function core::createSavedFilePath() {
 # core::dump
 # ```
 function core::dump() {
+  local \
+    dumpSuffix="" \
+    IFS=$' '
+  eval "local a= ${*@Q}"
+
+  # shellcheck disable=SC1091
+  source bash
+  bash::catchErrors core_dump "${dumpSuffix}"
+}
+
+# Private function to create a core dump file.
+function core_dump() {
   local filePath
-  printf -v filePath "%(%FT%H-%M-%S%z)T--PID_%06d" "${EPOCHSECONDS}" "${BASHPID}"
+  printf -v filePath "%(%FT%H-%M-%S%z)T--PID_%06d%s" "${EPOCHSECONDS}" "${BASHPID}" "${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
   core::getUserStateDirectory
   if [[ ! -d "${REPLY}/core-dumps" ]]; then
     mkdir -p "${REPLY}/core-dumps"
   fi
-  filePath="${REPLY}/core-dumps/${filePath}${_OPTION_DUMP_SUFFIX:-}"
+  filePath="${REPLY}/core-dumps/${filePath}"
 
   local fd listOfFds=""
-  if command -v readlink &>/dev/null; then
-    include exe
+  if command -v readlink &>/dev/null && [[ -d /proc/"${BASHPID}"/fd ]]; then
+    # shellcheck disable=SC1091
+    source bash
     for fd in /proc/"${BASHPID}"/fd/*; do
-      if exe::invoke2 false readlink -f "${fd}"; then
+      bash::getBuiltinOutput readlink -f "${fd}"
+      if [[ -n ${REPLY} ]]; then
         listOfFds+="${fd} -> ${REPLY%$'\n'*}"$'\n'
       else
         listOfFds+="${fd} -> ?? (readlink failed)"$'\n'
@@ -424,19 +511,19 @@ function core::dump() {
     echo "================="$'\n'"File descriptors:"
     echo "${listOfFds}"
   } >"${filePath}"
-  if command -v ls &>/dev/null; then
+  if command -v ls &>/dev/null && [[ -d /proc/"${BASHPID}"/fd ]]; then
     echo "From ls:" >>"${filePath}"
     ls -l /proc/"${BASHPID}"/fd >>"${filePath}" || :
   fi
   {
     if command -v lsof &>/dev/null; then
       echo "================="$'\n'"Open files:"
-      lsof -p "${BASHPID}" || :
+      lsof -p "${BASHPID}" 2>/dev/null || :
     fi
     echo "================="$'\n'"Options:"
     shopt
     shopt -p
-    echo "================="$'\n'"Signals:"
+    echo "================="$'\n'"Traps:"
     trap -p
     echo "================="$'\n'"Jobs:"
     jobs || :
@@ -505,21 +592,4 @@ function core::setShellOptions() {
   # listed in `locale -a` via the VALET_CONFIG_LOCALE environment variable.
   LC_ALL="${VALET_CONFIG_LOCALE:-C.UTF-8}"
   LANG="${LC_ALL}"
-}
-
-# ## core::parseMainArguments (private)
-#
-# Parses the main arguments of the valet command.
-#
-# - $@: arguments _as any_:
-#       The arguments to parse.
-#
-# ```bash
-# core::parseMainArguments "$@"
-# ```
-function core::parseMainArguments() {
-  # shellcheck source=lib-command
-  source command
-
-  command::parseProgramArguments "$@"
 }
diff --git a/libraries.d/lib-bash b/libraries.d/lib-bash
--- a/libraries.d/lib-bash
+++ b/libraries.d/lib-bash
@@ -20,13 +20,14 @@
 #
 # Returns:
 #
-# - ${REPLY}: the exit code of the command.
+# - ${REPLY_CODE}: the exit code of the command.
 #
 # ```bash
 # bash::catchErrors myFunction "arg1" "arg2"
-# if (( REPLY != 0 )); then
-#   core::fail "The command failed with code ${REPLY}."
+# if (( REPLY_CODE != 0 )); then
+#   core::fail "The command failed with code ${REPLY_CODE}."
 # fi
+# _OPTION_EXIT_ON_FAIL=true bash::catchErrors stuff
 # ```
 #
 # > While you can also put the execution of a command in an `if` (or in a pipeline) statement to effectively
@@ -48,11 +49,11 @@ function bash::catchErrors() {
 
   if [[ ${exitOnFail} == "true" && ${GLOBAL_ERROR_TRAP_LAST_ERROR_CODE} -gt 0 ]]; then
     # shellcheck disable=SC2034
-    _OPTION_SILENT=true exit "${GLOBAL_ERROR_TRAP_LAST_ERROR_CODE}"
+    core::exit "${GLOBAL_ERROR_TRAP_LAST_ERROR_CODE}" silent=true
   fi
 
   if [[ ${replyDisabled} != "true" ]]; then
-    REPLY="${GLOBAL_ERROR_TRAP_LAST_ERROR_CODE}"
+    REPLY_CODE="${GLOBAL_ERROR_TRAP_LAST_ERROR_CODE}"
   fi
 }
 
@@ -67,21 +68,22 @@ function bash::catchErrors() {
 # - $@: **command with args** _as string_:
 #       The command to run in the subshell.
 # - ${_OPTION_EXIT_ON_FAIL} _as bool_:
-#       (optional) If set to true, the main program will exit with code 1 if the subshell fails.
+#       (optional) If set to true, the main program will exit with code 1 if the command fails.
 #       (defaults to false)
-# - ${_OPTION_LOG_ON_ERROR_EXIT} _as bool_:
+# - ${_OPTION_LOG_ERROR_ON_EXIT} _as bool_:
 #       (optional) If true, will display an error if the subshell exits with a non zero code
 #       (defaults to false)
 #
 # Returns:
 #
-# - ${REPLY}: the exit code of the subshell.
+# - ${REPLY_CODE}: the exit code of the subshell.
 #
 # ```bash
 # bash::runInSubshell myFunction
-# if (( REPLY != 0 )); then
-#   core::fail "The subshell failed with code ${REPLY}"
+# if (( REPLY_CODE != 0 )); then
+#   core::fail "The subshell failed with code ${REPLY_CODE}"
 # fi
+# _OPTION_EXIT_ON_FAIL=true bash::runInSubshell myFunction
 # ```
 #
 # > This function exists because the behavior of bash subshells are not what you would expect.
@@ -92,7 +94,7 @@ function bash::catchErrors() {
 # > <https://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin-1>.
 function bash::runInSubshell() {
   local exitOnFail="${_OPTION_EXIT_ON_FAIL:-false}"
-  local logOnErrorExit="${_OPTION_LOG_ON_ERROR_EXIT:-false}"
+  local logOnErrorExit="${_OPTION_LOG_ERROR_ON_EXIT:-false}"
 
   # disable the ERR trap or we would catch the subshell failure with it and not restore
   # the errexit and the original trap (and we would display an error message that we do
@@ -103,11 +105,11 @@ function bash::runInSubshell() {
   (
     # re-enable errexit in the subshell
     set -o errexit
-    _OPTION_LOG_ON_ERROR_EXIT="${logOnErrorExit}" trap::registerSubshell
+    _OPTION_LOG_ERROR_ON_EXIT="${logOnErrorExit}" trap::registerSubshell
 
     # unset options or they will be visible from the subshell and might interfere
     local IFS=' '$'\t'$'\n'
-    unset -v ${!_OPTION_*}
+    unset -v _OPTION_EXIT_ON_FAIL _OPTION_LOG_ERROR_ON_EXIT
 
     # disable try mode in case we run this function from a tryRun
     # shellcheck disable=SC2034
@@ -121,9 +123,10 @@ function bash::runInSubshell() {
   trap trap::onErrorInternal ERR
   if [[ ${exitOnFail} == "true" && ${subshellExitCode} -gt 0 ]]; then
     # shellcheck disable=SC2034
-    _OPTION_SILENT=true exit "${subshellExitCode}"
+    core::exit "${subshellExitCode}" silent=true
   fi
-  REPLY="${subshellExitCode}"
+  # shellcheck disable=SC2034
+  REPLY_CODE="${subshellExitCode}"
 }
 
 # ## bash::injectCodeInFunction
@@ -137,8 +140,8 @@ function bash::runInSubshell() {
 #       The name of the function to inject the code into.
 # - $2: **code** _as string_:
 #       The code to inject.
-# - $3: inject at beginning _as bool_:
-#       (optional) Can be set using the variable `_OPTION_INJECT_AT_BEGINNING`.
+# - ${injectAtBeginning} _as bool_:
+#       (optional) Can be set using the variable `injectAtBeginning`.
 #       Whether to inject the code at the beginning of the function (or at the end).
 #       (defaults to false)
 #
@@ -148,14 +151,19 @@ function bash::runInSubshell() {
 # - ${REPLY2}: the original function.
 #
 # ```bash
-# bash::injectCodeInFunction myFunction "echo 'Hello world!'" true
+# bash::injectCodeInFunction myFunction "echo 'Hello!'" injectAtBeginning=true
+# bash::injectCodeInFunction myFunction "echo 'world!'"
 # eval "${REPLY}"
 # myFunction
 # ```
 function bash::injectCodeInFunction() {
-  local functionName="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
-  local code="${2?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
-  local injectAtBeginning="${3:-${_OPTION_INJECT_AT_BEGINNING:-false}}"
+  local \
+    functionName="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}" \
+    code="${2?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}" \
+    injectAtBeginning=false \
+    IFS=$' '
+  shift 2
+  eval "local a= ${*@Q}"
 
   local functionDefinition modifiedFunctionDefinition
   if declare -f "${functionName}" 1>"${GLOBAL_TEMPORARY_STDOUT_FILE}"; then
@@ -384,9 +392,6 @@ function bash::isFunction() {
 #
 # Returns:
 #
-# - $?:
-#   - 0 if the function was successfully re-exported
-#   - 1 if the function does not exist
 # - ${REPLY}: the modified function definition
 # - ${REPLY2}: the original function
 #
@@ -401,7 +406,7 @@ function bash::getFunctionDefinitionWithGlobalVars() {
   shift 2
 
   local IFS=''
-  declare -f "${functionName}" 1>"${GLOBAL_TEMPORARY_STDOUT_FILE}" || return 1
+  declare -f "${functionName}" 1>"${GLOBAL_TEMPORARY_STDOUT_FILE}" || core::fail "The function ⌜${functionName}⌝ does not exist."
   read -rd '' REPLY2 <"${GLOBAL_TEMPORARY_STDOUT_FILE}" || [[ -n ${REPLY2} ]]
   local functionDefinition
   functionDefinition="${REPLY2/"${functionName}"/"${newFunctionName}"}"
@@ -452,7 +457,7 @@ function bash::getFunctionDefinitionWithGlobalVars() {
 #
 # Returns:
 #
-# - $?
+# - ${REPLY_CODE}:
 #   - 0 if the command was successful
 #   - 1 otherwise.
 # - ${REPLY}: The captured output.
@@ -463,10 +468,15 @@ function bash::getFunctionDefinitionWithGlobalVars() {
 # ```
 function bash::getBuiltinOutput() {
   local IFS=' '
-  # shellcheck disable=SC2068
-  "${@}" &>"${GLOBAL_TEMPORARY_STDOUT_FILE}" || return 1
   REPLY=""
-  IFS='' read -rd '' REPLY <"${GLOBAL_TEMPORARY_STDOUT_FILE}" || :
+  # shellcheck disable=SC2068
+  if "${@}" &>"${GLOBAL_TEMPORARY_STDOUT_FILE}"; then
+    IFS='' read -rd '' REPLY <"${GLOBAL_TEMPORARY_STDOUT_FILE}" || :
+    REPLY_CODE=0
+  else
+    # shellcheck disable=SC2034
+    REPLY_CODE=$?
+  fi
 }
 
 # ## bash::isFdValid
