:recycle: refacto parallel run

diff --git a/libraries.d/core b/libraries.d/core
--- a/libraries.d/core
+++ b/libraries.d/core
@@ -45,6 +45,26 @@ function trap::onErrorInternal() {
     return 0
   fi
 
+  # reset the trap to not call this function again
+  trap ERR
+
+  if declare -F trap::onErrorInternalExtra &>/dev/null; then
+    log::debug "Executing custom ⌜trap::onErrorInternalExtra function ."
+    trap::onErrorInternalExtra "${errorCodes[@]}"
+  fi
+
+  if [[ ${GLOBAL_ERROR_TRAP_TEST_MODE_ENABLED:-} == "true" ]]; then
+    # if we are in test mode, we do not want to exit the program when testing a function that
+    # returns a non-zero code; see function test_exec in lib-test
+    if [[ ${BASH_COMMAND:-} == "return "* ]]; then
+      # shellcheck disable=SC2034
+      GLOBAL_ERROR_TRAP_LAST_ERROR_CODE="${errorCodes[0]}"
+      return 0
+    elif [[ ${BASH_COMMAND:-} == "eval "* && ${FUNCNAME[1]:-} == "test_exec" ]]; then
+      return 0
+    fi
+  fi
+
   local symbol="╰"
   if [[ -n ${FUNCNAME[1]:-} ]]; then
     symbol="╭"
@@ -53,8 +73,6 @@ function trap::onErrorInternal() {
   log::printString "${symbol} ${BASH_COMMAND:-}" "│ "
   log::printCallStack 2
 
-  # reset the trap to not call this function again
-  trap ERR
   GLOBAL_EXPECTED_EXIT=1
   exit 1
 }
@@ -70,6 +88,11 @@ function trap::onExitInternal() {
   fi
 
   log::debug "Exiting with code ${exitCode} after ${SECONDS}s."
+
+  if declare -F trap::onExitInternalExtra &>/dev/null; then
+    log::debug "Executing custom ⌜trap::onExitInternalExtra function ."
+    trap::onExitInternalExtra "${exitCode}"
+  fi
 
   if declare -F trap::onExit &>/dev/null; then
     log::debug "Executing custom ⌜trap::onExit⌝ function ."
@@ -179,7 +202,9 @@ function trap::onCleanUpInternal() {
   if (( ${#GLOBAL_BACKGROUND_PIDS[@]} > 0 )); then
     local pid
     for pid in "${GLOBAL_BACKGROUND_PIDS[@]}"; do
-      kill "${pid}" &>/dev/null || :
+      log::debug "Killing background process with PID ${pid}."
+      kill -INT "${pid}" &>/dev/null || :
+      kill -HUP "${pid}" &>/dev/null || :
     done
   fi
 
@@ -359,26 +384,28 @@ function trap::unregister() {
 function trap::onSubshellExitInternal() {
   local exitCode="$?"
 
-  log::debug "Exiting subshell ${BASH_SUBSHELL} with code ${exitCode}"
-  if declare -F onSubshellExit &>/dev/null; then
-    log::debug "Executing custom ⌜onSubshellExit⌝ function ."
-    onSubshellExit "${exitCode}"
+  local symbol="╰"
+  if [[ -n ${FUNCNAME[1]:-} ]]; then
+    symbol="╭"
   fi
 
-  if [[ ! -v GLOBAL_SUBSHELL_EXPECTED_EXIT ]]; then
-    if (( exitCode != 0 )); then
-      log::error "Exiting subshell ${BASH_SUBSHELL} with code ${exitCode}, stack:"
-    elif log::isDebugEnabled; then
-      log::debug "Exiting subshell ${BASH_SUBSHELL} with code ${exitCode}, stack:"
-    fi
-    if log::isDebugEnabled || (( exitCode != 0 )); then
-      local symbol="╰"
-      if [[ -n ${FUNCNAME[1]:-} ]]; then
-        symbol="╭"
-      fi
+  if [[ ${GLOBAL_SUBSHELL_LOG_ON_ERROR_EXIT:-} == "true" && ${exitCode} -ne 0 ]]; then
+    log::error "Exiting subshell depth ${BASH_SUBSHELL} with code ${exitCode}, stack:"
+    log::printString "${symbol} ${BASH_COMMAND:-}" "│ "
+    log::printCallStack 2
+  elif log::isDebugEnabled; then
+    if log::isTraceEnabled; then
+      log::debug "Exiting subshell depth ${BASH_SUBSHELL} with code ${exitCode}, stack:"
       log::printString "${symbol} ${BASH_COMMAND:-}" "│ "
       log::printCallStack 2
+    else
+      log::debug "Exiting subshell depth ${BASH_SUBSHELL} with code ${exitCode}."
     fi
+  fi
+
+  if declare -F onSubshellExit &>/dev/null; then
+    log::debug "Executing custom exit ⌜onSubshellExit⌝ function."
+    onSubshellExit "${exitCode}"
   fi
 }
 
@@ -386,9 +413,9 @@ function trap::onSubshellExitInternal() {
 #
 # Register the traps for a subshell.
 #
-# - ${_OPTION_EXPECTED_EXIT} _as bool_:
-#       (optional) If true, will not display an error if the subshell exits with a non zero code
-#       (defaults to false)
+# - ${_OPTION_LOG_ON_ERROR_EXIT} _as bool_:
+#       (optional) If true, will display an error if the subshell exits with a non zero code
+#       (defaults to true)
 
 # > - For a subshell, we do not want to execute the "cleanup" because it would also delete
 # >   files of the main process.
@@ -401,10 +428,10 @@ function trap::registerSubshell() {
   if (( BASH_SUBSHELL == 0 )); then
     core::fail "This function should only be called in a subshell."
   fi
-  if [[ ${_OPTION_EXPECTED_EXIT:-false} == "true" ]]; then
-    GLOBAL_SUBSHELL_EXPECTED_EXIT=1
+  if [[ ${_OPTION_LOG_ON_ERROR_EXIT:-true} == "true" ]]; then
+    GLOBAL_SUBSHELL_LOG_ON_ERROR_EXIT=true
   else
-    unset -v GLOBAL_SUBSHELL_EXPECTED_EXIT
+    unset -v GLOBAL_SUBSHELL_LOG_ON_ERROR_EXIT
   fi
 
   trap trap::onErrorInternal ERR
@@ -1360,7 +1387,7 @@ function log::parseLogPattern() {
       printfFormat="%${formatSpecifier:-"-5d"}"
       # shellcheck disable=SC2034
       declare -g -A GLOBAL_PID_TO_PNAME
-      REPLY4+=$'\n'"local processName=\${GLOBAL_PID_TO_PNAME[\${BASHPID}]:-}; if [[ -z \${processName} ]]; then if [[ \${BASHPID} == \"${BASHPID}\" ]]; then GLOBAL_PID_TO_PNAME[\${BASHPID}]=\"main\"; else string::numberToUniqueId \"\${BASHPID}\"; GLOBAL_PID_TO_PNAME[\${BASHPID}]=\"\${REPLY}\"; fi; processName=\${GLOBAL_PID_TO_PNAME[\${BASHPID}]}; fi"
+      REPLY4+=$'\n'"local processName=\${GLOBAL_PID_TO_PNAME[\${BASHPID}]:-}; if [[ -z \${processName} ]]; then if [[ \${BASHPID} == \"${GLOBAL_PROGRAM_MAIN_PID}\" ]]; then GLOBAL_PID_TO_PNAME[\${BASHPID}]=\"main\"; else string::numberToUniqueId \"\${BASHPID}\"; GLOBAL_PID_TO_PNAME[\${BASHPID}]=\"\${REPLY}\"; fi; processName=\${GLOBAL_PID_TO_PNAME[\${BASHPID}]}; fi"
       log_setPrintfArgumentFromFormat "processName"
       ;;
     subshell)
@@ -1433,6 +1460,9 @@ function log::parseLogPattern() {
 # Indeed, each log function might have to output the same log to different file descriptors or files,
 # we don't want to repeat code and we don't want to recompute the same output logic on each function.
 #
+# - $1: log file descriptor _as string_:
+#       (optional) The variable name to use for the coproc.
+#       (defaults to "${VALET_CONFIG_LOG_FD}" which defaults to 2).
 # - ${_OPTION_LOG_PATTERN} _as string_:
 #       (optional) If defined, the log pattern to use.
 #       (defaults to "")
@@ -1457,7 +1487,10 @@ function log::parseLogPattern() {
 # - ${GLOBAL_LOG_WRAP_PADDING}: The string with the number of spaces necessary to align with other log messages.
 # - $[GLOBAL_LOG_COLUMNS}: The number of columns to use for the log.
 # - $[GLOBAL_LOG_DISABLE_WRAP}: true if the log should not be wrapped.
+# shellcheck disable=SC2120
 function log::init() {
+  local logFileDescriptor="${1:-${VALET_CONFIG_LOG_FD:-}}"
+
   GLOBAL_LOG_COLUMNS="${VALET_CONFIG_LOG_COLUMNS:-${GLOBAL_COLUMNS}}"
   GLOBAL_LOG_DISABLE_WRAP="${VALET_CONFIG_LOG_DISABLE_WRAP:-false}"
   GLOBAL_LOG_PATTERN="${_OPTION_LOG_PATTERN:-${VALET_CONFIG_LOG_PATTERN:-"<colorFaded><time>{(%H:%M:%S)T}<colorDefault> <levelColor><level>  <icon><colorDefault> <message>"}}"
@@ -1474,18 +1507,18 @@ function log::init() {
   fi
 
   # make sure the file descriptor (if any) is valid
-  if [[ -n ${VALET_CONFIG_LOG_FD:-} && ${VALET_CONFIG_LOG_FD} != "2" ]]; then
+  if [[ -n ${logFileDescriptor} && ${logFileDescriptor} != "2" ]]; then
     local isFdValid=false
-    if [[ ${VALET_CONFIG_LOG_FD} =~ ^[0-9]+$ ]]; then
-      if { : >&"${VALET_CONFIG_LOG_FD}"; } 2>/dev/null && exec {GLOBAL_FD_LOG}>&${VALET_CONFIG_LOG_FD}; then
+    if [[ ${logFileDescriptor} =~ ^[0-9]+$ ]]; then
+      if { : >&"${logFileDescriptor}"; } 2>/dev/null && exec {GLOBAL_FD_LOG}>&${logFileDescriptor}; then
         isFdValid=true
       fi
-    elif { : >>"${VALET_CONFIG_LOG_FD}"; } 2>/dev/null && exec {GLOBAL_FD_LOG}>>"${VALET_CONFIG_LOG_FD}"; then
+    elif { : >>"${logFileDescriptor}"; } 2>/dev/null && exec {GLOBAL_FD_LOG}>>"${logFileDescriptor}"; then
       # it is a file
       isFdValid=true
     fi
     if [[ ${isFdValid} != "true" ]]; then
-      core::fail "The file descriptor for the logs VALET_CONFIG_LOG_FD is not valid: ⌜${VALET_CONFIG_LOG_FD}⌝."
+      core::fail "The file descriptor for the logs VALET_CONFIG_LOG_FD is not valid: ⌜${logFileDescriptor}⌝."
     fi
     # save the original stderr fd so we can restore it if we call log::init again
     exec {GLOBAL_FD_ORIGINAL_STDERR}>&2
@@ -1493,9 +1526,10 @@ function log::init() {
     exec 2>&${GLOBAL_FD_LOG}
   else
     exec {GLOBAL_FD_LOG}>&2
+    logFileDescriptor="${logFileDescriptor:-2}"
   fi
 
-  local progressBarCode progressBarCode2 progressBarCode3 outputCode logFileDescriptor="${VALET_CONFIG_LOG_FD:-2}"
+  local progressBarCode progressBarCode2 progressBarCode3 outputCode
   if [[ ${logFileDescriptor} =~ ^[0-9]+$ ]]; then
     # it is a numbered file descriptor
     outputCode="1>&${logFileDescriptor}"
diff --git a/libraries.d/lib-bash b/libraries.d/lib-bash
--- a/libraries.d/lib-bash
+++ b/libraries.d/lib-bash
@@ -6,20 +6,23 @@
 # ## bash::runInSubshell
 #
 # This functions runs a command in a subshell.
-  #
+# The command can fail and can trigger errors; it will be caught and this function will return
+# the exit code of the subshell.
+# This function can almost be considered as a try/catch block for bash.
+#
 # - $@: **command with args** _as string_:
 #       The command to run in the subshell.
 # - ${_OPTION_EXIT_ON_FAIL} _as bool_:
 #       (optional) If set to true, the main program will exit with code 1 if the subshell fails.
 #
 # Returns:
-# - $?:
-#   - 0 if the subshell completed successfully.
-#   - 1 if the subshell failed.
+#
+# - ${REPLY}: the exit code of the subshell.
 #
 # ```bash
-# if ! bash::runInSubshell myFunction; then
-#   core::fail "The subshell failed with code ${PIPESTATUS[0]:-}"
+# bash::runInSubshell myFunction
+# if (( REPLY != 0 )); then
+#   core::fail "The subshell failed with code ${REPLY}"
 # fi
 # ```
 #
@@ -27,11 +30,11 @@
 # > This function ensures that errors are properly handled and make the command list fail,
 # > it ensures that we run the exit trap and the custom function "onSubshellExit",
 # > and it gives you the correct exit code of the subshell.
+# > As a reminder, the error trap is not triggered for commands part of until while if ! || && tests,
+# > see <https://www.gnu.org/software/bash/manual/bash.html#index-trap> and
+# > <https://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin-1>.
 function bash::runInSubshell() {
   local exitOnFail="${_OPTION_EXIT_ON_FAIL:-false}"
-  # save the ERR trap to restore it later
-  bash::getBuiltinOutput trap -p ERR
-  local originalErrTrap="${REPLY}"
   # disable the ERR trap or we would catch the subshell failure with it and not restore
   # the errexit and the original trap (and we would display an error message that we do
   # not want to display because we already displayed an error from the subshell).
@@ -41,19 +44,19 @@ function bash::runInSubshell() {
   (
     # re-enable errexit in the subshell
     set -o errexit
-    _OPTION_EXPECTED_EXIT=true trap::registerSubshell
+    _OPTION_LOG_ON_ERROR_EXIT=false trap::registerSubshell
     "${@}"
   )
   local subshellExitCode=${PIPESTATUS[0]:-}
-  set +o errexit
+  set -o errexit
   # restore the original ERR trap
-  eval "${originalErrTrap}"
+  trap trap::onErrorInternal ERR
   if [[ ${exitOnFail} == "true" && ${subshellExitCode} -gt 0 ]]; then
     # shellcheck disable=SC2034
     GLOBAL_EXPECTED_EXIT=1
     exit "${subshellExitCode}"
   fi
-  return "${subshellExitCode}"
+  REPLY="${subshellExitCode}"
 }
 
 # ## bash::countJobs
diff --git a/libraries.d/lib-coproc b/libraries.d/lib-coproc
--- a/libraries.d/lib-coproc
+++ b/libraries.d/lib-coproc
@@ -2,8 +2,152 @@
 # author: github.com/jcaillon
 # description: This script can be sourced by commands to provide convenient functions.
 
-# shellcheck source=lib-bash
-source bash
+# ## coproc::runInParallel
+#
+# This function runs a list of commands in parallel with a maximum number of parallel coprocs.
+#
+# - $1: **job commands array name** _as string_:
+#       The name of the array containing the commands to run.
+#       Each command string will be evaluated in a subshell.
+#       Each command should explicitly exit with a non-zero code if it fails and with zero if it succeeds.
+# - ${_OPTION_MAX_IN_PARALLEL} _as int_:
+#       (optional) The maximum number of parallel coprocs to run.
+#       (defaults to 8)
+# - ${_OPTION_COMPLETED_CALLBACK} _as string_:
+#       (optional) The name of the function to call when a coproc is completed (successfully or not).
+#       The function will receive the following arguments:
+#       - $1 the coproc index
+#       - $2 the coproc exit code
+#       - $3 the percentage of coprocs already completed
+#       - $4 the path of the file containing the accumulated logs of the coproc
+#       If the function sets REPLY to 1, the script will exit early. Otherwise it should set REPLY to 0.
+#       (defaults to "" which does nothing)
+# - ${_OPTION_REDIRECT_LOGS} _as bool_:
+#       (optional) Redirect the logs of the coproc instead of printing them in the current file descriptor.
+#       The accumulated logs of the coproc will be available in the completed callback function.
+#       (defaults to false)
+# - ${_OPTION_PRINT_REDIRECTED_LOGS} _as bool_:
+#       (optional) This option allows to automatically redirect the logs of the coproc to a file and
+#       print the accumulated logs of a coproc when it is completed (successfully or not).
+#       (defaults to false)
+#
+# Returns:
+#
+# - ${REPLY}: 0 if all the jobs completed, 1 if the completed callback function returned 1.
+# - ${REPLY2}: The number of successfully completed jobs.
+# - ${REPLY_ARRAY[@]}: an array containing the exit codes of the jobs.
+#
+# ```bash
+# declare -a jobCommands=("sleep 1" "sleep 2" "sleep 3")
+# _OPTION_MAX_PARALLEL_COPROCS=2 coproc::runInParallel jobCommands
+# ```
+function coproc::runInParallel() {
+  local -n jobCommands="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
+  local -i maxInParallel="${_OPTION_MAX_IN_PARALLEL:-8}"
+  local completedCallback="${_OPTION_COMPLETED_CALLBACK:-}"
+  local redirectLogs="${_OPTION_REDIRECT_LOGS:-false}"
+  local printRedirectedLogs="${_OPTION_PRINT_REDIRECTED_LOGS:-false}"
+  local coprocNamePrefix="_COPROC_PARALLEL_"
+
+  local logOnErrorExit=false
+  if [[ -z ${completedCallback} ]]; then
+    # if no callback is defined, we want to log on error exit
+    logOnErrorExit=true
+  fi
+
+  maxInParallel=$(( maxInParallel < 1 ? 1 : maxInParallel ))
+
+  local -a -i pids=() runningPids=() exitCodes=()
+  local -i index pid endedCoprocPid endedCoprocExitStatus endedCoprocIndex
+  local -a logFiles=()
+  local logFile=""
+
+  for ((index = 0; index < ${#jobCommands[@]}; index++)); do
+    if [[ ${redirectLogs} == "true" || ${printRedirectedLogs} == "true" ]]; then
+      _OPTION_PATH_ONLY=true fs::createTempFile
+      logFile="${REPLY}"
+    fi
+    logFiles+=("${logFile}")
+
+    _OPTION_INIT_COMMAND="${jobCommands[index]}" \
+      _OPTION_REDIRECT_LOGS_TO_FILE="${logFile}" \
+      _OPTION_LOG_ON_ERROR_EXIT="${logOnErrorExit}" \
+      coproc::run "${coprocNamePrefix}${index}"
+
+    pid="${REPLY}"
+    pids+=("${pid}")
+    runningPids+=("${pid}")
+
+    log::debug "Running parallel coproc ${index} with PID ${pid}."
+    log::trace $'\n'"Command: ${jobCommands[index]}"
+
+    while (( ${#runningPids[@]} >= maxInParallel || index == ${#jobCommands[@]} - 1 )); do
+      # wait for one of the coproc to finish (or all of them if they are all scheduled)
+      endedCoprocExitStatus=0
+      wait -n -p endedCoprocPid "${runningPids[@]}" || endedCoprocExitStatus=$?
+      exitCodes+=("${endedCoprocExitStatus}")
+
+      # find the index of the ended coproc in the pids array
+      for endedCoprocIndex in "${!pids[@]}"; do
+        if [[ ${pids[endedCoprocIndex]} == "${endedCoprocPid}" ]]; then
+          log::debug "The coproc with PID ${endedCoprocPid} is at index ${endedCoprocIndex} in ${pids[*]}."
+          break
+        fi
+      done
+
+      log::debug "The parallel coproc ${endedCoprocIndex} with PID ${endedCoprocPid} is completed with code ${endedCoprocExitStatus}."
+
+      # remove the coproc from the list of running pids
+      coproc_removePidFromBackgroundPids "${endedCoprocPid}"
+      local pidIndex
+      for pidIndex in "${!runningPids[@]}"; do
+        if [[ ${runningPids[pidIndex]} == "${endedCoprocPid}" ]]; then
+          unset -v 'runningPids[pidIndex]'
+          break
+        fi
+      done
+
+      # execute the completed callback if defined
+      if [[ -n ${completedCallback} ]]; then
+        local -i percentageCompleted=$(( ${#exitCodes[@]} * 100 / ${#jobCommands[@]} ))
+
+        if [[ ${printRedirectedLogs} == "true" ]]; then
+          # display the accumulated logs
+          if [[ -n ${logFiles[endedCoprocIndex]} && -s ${logFiles[endedCoprocIndex]} ]]; then
+            fs::readFile "${logFiles[endedCoprocIndex]}"
+            log::printRaw REPLY
+          fi
+        fi
+
+        REPLY=0
+        "${completedCallback}" "${endedCoprocIndex}" "${endedCoprocExitStatus}" "${percentageCompleted}" "${logFiles[endedCoprocIndex]}"
+        if (( REPLY != 0 )) ; then
+          log::debug "The completed callback function ⌜${completedCallback}⌝ requested to stop the parallel execution."
+          REPLY=1
+          break 2
+        fi
+      fi
+
+      # if all coproc are scheduled and completed, we can exit the loop
+      if ((${#exitCodes[@]} == ${#jobCommands[@]})); then
+        REPLY=0
+        break 2
+      fi
+    done
+  done
+
+  REPLY2=0
+  local -i exitCode
+  for exitCode in "${exitCodes[@]}"; do
+    if (( exitCode == 0 )); then
+      REPLY2=$((REPLY2 + 1))
+    fi
+  done
+
+  # shellcheck disable=SC2034
+  REPLY_ARRAY=("${exitCodes[@]}")
+}
+
 
 # ## coproc::run
 #
@@ -14,7 +158,7 @@ source bash
 #
 # - $1: **coproc variable name** _as string_:
 #       The variable name to use for the coproc.
-#       It will be used to store the coproc file descriptors and PID.²
+#       It will be used to store the coproc file descriptors and PID.
 #       <coproc_variable_name>[0] will be the input pipe file descriptor,
 #       <coproc_variable_name>[1] will be the output pipe file descriptor,
 #       <coproc_variable_name>_PID will be the PID of the coproc.
@@ -47,6 +191,12 @@ source bash
 #       (optional) If true, the coproc will only keep the last message received
 #       from the main thread to evaluate the on message command.
 #       (defaults to false)
+# - ${_OPTION_REDIRECT_LOGS_TO_FILE} _as string_:
+#       (optional) The path to a file where the logs of the coproc will be redirected.
+#       (defaults to "")
+# - ${_OPTION_LOG_ON_ERROR_EXIT} _as bool_:
+#       (optional) If true, will display an error if the coproc exits with a non zero code
+#       (defaults to true)
 #
 # Returns:
 #
@@ -63,15 +213,18 @@ function coproc::run() {
   local endCommand="${_OPTION_END_COMMAND:-":"}"
   local waitForReadiness="${_OPTION_WAIT_FOR_READINESS:-false}"
   local keepOnlyLastMessage="${_OPTION_KEEP_ONLY_LAST_MESSAGE:-false}"
+  local redirectLogsToFile="${_OPTION_REDIRECT_LOGS_TO_FILE:-""}"
+  local logOnErrorExit="${_OPTION_LOG_ON_ERROR_EXIT:-true}"
 
   if [[ -v "${coprocVarName}" ]]; then
     core::fail "The coproc ⌜${coprocVarName}⌝ is already running."
   fi
 
-  log::debug "Starting coproc ⌜${coprocVarName}⌝ with command ⌜${initCommand}⌝ and loop ⌜${loopCommand}⌝."
+  log::debug "Starting coproc ${coprocVarName}"
+  log::trace $'\n'"Init command: ${initCommand}"$'\n'"loop command: ${loopCommand}."$'\n'"on message command: ${onMessageCommand}"$'\n'"end command: ${endCommand}"$'\n'"wait for readiness: ${waitForReadiness}"$'\n'"keep only last message: ${keepOnlyLastMessage}"
 
   # Start the coproc
-  eval "{ coproc ${coprocVarName} { coproc_program \"${initCommand}\" \"${loopCommand}\" \"${onMessageCommand}\" \"${endCommand}\" ${waitForReadiness} ${keepOnlyLastMessage} 2>&${GLOBAL_FD_LOG}; } } 2>/dev/null"
+  eval "{ coproc ${coprocVarName} { coproc_program \"${initCommand}\" \"${loopCommand}\" \"${onMessageCommand}\" \"${endCommand}\" ${waitForReadiness} ${keepOnlyLastMessage} \"${redirectLogsToFile}\" ${logOnErrorExit} 2>&${GLOBAL_FD_LOG}; } } 2>/dev/null"
 
   # wait for pid variable to be set by bash (we should never enter the loop)
   local -i loopNumber=0
@@ -111,9 +264,15 @@ function coproc_program() {
   local endCommand="${4}"
   local waitForReadiness="${5}"
   local keepOnlyLastMessage="${6}"
+  local redirectLogsToFile="${7}"
+  local logOnErrorExit="${8}"
 
   # we are inside a coproc, register the correct traps
-  trap::registerSubshell
+  _OPTION_LOG_ON_ERROR_EXIT="${logOnErrorExit}" trap::registerSubshell
+
+  if [[ -n ${redirectLogsToFile} ]]; then
+    log::init "${redirectLogsToFile}"
+  fi
 
   # wait for the main process to retrieve our PID
   if ! kill -0 "${GLOBAL_PROGRAM_MAIN_PID}" 2>/dev/null || ! IFS=$'\0' read -rd $'\0' REPLY; then
@@ -309,7 +468,7 @@ function coproc_removePidFromBackgroundPids() {
 
   local index
   for index in "${!GLOBAL_BACKGROUND_PIDS[@]}"; do
-    if [[ "${GLOBAL_BACKGROUND_PIDS[index]}" == "${pid}" ]]; then
+    if [[ ${GLOBAL_BACKGROUND_PIDS[index]} == "${pid}" ]]; then
       unset -v 'GLOBAL_BACKGROUND_PIDS[index]'
       break
     fi
