:sparkles: fixed subshell usage

diff --git a/libraries.d/core b/libraries.d/core
--- a/libraries.d/core
+++ b/libraries.d/core
@@ -71,6 +71,7 @@ function trap::onExitInternal() {
 
   log::debug "Exiting with code ${exitCode} after ${SECONDS}s."
   if declare -F onExit &>/dev/null; then
+    log::debug "Executing custom ⌜onExit⌝ function ."
     onExit "${exitCode}"
   fi
 
@@ -264,25 +265,26 @@ function trap::unregister() {
 function trap::onSubshellExitInternal() {
   local exitCode="$?"
 
-  if (( exitCode != 0 )); then
-    log::error "Exiting with code ${exitCode}, stack:"
-  elif log::isDebugEnabled; then
-    log::debug "Exiting with code ${exitCode}, stack:"
-  else
-    log::debug "Exiting with code ${exitCode}"
-  fi
-
-  if log::isDebugEnabled || (( exitCode != 0 )); then
-    local symbol="╰"
-    if [[ -n ${FUNCNAME[1]:-} ]]; then
-      symbol="╭"
-    fi
-    log::printString "${symbol} ${BASH_COMMAND:-}" "│ "
-    log::printCallStack 2
-  fi
-
+  log::debug "Exiting subshell ${BASH_SUBSHELL} with code ${exitCode}"
   if declare -F onSubshellExit &>/dev/null; then
+    log::debug "Executing custom ⌜onSubshellExit⌝ function ."
     onSubshellExit "${exitCode}"
+  fi
+
+  if [[ ! -v GLOBAL_SUBSHELL_EXPECTED_EXIT ]]; then
+    if (( exitCode != 0 )); then
+      log::error "Exiting subshell ${BASH_SUBSHELL} with code ${exitCode}, stack:"
+    elif log::isDebugEnabled; then
+      log::debug "Exiting subshell ${BASH_SUBSHELL} with code ${exitCode}, stack:"
+    fi
+    if log::isDebugEnabled || (( exitCode != 0 )); then
+      local symbol="╰"
+      if [[ -n ${FUNCNAME[1]:-} ]]; then
+        symbol="╭"
+      fi
+      log::printString "${symbol} ${BASH_COMMAND:-}" "│ "
+      log::printCallStack 2
+    fi
   fi
 }
 
@@ -290,17 +292,27 @@ function trap::onSubshellExitInternal() {
 #
 # Register the traps for a subshell.
 #
-# - For a subshell, we do not want to execute the "cleanup" because it would also delete
-#   files of the main process.
-# - Additionally, we want to re-register the EXIT trap because it is not properly honored.
-# - External interruptions of the subshell (e.g. kill) are considered to be voluntary so we exit with 0;
-#   note that coproc do not respond to interrupt signals (CTRL+C does not work).
-# - coproc and jobs will not get SIGHUP when the main process ends and they will continue to execute
-#   until killed or until they check that the main process is dead.
+# - ${_OPTION_EXPECTED_EXIT} _as bool_:
+#       (optional) If true, will not display an error if the subshell exits with a non zero code
+#       (defaults to false)
+
+# > - For a subshell, we do not want to execute the "cleanup" because it would also delete
+# >   files of the main process.
+# > - Additionally, we want to re-register the EXIT trap because it is not properly honored.
+# > - External interruptions of the subshell (e.g. kill) are considered to be voluntary so we exit with 0;
+# >   note that coproc do not respond to interrupt signals (CTRL+C does not work).
+# > - coproc and jobs will not get SIGHUP when the main process ends and they will continue to execute
+# >   until killed or until they check that the main process is dead.
 function trap::registerSubshell() {
   if (( BASH_SUBSHELL == 0 )); then
     core::fail "This function should only be called in a subshell."
   fi
+  if [[ ${_OPTION_EXPECTED_EXIT:-false} == "true" ]]; then
+    GLOBAL_SUBSHELL_EXPECTED_EXIT=1
+  else
+    unset -v GLOBAL_SUBSHELL_EXPECTED_EXIT
+  fi
+
   trap trap::onErrorInternal ERR
   trap trap::onSubshellExitInternal EXIT
   # Register CTRL+C SIGINT (interrupt) and CTRL+\ QUIT (interrupt with a coredump) event handler
diff --git a/libraries.d/lib-bash b/libraries.d/lib-bash
--- a/libraries.d/lib-bash
+++ b/libraries.d/lib-bash
@@ -17,10 +17,8 @@
 #   - 1 if the subshell failed.
 #
 # ```bash
-# if bash::runInSubshell myFunction; then
-#   log::info "The subshell completed successfully."
-# else
-#   core::fail "The subshell failed."
+# if ! bash::runInSubshell myFunction; then
+#   core::fail "The subshell failed with code ${PIPESTATUS[0]:-}"
 # fi
 # ```
 #
@@ -34,7 +32,7 @@ function bash::runInSubshell() {
   bash::getBuiltinOutput trap -p ERR
   local originalErrTrap="${RETURNED_VALUE}"
   # disable the ERR trap or we would catch the subshell failure with it and not restore
-  # the errexit and the original trap (and we would display an error message that we do 
+  # the errexit and the original trap (and we would display an error message that we do
   # not want to display because we already displayed an error from the subshell).
   trap ERR
   # disable errexit in the main shell
@@ -42,17 +40,17 @@ function bash::runInSubshell() {
   (
     # re-enable errexit in the subshell
     set -o errexit
-    trap::registerSubshell
+    _OPTION_EXPECTED_EXIT=true trap::registerSubshell
     "${@}"
   )
-  local subshellExitCode=$?
+  local subshellExitCode=${PIPESTATUS[0]:-} 
   set +o errexit
   # restore the original ERR trap
   eval "${originalErrTrap}"
   if [[ ${exitOnFail} == "true" && ${subshellExitCode} -gt 0 ]]; then
     # shellcheck disable=SC2034
     GLOBAL_EXPECTED_EXIT=1
-    exit ${subshellExitCode}
+    exit "${subshellExitCode}"
   fi
   return "${subshellExitCode}"
 }
