:sparkles: implemented SIGTSTP/SIGCONT signals

diff --git a/libraries.d/core b/libraries.d/core
--- a/libraries.d/core
+++ b/libraries.d/core
@@ -71,9 +71,9 @@ function trap::onExitInternal() {
 
   log::debug "Exiting with code ${exitCode} after ${SECONDS}s."
 
-  if declare -F onExit &>/dev/null; then
-    log::debug "Executing custom ⌜onExit⌝ function ."
-    onExit "${exitCode}"
+  if declare -F trap::onExit &>/dev/null; then
+    log::debug "Executing custom ⌜trap::onExit⌝ function ."
+    trap::onExit "${exitCode}"
   fi
 
   if [[ ! -v GLOBAL_EXPECTED_EXIT ]]; then
@@ -119,9 +119,9 @@ function trap::onInterruptInternal() {
   fi
 
   # check if the function exists
-  if declare -F onInterrupt &>/dev/null; then
-    if onInterrupt; then
-      # if onInterrupt returns 0, then we cancel the interrupt
+  if declare -F trap::onInterrupt &>/dev/null; then
+    if trap::onInterrupt; then
+      # if trap::onInterrupt returns 0, then we cancel the interrupt
       return 0
     fi
   fi
@@ -133,9 +133,9 @@ function trap::onInterruptInternal() {
 function trap::onTerminateInternal() {
   log::print "ERROR" "${ICON_KILLED:-}" "KILLED" "Program killed."
   # check if the function exists
-  if declare -F onTerminate &>/dev/null; then
-    if onTerminate; then
-      # if onTerminate returns 0, then we cancel the termination
+  if declare -F trap::onTerminate &>/dev/null; then
+    if trap::onTerminate; then
+      # if trap::onTerminate returns 0, then we cancel the termination
       return 0
     fi
   fi
@@ -147,25 +147,34 @@ function trap::onTerminateInternal() {
 
 # This function is called when terminal changes its size.
 function trap::onResizeInternal() {
+  local currentSize="${GLOBAL_COLUMNS}x${GLOBAL_LINES}"
   terminal::getTerminalSize
+  local newSize="${GLOBAL_COLUMNS}x${GLOBAL_LINES}"
+
+  if [[ ${currentSize} == "${newSize}" ]]; then
+    log::debug "Terminal size did not change, still ⌜${currentSize}⌝."
+    return 0
+  fi
+  log::debug "Terminal size changed from ⌜${currentSize}⌝ to ⌜${newSize}⌝."
+
   # shellcheck disable=SC2034
   GLOBAL_SCREEN_REDRAW_REQUIRED=true
+
   # need to re init the logs because might depend on the number of columns for wrapping
   log::init
+
   if declare -F progress::onResize &>/dev/null; then
     progress::onResize
   fi
-  if declare -F onResize &>/dev/null; then
-    onResize
+  if declare -F trap::onResize &>/dev/null; then
+    trap::onResize
   fi
 }
 
 # This functions is called before the program exits (in all cases, error or not).
 function trap::onCleanUpInternal() {
-  # disable the profiler if still on
-  if [[ ${GLOBAL_PROFILER_ENABLED:-} == "true" ]]; then
-    profiler::disable
-  fi
+  # restore the terminal as it was before running this program
+  trap::restoreTerminal
 
   # kill background processes if still running
   if (( ${#GLOBAL_BACKGROUND_PIDS[@]} > 0 )); then
@@ -175,27 +184,95 @@ function trap::onCleanUpInternal() {
     done
   fi
 
+  # call the clean up functions if they exist
+  if declare -F trap::onCleanUp &>/dev/null; then
+    trap::onCleanUp
+  fi
+
+  # disable the profiler if still on
+  if [[ ${GLOBAL_PROFILER_ENABLED:-} == "true" ]]; then
+    profiler::disable
+  fi
+
+  fs::cleanTempFiles
+}
+
+# restore the terminal in its original state, before running valet
+function trap::restoreTerminal() {
   # if we are in interactive mode, we need to restore the cursor
   if [[ -t ${GLOBAL_FD_TUI} && ${VALET_CONFIG_DISABLE_ESC_CODES:-} != "true" ]]; then
     printf '%s' $'\e[?25h' 1>&"${GLOBAL_FD_TUI}" # ESC__CURSOR_SHOW_FORCE
   fi
 
-  # restore tty settings if needed
-  if declare -F terminal::restoreSettings &>/dev/null; then
-    terminal::restoreSettings
+  # if we were in interactive mode, we need to restore the logs
+  if [[ ${GLOBAL_LOG_REROUTED_TO_FILE_ENABLED:-} == "true" ]]; then
+    terminal::restoreLogs
+    GLOBAL_LOG_REROUTED_TO_FILE_ENABLED=true
   fi
 
-  # call the clean up functions if they exist
-  if declare -F cleanUp &>/dev/null; then
-    cleanUp
+  # restore tty settings if needed
+  if [[ ${GLOBAL_TERMINAL_RAW_MODE_ENABLED:-} == "true" ]]; then
+    terminal::restoreSettings
+    GLOBAL_TERMINAL_RAW_MODE_ENABLED=true
+  fi
+}
+
+# This function is called when the program is required to pause (stop/suspend).
+# Usually this is called when the user presses CTRL+Z in bash.
+function trap::onSuspendInternal() {
+  # check if the function exists
+  if declare -F onHalt &>/dev/null; then
+    if onHalt; then
+      # if onHalt returns 0, then we cancel the suspend
+      onHalt 0
+    fi
+  fi
+
+  # restore the terminal in its original state, before running valet
+  trap::restoreTerminal
+  
+  log::print "WARNING" "${ICON_HALT:-}" "PAUSED" "Program halted."
+
+  # now that we have set up everything for a suspend, we temporarily remove this trap
+  # and send the same signal again to let bash handle the suspend of the process
+  trap SIGTSTP
+  kill -TSTP "${BASHPID}" &>/dev/null || :
+}
+
+# This function is called when the program is required to resume its execution.
+function trap::onContinueInternal() {
+  log::print "INFO" "${ICON_HALT:-}" "RESUMED" "Program resumed (press any key to unfreeze)."
+
+  # we reregister the TSTP trap that removed on halt
+  trap trap::onSuspendInternal SIGTSTP
+
+  # check if the function exists
+  if declare -F onContinue &>/dev/null; then
+    onContinue
+  fi
+
+  # if we are in interactive mode, we need to hide the cursor
+  if [[ -t ${GLOBAL_FD_TUI} ]]; then
+    terminal::getTerminalSize
+    if [[ ${GLOBAL_SOURCED_FOR_PROMPT:-} != "true" ]]; then
+      # hide the cursor (we restore on exit)
+      printf "%s" "${ESC__CURSOR_HIDE}" 1>&"${GLOBAL_FD_TUI}"
+    fi
+  fi
+
+  # restore tty settings if needed
+  if [[ ${GLOBAL_TERMINAL_RAW_MODE_ENABLED:-} == "true" ]]; then
+    unset -v GLOBAL_TERMINAL_RAW_MODE_ENABLED
+    terminal::setRawMode
   fi
 
   # if we were in interactive mode, we need to restore the logs
-  if declare -F terminal::restoreLogs &>/dev/null; then
-    terminal::restoreLogs
+  if [[ ${GLOBAL_LOG_REROUTED_TO_FILE_ENABLED:-} == "true" ]]; then
+    unset -v GLOBAL_LOG_REROUTED_TO_FILE_ENABLED
+    terminal::rerouteLogs
   fi
 
-  fs::cleanTempFiles
+  GLOBAL_SCREEN_REDRAW_REQUIRED=true
 }
 
 # Function to handle commands not found, so we can display a better message.
@@ -238,10 +315,14 @@ function command_not_found_handle() {
 function trap::register() {
   trap trap::onErrorInternal ERR
   trap trap::onExitInternal EXIT
-  # Register CTRL+C SIGINT (interrupt) and CTRL+\ QUIT (interrupt with a coredump) event handler
+  # Register CTRL+C SIGINT (interrupt) and CTRL+\ SIGQUIT (interrupt with a coredump) event handler
   trap trap::onInterruptInternal SIGINT SIGQUIT
-  # Register SIGHUP (hang up, terminal disconnected) and TERM (terminate the program) event handler
+  # Register SIGHUP (hang up, terminal disconnected) and SIGTERM (terminate the program) event handler
   trap trap::onTerminateInternal SIGHUP SIGTERM
+  # Register CTRL+Z SIGTSTP (stop/suspend from tty)
+  trap trap::onSuspendInternal SIGTSTP
+  # Register SIGCONT (continue with fg or bg after suspend) event handler
+  trap trap::onContinueInternal SIGCONT
   if [[ -t 2 ]]; then
     # shellcheck disable=SC2034
     GLOBAL_SCREEN_REDRAW_REQUIRED=false
@@ -260,6 +341,8 @@ function trap::unregister() {
   trap SIGQUIT
   trap SIGHUP
   trap SIGTERM
+  trap SIGTSTP
+  trap SIGCONT
   if [[ -t 2 ]]; then
     trap SIGWINCH
   fi
@@ -326,6 +409,8 @@ function trap::registerSubshell() {
   # Register SIGHUP (hang up, terminal disconnected) and TERM (terminate the program) event handler
   trap 'exit 0' SIGHUP SIGTERM
   trap SIGWINCH
+  trap SIGTSTP
+  trap SIGCONT
 }
 
 #===============================================================
