:sparkles: better CTRL+C handling

diff --git a/libraries.d/core-traps b/libraries.d/core-traps
--- a/libraries.d/core-traps
+++ b/libraries.d/core-traps
@@ -8,6 +8,27 @@
 # >>> Traps
 #===============================================================
 
+# ## trap::register (private)
+#
+# Register the traps for the program.
+function trap::register() {
+  trap trap::onErrorInternal ERR
+  trap trap::onExitInternal EXIT
+  # Register CTRL+C SIGINT (interrupt) and CTRL+\ SIGQUIT (interrupt with a coredump) event handler
+  trap trap::onInterruptInternal SIGINT SIGQUIT
+  # Register SIGHUP (hang up, terminal disconnected) and SIGTERM (terminate the program) event handler
+  trap trap::onTerminateInternal SIGHUP SIGTERM
+  # Register CTRL+Z SIGTSTP (stop/suspend from tty)
+  trap trap::onSuspendInternal SIGTSTP
+  # Register SIGCONT (continue with fg or bg after suspend) event handler
+  trap trap::onContinueInternal SIGCONT
+  if [[ -t 2 ]]; then
+    # shellcheck disable=SC2034
+    GLOBAL_SCREEN_REDRAW_REQUIRED=false
+    trap trap::onResizeInternal SIGWINCH
+  fi
+}
+
 # This function is called when a command or pipeline returns a non-zero exit status.
 # It is executed in the same shell as the command that failed, as if we called this function
 # at the line where the command failed.
@@ -51,31 +72,12 @@ function trap::onErrorInternal() {
 # It is executed in the same shell that exited, as if we called this function
 # at the line where the exit command is called.
 function trap::onExitInternal() {
-  local exitCode="$?"
+  local exitCode="${?}"
 
-  # disable errexit to avoid exiting before cleaning up
-  set +o errexit
-
-  if [[ ${VALET_CONFIG_CORE_DUMP_ON_EXIT:-} == "true" || (${GLOBAL_EXPECTED_EXIT:-} != "true" && ${exitCode} != "0") ]]; then
-    dumpSuffix="-${exitCode}" core::dump
-  fi
-
-  log::debug "Exiting with code ${exitCode} after ${SECONDS}s."
-
-  if [[ ${GLOBAL_EXPECTED_EXIT:-} != "true" ]]; then
-    if [[ ${VALET_CONFIG_WARNING_ON_UNEXPECTED_EXIT:-} == "true" && ! ${BASH_COMMAND:-} =~ ^(exit|return) ]]; then
-      log::print "WARNING" "${ICON_EXIT:-}" "EXIT" "Unexpected exit with code ${exitCode}:"
-      log::printTrappedBashCommand
-      log::printCallStack
-    elif (( exitCode != 0 )); then
-      log::print "ERROR" "${ICON_EXIT:-}" "EXIT" "Exiting with code ${exitCode}, stack:"
-      log::printTrappedBashCommand
-      log::printCallStack
-    fi
-  fi
-
-  if [[ -n ${GLOBAL_ON_EXIT_MESSAGE:-} ]]; then
-    log::error "${GLOBAL_ON_EXIT_MESSAGE}"
+  # as we want to make sure that we execute the cleanup function, we use the fact that
+  # commands in if statements do not exit the program on error
+  if trap::onExitInternalSafe "${exitCode}"; then
+    :
   fi
 
   # always call cleanUp before exiting
@@ -95,6 +97,15 @@ function trap::onInterruptInternal() {
   # reset the trap to not call this function again
   trap SIGINT SIGQUIT
 
+  if [[ ${_TRAP_PROGRAM_INTERRUPTED:-} == "true" ]]; then
+    # we are here if the program was already interrupted,
+    # it can happen if the user pressed CTRL+C multiple times
+    # we are already exiting and we want the program to exit gracefully so
+    # stop there
+    return 0
+  fi
+  _TRAP_PROGRAM_INTERRUPTED=true
+
   if [[ -z ${GLOBAL_STTY_SAVED_CONFIG:-} ]]; then
     printf '\n' 1>&"${GLOBAL_FD_TUI}" # Set cursor to the next line of '^C' (only if stty echo is on)
   fi
@@ -112,6 +123,7 @@ function trap::onInterruptInternal() {
 }
 
 # This function is called when the program is terminated by the system (SIGHUP, SIGTERM).
+# It is called from the main process.
 function trap::onTerminateInternal() {
   # check if the function exists
   if declare -F trap::onTerminate &>/dev/null && trap::onTerminate; then
@@ -128,6 +140,9 @@ function trap::onTerminateInternal() {
 }
 
 # This function is called when terminal changes its size.
+# It is called from the main process and it will not be triggered if the program is
+# busy running an external command (e.g. sleep). Note that the builtin read command
+# also blocks this trigger only it is finished.
 function trap::onResizeInternal() {
   local currentSize="${GLOBAL_COLUMNS}x${GLOBAL_LINES}"
   terminal::getTerminalSize
@@ -154,82 +169,11 @@ function trap::onResizeInternal() {
   fi
 }
 
-# This functions is called before the program exits (in all cases, error or not).
-function trap::onCleanUpInternal() {
-  # kill background processes if still running
-  # we need to do this first because if one of the background is killed during "read"
-  # it will restore the tty as it was when it entered read, effectively discarding our trap::restoreTerminal
-  trap::killBackgroundProcesses
-
-  # restore the terminal as it was before running this program
-  trap::restoreTerminal
-
-  # call the clean up functions if they exist
-  if declare -F trap::onCleanUp &>/dev/null && trap::onCleanUp; then
-    # (we execute it in a if statement to disable errexit and avoid exiting the program)
-    :
-  fi
-
-  # disable the profiler if still on
-  if [[ ${GLOBAL_PROFILER_ENABLED:-} == "true" ]]; then
-    profiler::disable
-  fi
-
-  fs::cleanTempFiles
-}
-
-# restore the terminal in its original state, before running valet
-function trap::restoreTerminal() {
-  # if we are in interactive mode, we need to restore the cursor
-  if [[ -t ${GLOBAL_FD_TUI} && ${VALET_CONFIG_DISABLE_ESC_CODES:-} != "true" ]]; then
-    printf '%s' "${ESC__CURSOR_SHOW_FORCE:-$'\e[?25h'}" 1>&"${GLOBAL_FD_TUI}"
-    printf '%s' "${ESC__DISABLE_MOUSE_BUTTON_TRACKING:-$'\e[?1006l'$'\e[?1000l'}${ESC__DISABLE_MOUSE_ANY_EVENT_TRACKING:-$'\e[?1006l'$'\e[?1003l'}" 1>&"${GLOBAL_FD_TUI}"
-  fi
-
-  # if we were in interactive mode, we need to restore the logs
-  if [[ ${GLOBAL_LOG_REROUTED_TO_FILE_ENABLED:-} == "true" ]]; then
-    terminal::restoreLogs
-    GLOBAL_LOG_REROUTED_TO_FILE_ENABLED=true
-  fi
-
-  # restore tty settings if needed
-  if [[ ${GLOBAL_TERMINAL_RAW_MODE_ENABLED:-} == "true" ]]; then
-    terminal::restoreSettings
-    GLOBAL_TERMINAL_RAW_MODE_ENABLED=true
-  fi
-}
-
-# Kill all background processes that are still running.
-function trap::killBackgroundProcesses() {
-  if [[ ${#GLOBAL_BACKGROUND_PROCESSES[@]} -eq 0 ]]; then
-    return 0
-  fi
-
-  local coprocName
-  for coprocName in "${!GLOBAL_BACKGROUND_PROCESSES[@]}"; do
-    log::debug "Killing background process ${coprocName} with PID ${GLOBAL_BACKGROUND_PROCESSES[${coprocName}]}."
-    kill -INT "${GLOBAL_BACKGROUND_PROCESSES[${coprocName}]}" &>/dev/null || :
-    kill -HUP "${GLOBAL_BACKGROUND_PROCESSES[${coprocName}]}" &>/dev/null || :
-    # TODO: wait for the process to exit (max 500ms then kill -9)
-    if [[ -n ${GLOBAL_BACKGROUND_PROCESSES_LOGS[${coprocName}]:-} ]]; then
-      log::info "===================="$'\n'"Redirected logs for background process ${coprocName}:"
-      log::printString "===================="
-      # shellcheck disable=SC1091
-      source fs
-      fs::readFile "${GLOBAL_BACKGROUND_PROCESSES_LOGS[${coprocName}]:-}"
-      log::printRaw REPLY
-      log::printString "===================="
-    fi
-    log::info "!GLOBAL_BACKGROUND_PROCESSES -> ${!GLOBAL_BACKGROUND_PROCESSES[*]}"
-    log::info "GLOBAL_BACKGROUND_PROCESSES -> ${GLOBAL_BACKGROUND_PROCESSES[*]}"
-    log::info "GLOBAL_BACKGROUND_PROCESSES_LOGS -> ${GLOBAL_BACKGROUND_PROCESSES_LOGS[*]}"
-  done
-}
-
 # This function is called when the program is required to pause (stop/suspend).
 # Usually this is called when the user presses CTRL+Z in bash.
 function trap::onSuspendInternal() {
   # avoid multiple calls
+  # shellcheck disable=SC2034
   trap SIGTSTP
 
   # check if the function exists
@@ -237,6 +181,17 @@ function trap::onSuspendInternal() {
     # if trap::onSuspend returns 0, then we cancel the suspend
     # (we execute it in a if statement to disable errexit and avoid exiting the program)
     return 0
+  fi
+
+  # save these value to restore them on continue
+  # shellcheck disable=SC2034
+  declare -g \
+    GLOBAL_LOG_REROUTED_TO_FILE_ENABLED_SAVED="${GLOBAL_LOG_REROUTED_TO_FILE_ENABLED}" \
+    GLOBAL_TERMINAL_RAW_MODE_ENABLED_SAVED="${GLOBAL_TERMINAL_RAW_MODE_ENABLED}"
+
+  # if we were in interactive mode, we need to restore the logs
+  if [[ ${GLOBAL_LOG_REROUTED_TO_FILE_ENABLED:-} == "true" ]]; then
+    terminal::restoreLogs
   fi
 
   # restore the terminal in its original state, before running valet
@@ -272,17 +227,16 @@ function trap::onContinueInternal() {
   fi
 
   # restore tty settings if needed
-  if [[ ${GLOBAL_TERMINAL_RAW_MODE_ENABLED:-} == "true" ]]; then
-    unset -v GLOBAL_TERMINAL_RAW_MODE_ENABLED
+  if [[ ${GLOBAL_TERMINAL_RAW_MODE_ENABLED_SAVED:-} == "true" ]]; then
     terminal::setRawMode
   fi
 
   # if we were in interactive mode, we need to restore the logs
-  if [[ ${GLOBAL_LOG_REROUTED_TO_FILE_ENABLED:-} == "true" ]]; then
-    unset -v GLOBAL_LOG_REROUTED_TO_FILE_ENABLED
+  if [[ ${GLOBAL_LOG_REROUTED_TO_FILE_ENABLED_SAVED:-} == "true" ]]; then
     terminal::rerouteLogs
   fi
 
+  # shellcheck disable=SC2034
   GLOBAL_SCREEN_REDRAW_REQUIRED=true
 }
 
@@ -322,47 +276,155 @@ function command_not_found_handle() {
   # but we set $? to 1 so ERR trap is called
 }
 
-# ## trap::register (private)
-#
-# Register the traps for the program.
-function trap::register() {
-  trap trap::onErrorInternal ERR
-  trap trap::onExitInternal EXIT
-  # Register CTRL+C SIGINT (interrupt) and CTRL+\ SIGQUIT (interrupt with a coredump) event handler
-  trap trap::onInterruptInternal SIGINT SIGQUIT
-  # Register SIGHUP (hang up, terminal disconnected) and SIGTERM (terminate the program) event handler
-  trap trap::onTerminateInternal SIGHUP SIGTERM
-  # Register CTRL+Z SIGTSTP (stop/suspend from tty)
-  trap trap::onSuspendInternal SIGTSTP
-  # Register SIGCONT (continue with fg or bg after suspend) event handler
-  trap trap::onContinueInternal SIGCONT
-  if [[ -t 2 ]]; then
-    # shellcheck disable=SC2034
-    GLOBAL_SCREEN_REDRAW_REQUIRED=false
-    trap trap::onResizeInternal SIGWINCH
-  fi
-}
-
-# This function is called when a subshell exits (on error, on success, on exit, on interrupt).
-# It is executed in the process that exited, as if we called this function
+# This function is called when the program exits (on error, on success, on exit, on interrupt).
+# It is executed in the same shell that exited, as if we called this function
 # at the line where the exit command is called.
-function trap::onSubshellExitInternal() {
-  local exitCode="$?"
+function trap::onExitInternalSafe() {
+  local exitCode="${1}"
 
-  if [[ ${GLOBAL_EXPECTED_EXIT:-} != "true" && ${GLOBAL_SUBSHELL_LOG_ON_ERROR_EXIT:-} == "true" && ${exitCode} -ne 0 ]]; then
-    log::error "Exiting subshell depth ${BASH_SUBSHELL} with code ${exitCode}, stack:"
-    log::printTrappedBashCommand
-    log::printCallStack
-  elif log::isDebugEnabled; then
-    if log::isTraceEnabled; then
-      log::debug "Exiting subshell depth ${BASH_SUBSHELL} with code ${exitCode}, stack:"
+  if [[ ${VALET_CONFIG_CORE_DUMP_ON_EXIT:-} == "true" || (${GLOBAL_EXPECTED_EXIT:-} != "true" && ${exitCode} != "0") ]]; then
+    core::dump dumpSuffix="-exit-${exitCode}"
+  fi
+
+  # if we were in interactive mode, we need to restore the logs
+  if [[ ${GLOBAL_LOG_REROUTED_TO_FILE_ENABLED:-} == "true" ]]; then
+    terminal::restoreLogs
+  fi
+
+  log::debug "Exiting with code ${exitCode} after ${SECONDS}s."
+
+  if [[ ${GLOBAL_EXPECTED_EXIT:-} != "true" ]]; then
+    if [[ ${VALET_CONFIG_WARNING_ON_UNEXPECTED_EXIT:-} == "true" && ! ${BASH_COMMAND:-} =~ ^(exit|return) ]]; then
+      log::print "WARNING" "${ICON_EXIT:-}" "EXIT" "Unexpected exit with code ${exitCode}:"
       log::printTrappedBashCommand
       log::printCallStack
-    else
-      log::debug "Exiting subshell depth ${BASH_SUBSHELL} with code ${exitCode}."
+    elif ((exitCode != 0)); then
+      log::print "ERROR" "${ICON_EXIT:-}" "EXIT" "Exiting with code ${exitCode}, stack:"
+      log::printTrappedBashCommand
+      log::printCallStack
     fi
   fi
+
+  if [[ -n ${GLOBAL_ON_EXIT_MESSAGE:-} ]]; then
+    log::error "${GLOBAL_ON_EXIT_MESSAGE}"
+  fi
 }
+
+# This functions is called before the program exits (in all cases, error or not).
+# Important note: we can end up here while having the stdout/stderr redirected somewhere
+# else (for example because the program exited in a command &>/dev/null). So we need to make
+# sure to use our GLOBAL_FD variables to actually access the original stdout/stderr.
+function trap::onCleanUpInternal() {
+  if declare -F progress::stop &>/dev/null; then
+    progress::stop
+  fi
+
+  # kill background processes if still running
+  # we need to do this first because if one of the background is killed during "read"
+  # it will restore the tty as it was when it entered read, effectively discarding our trap::restoreTerminal
+  trap::killBackgroundProcesses
+
+  # restore the terminal as it was before running this program
+  trap::restoreTerminal
+
+  # call the clean up functions if they exist
+  if declare -F trap::onCleanUp &>/dev/null && trap::onCleanUp; then
+    # (we execute it in a if statement to disable errexit and avoid exiting the program)
+    :
+  fi
+
+  # disable the profiler if still on
+  if [[ ${GLOBAL_PROFILER_ENABLED:-} == "true" ]]; then
+    profiler::disable
+  fi
+
+  fs::cleanTempFiles
+}
+
+# restore the terminal in its original state, before running valet
+function trap::restoreTerminal() {
+  # Important note: we can end up here while having the stdout/stderr redirected somewhere
+  # else (for example because the program exited in a command &>/dev/null). So we need to make
+  # sure to use our GLOBAL_FD variables to actually access the original stdout/stderr.
+
+  # if we are in interactive mode, we need to restore the cursor
+  if [[ -t ${GLOBAL_FD_TUI} && ${VALET_CONFIG_DISABLE_ESC_CODES:-} != "true" ]]; then
+    printf '%s' "${ESC__CURSOR_SHOW_FORCE:-$'\e[?25h'}" 1>&"${GLOBAL_FD_TUI}"
+    printf '%s' "${ESC__DISABLE_MOUSE_BUTTON_TRACKING:-$'\e[?1006l'$'\e[?1000l'}${ESC__DISABLE_MOUSE_ANY_EVENT_TRACKING:-$'\e[?1006l'$'\e[?1003l'}" 1>&"${GLOBAL_FD_TUI}"
+  fi
+
+  # restore tty settings if needed
+  if [[ ${GLOBAL_TERMINAL_RAW_MODE_ENABLED:-} == "true" ]]; then
+    terminal::restoreSettings
+  fi
+}
+
+# Kill all background processes that are still running.
+function trap::killBackgroundProcesses() {
+  if [[ ${#GLOBAL_BACKGROUND_PROCESSES[@]} -eq 0 ]]; then
+    return 0
+  fi
+
+  local coprocName coprocPid coprocLogFile
+
+  # display the logs for on going background processes that redirected their output to a file
+  for coprocName in "${!GLOBAL_BACKGROUND_PROCESSES[@]}"; do
+    coprocPid="${GLOBAL_BACKGROUND_PROCESSES[${coprocName}]:-}"
+    coprocLogFile="${GLOBAL_BACKGROUND_PROCESSES_LOGS[${coprocName}]:-}"
+
+    if [[ -n ${coprocLogFile} && -s ${coprocLogFile} ]] && log::isDebugEnabled; then
+      log::debug "Redirected logs for on going background process ${coprocName} (pid ${coprocPid}):"
+      log::printString "------"
+      # shellcheck disable=SC1091
+      source fs
+      fs::readFile "${coprocLogFile}"
+      log::printRaw REPLY
+      log::printString "------"
+    fi
+  done
+
+  # send SIGHUP to all background processes to terminate them
+  for coprocName in "${!GLOBAL_BACKGROUND_PROCESSES[@]}"; do
+    coprocPid="${GLOBAL_BACKGROUND_PROCESSES[${coprocName}]:-}"
+    log::debug "Killing background process ${coprocName} with PID ${coprocPid}."
+    kill -HUP "${coprocPid}" &>/dev/null || :
+  done
+
+  # wait for them to finish or force kill them after a timeout (500ms - 100ms per subshell level)
+  time::getProgramElapsedMicroseconds
+  local -i startTime=${REPLY} nowTime=${REPLY}
+  for coprocName in "${!GLOBAL_BACKGROUND_PROCESSES[@]}"; do
+    coprocPid="${GLOBAL_BACKGROUND_PROCESSES[${coprocName}]:-}"
+    coprocLogFile="${GLOBAL_BACKGROUND_PROCESSES_LOGS[${coprocName}]:-}"
+    while kill -0 "${coprocPid}" &>/dev/null && ((nowTime - startTime < 500000 - BASH_SUBSHELL * 100000)); do
+      time::getProgramElapsedMicroseconds
+      nowTime=${REPLY}
+    done
+  done
+
+  # if we did not manage to kill the background processes in time, we spawn a coproc to kill them later
+  if ((nowTime - startTime >= 500000 - BASH_SUBSHELL * 100000)); then
+    disown
+    log::debug "Some background processes did not terminate in time, starting a coproc to kill them asynchronously."
+    # shellcheck disable=SC2034
+    # shellcheck disable=SC2317
+    function coproc_killer() {
+      # shellcheck disable=SC1091
+      source bash
+      local IFS=' '
+      GLOBAL_LOG_LEVEL_INT=9
+      bash::sleep 5
+      kill -9 ${GLOBAL_BACKGROUND_PROCESSES[*]}
+      bash::sleep 5
+      fs::cleanTempFiles
+    }
+    eval "{ coproc _coproc_killer { if coproc_killer; then : ; fi } } &>/dev/null"
+  fi
+}
+
+#===============================================================
+# >>> Traps for subshells
+#===============================================================
 
 # ## trap::registerForSubshell (private)
 #
@@ -380,11 +442,11 @@ function trap::onSubshellExitInternal() {
 # > - coproc and jobs will not get SIGHUP when the main process ends and they will continue to execute
 # >   until killed or until they check that the main process is dead.
 function trap::registerSubshell() {
-  if (( BASH_SUBSHELL == 0 )); then
+  if ((BASH_SUBSHELL == 0)); then
     core::fail "This function should only be called in a subshell."
   fi
 
-  # in case we are in a subshell called within a bash::catchErrors, we reset errexit
+  # in case we are in a subshell called within a bash::catchErrors, we reset errexit and not longer catch errors
   unset -v GLOBAL_ERROR_TRAP_TRY_MODE_ENABLED
   set -o errexit
 
@@ -394,13 +456,42 @@ function trap::registerSubshell() {
     GLOBAL_SUBSHELL_LOG_ON_ERROR_EXIT=false
   fi
 
-  trap trap::onErrorInternal ERR
+  trap '_TRAP_SUBSHELL_EXIT_REASON=ERROR trap::onErrorInternal' ERR
   trap trap::onSubshellExitInternal EXIT
   # Register CTRL+C SIGINT (interrupt) and CTRL+\ QUIT (interrupt with a coredump) event handler
-  trap 'exit 0' SIGINT SIGQUIT
+  trap '_TRAP_SUBSHELL_EXIT_REASON=SIGINT exit 0' SIGINT SIGQUIT
   # Register SIGHUP (hang up, terminal disconnected) and TERM (terminate the program) event handler
-  trap 'exit 0' SIGHUP SIGTERM
+  trap '_TRAP_SUBSHELL_EXIT_REASON=SIGTERM exit 0' SIGHUP SIGTERM
   trap SIGWINCH
   trap SIGTSTP
   trap SIGCONT
+}
+
+# This function is called when a subshell exits (on error, on success, on exit, on interrupt).
+# It is executed in the process that exited, as if we called this function
+# at the line where the exit command is called.
+function trap::onSubshellExitInternal() {
+  local exitCode="$?"
+
+  local reason
+  case "${_TRAP_SUBSHELL_EXIT_REASON:-}" in
+  ERROR) reason=" (exited because of an error)" ;;
+  SIGINT) reason=" (got interrupted)" ;;
+  SIGTERM) reason=" (got terminated)" ;;
+  *) reason="" ;;
+  esac
+
+  if [[ ${GLOBAL_EXPECTED_EXIT:-} != "true" && ${GLOBAL_SUBSHELL_LOG_ON_ERROR_EXIT:-} == "true" && ${exitCode} -ne 0 ]]; then
+    log::error "Exiting subshell${reason} depth ${BASH_SUBSHELL} with code ${exitCode}, stack:"
+    log::printTrappedBashCommand
+    log::printCallStack
+  elif log::isDebugEnabled; then
+    if log::isTraceEnabled; then
+      log::debug "Exiting subshell${reason} depth ${BASH_SUBSHELL} with code ${exitCode}, stack:"
+      log::printTrappedBashCommand
+      log::printCallStack
+    else
+      log::debug "Exiting subshell${reason} depth ${BASH_SUBSHELL} with code ${exitCode}."
+    fi
+  fi
 }
diff --git a/libraries.d/lib-terminal b/libraries.d/lib-terminal
--- a/libraries.d/lib-terminal
+++ b/libraries.d/lib-terminal
@@ -7,7 +7,6 @@ source bash
 # shellcheck source=lib-fs
 source fs
 
-
 #===============================================================
 # >>> Interactive utilities
 #===============================================================
@@ -31,7 +30,7 @@ source fs
 function terminal::createSpace() {
   local -i nbLines="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
   nbLines=$((nbLines > GLOBAL_LINES ? GLOBAL_LINES : nbLines))
-  if (( nbLines <= 1 )); then
+  if ((nbLines <= 1)); then
     printf '%s' "${ESC__CURSOR_HIDE}${ESC__CURSOR_MOVE__}1${__ESC__COLUMN}${ESC__ERASE_LINE}${ESC__CURSOR_SHOW}" 1>&"${GLOBAL_FD_TUI}"
     return 0
   fi
@@ -113,24 +112,27 @@ function terminal::setRawMode() {
   if [[ ${GLOBAL_TERMINAL_RAW_MODE_ENABLED:-} == "true" ]]; then
     return 0
   fi
+  if [[ ! -t ${GLOBAL_FD_ORIGINAL_STDIN} && ${GLOBAL_TEST_FORCE_FD_OPEN:-} != "true" ]]; then
+    core::fail "stdin is not a terminal, cannot reset mode."
+  fi
   if [[ -z ${GLOBAL_STTY_SAVED_CONFIG:-} ]]; then
-    bash::getBuiltinOutput stty -g
-    if [[ -z ${REPLY} ]]; then
+    if stty -g <&"${GLOBAL_FD_ORIGINAL_STDIN:-0}" &>"${GLOBAL_TEMPORARY_STDOUT_FILE}"; then
+      IFS='' read -rd '' REPLY <"${GLOBAL_TEMPORARY_STDOUT_FILE}" || :
+    else
       core::fail "Unable to get the current terminal configuration. Please make sure that ⌜stty⌝ is available in your PATH."
     fi
     GLOBAL_STTY_SAVED_CONFIG="${REPLY%%$'\n'}"
     log::debug "Saved terminal stty initial settings: ${GLOBAL_STTY_SAVED_CONFIG}."
   fi
-  if [[ ! -t 0 && ${GLOBAL_TEST_FORCE_FD_OPEN:-} != "true" ]]; then
-    core::fail "stdin is not a terminal, cannot set raw mode."
-  fi
   # we try to set specific settings and if it fails, we just set raw mode
-  stty -icrnl -inlcr -ixon -ixoff \
-    nl0 cr0 tab0 ff0 -onlret \
-    -icanon -echo -echok -echonl -echoe -echoke -ctlecho -tostop \
-    erase ^B werase ^W \
-    min 1 time 0 || \
-    stty raw -echo || core::fail "Failed to set the terminal in raw mode, check stty version."
+  {
+    stty -icrnl -inlcr -ixon -ixoff \
+      nl0 cr0 tab0 ff0 -onlret \
+      -icanon -echo -echok -echonl -echoe -echoke -ctlecho -tostop \
+      erase ^B werase ^W \
+      min 1 time 0 ||
+      stty raw -echo || core::fail "Failed to set the terminal in raw mode, check stty version."
+  } <&"${GLOBAL_FD_ORIGINAL_STDIN:-0}"
   GLOBAL_TERMINAL_RAW_MODE_ENABLED=true
 }
 
@@ -151,14 +153,10 @@ function terminal::restoreSettings() {
   if [[ ${GLOBAL_TERMINAL_RAW_MODE_ENABLED:-} != "true" || ! -v GLOBAL_STTY_SAVED_CONFIG || ${BASH_SUBSHELL} -ne 0 ]]; then
     return 0
   fi
-  if [[ ! -t 0 && ${GLOBAL_TEST_FORCE_FD_OPEN:-} != "true" ]]; then
-    if [[ -n ${GLOBAL_FD_ORIGINAL_STDIN:-} && -t ${GLOBAL_FD_ORIGINAL_STDIN:-} ]] && exec 0<&"${GLOBAL_FD_ORIGINAL_STDIN}"; then
-      log::debug "Restored terminal fd before using stty command."
-    else
-      core::fail "stdin is not a terminal, cannot reset mode."
-    fi
+  if [[ ! -t ${GLOBAL_FD_ORIGINAL_STDIN} && ${GLOBAL_TEST_FORCE_FD_OPEN:-} != "true" ]]; then
+    core::fail "stdin is not a terminal, cannot reset mode."
   fi
-  stty "${GLOBAL_STTY_SAVED_CONFIG}" || log::warning "Failed to restore the terminal settings, check stty version."
+  stty "${GLOBAL_STTY_SAVED_CONFIG}" <&"${GLOBAL_FD_ORIGINAL_STDIN:-}" 2>&"${GLOBAL_FD_LOG}" || log::warning "Failed to restore the terminal settings, check stty version."
   log::debug "Restored terminal settings using: stty ${GLOBAL_STTY_SAVED_CONFIG}."
   unset -v GLOBAL_TERMINAL_RAW_MODE_ENABLED
 }
@@ -377,7 +375,6 @@ function terminal::getBestAutocompleteBox() {
   REPLY4="${height}"
 }
 
-
 #===============================================================
 # >>> Key press detection
 #===============================================================
@@ -484,8 +481,7 @@ function terminal::waitForChar() {
     esac
   else
 
-
-    if (( ${#LAST_KEY_PRESSED} > 1 )); then
+    if ((${#LAST_KEY_PRESSED} > 1)); then
       # if we have more than one char, we store the extra chars for the next read
       PREVIOUS_KEY_PRESSED_EXTRA_CHARS="${LAST_KEY_PRESSED:1}"
       LAST_KEY_PRESSED="${LAST_KEY_PRESSED:0:1}"
@@ -557,7 +553,7 @@ function terminal::waitForKeyPress() {
     read "$@" -d '' -s -r -N 1 2>/dev/null
     LAST_KEY_PRESSED+="${REPLY}"
   done
-  if (( ${#LAST_KEY_PRESSED} > 1 )); then
+  if ((${#LAST_KEY_PRESSED} > 1)); then
     # if we have more than one char, we store the extra chars for the next read
     PREVIOUS_KEY_PRESSED_EXTRA_CHARS="${LAST_KEY_PRESSED:1}"
     LAST_KEY_PRESSED="${LAST_KEY_PRESSED:0:1}"
@@ -626,7 +622,6 @@ function terminal::rebindKeymap() {
     bind -r "${key%:}"
   done
 
-
   # some other default values to ensure we get the right behavior
   bind 'set bind-tty-special-chars on'
   bind 'set echo-control-characters on'
@@ -656,8 +651,8 @@ function terminal::rebindKeymap() {
     "ALT+" "\e"
   )
   local -i index modeIndex
-  for((index=0;index<${#normalKeys};index++)); do
-    for((modeIndex=0;modeIndex<${#modifiers[@]};modeIndex+=2)); do
+  for ((index = 0; index < ${#normalKeys}; index++)); do
+    for ((modeIndex = 0; modeIndex < ${#modifiers[@]}; modeIndex += 2)); do
       key="${normalKeys:index:1}"
       bind -x "\"${modifiers[modeIndex + 1]}${key}\": ${callBackFunction} ${modifiers[modeIndex]}${key^^}"
     done
@@ -702,8 +697,8 @@ function terminal::rebindKeymap() {
     "CTRL+SHIFT+" ";6"
     "CTRL+ALT+" ";7"
   )
-  for((index=0;index<${#specialKeys[@]};index+=2)); do
-    for((modeIndex=0;modeIndex<${#modifiers[@]};modeIndex+=2)); do
+  for ((index = 0; index < ${#specialKeys[@]}; index += 2)); do
+    for ((modeIndex = 0; modeIndex < ${#modifiers[@]}; modeIndex += 2)); do
       key="${specialKeys[index]}"
       bind -x "\"\e${key//\?/"${modifiers[modeIndex + 1]}"}\": ${callBackFunction} ${modifiers[modeIndex]}${specialKeys[index + 1]}"
       # I have noticed that sometimes the terminal sends the sequence without the \e...
@@ -751,8 +746,8 @@ function terminal::rebindKeymap() {
     "CTRL+SHIFT+" "1;6"
     "CTRL+ALT+" "1;7"
   )
-  for((index=0;index<${#specialKeys2[@]};index+=2)); do
-    for((modeIndex=0;modeIndex<${#modifiers[@]};modeIndex+=2)); do
+  for ((index = 0; index < ${#specialKeys2[@]}; index += 2)); do
+    for ((modeIndex = 0; modeIndex < ${#modifiers[@]}; modeIndex += 2)); do
       key="${specialKeys2[index]}"
       bind -x "\"\e${key//\?/"${modifiers[modeIndex + 1]}"}\": ${callBackFunction} ${modifiers[modeIndex]}${specialKeys2[index + 1]}"
       # I have noticed that sometimes the terminal sends the sequence without the \e...
