:recycle: improving error handling

diff --git a/libraries.d/core-traps b/libraries.d/core-traps
--- a/libraries.d/core-traps
+++ b/libraries.d/core-traps
@@ -21,9 +21,9 @@ function trap::onErrorInternal() {
 
   if [[ ${FUNCNAME[1]:-} == "log::"* ]]; then
     # we are here if the error happened in a log function and thus we couldn't print the error
-    printf '%s\n%s\n%s\n' "The command had a return code of ${errorCodesString}." "Error in a log function:" "${BASH_COMMAND:-}" >&2
-    log::getCallStack 2
-    printf '%s\n' "${REPLY}" >&2
+    printf '%s\n%s\n%s\n' "The command had a return code of ${errorCodesString}." "Error in a log function:" "${BASH_COMMAND:-}" >&"${GLOBAL_FD_LOG}"
+    log::getCallStack stackToSkip=2
+    printf '%s\n' "${REPLY}" >&"${GLOBAL_FD_LOG}"
     return 0
   fi
 
@@ -32,7 +32,7 @@ function trap::onErrorInternal() {
     if log::isTraceEnabled; then
       log::trace "Caught error in try/catch mode, error code ${errorCodesString} for the command:"
       log::printTrappedBashCommand
-      log::printCallStack 2
+      log::printCallStack
     fi
     # shellcheck disable=SC2034
     GLOBAL_ERROR_TRAP_LAST_ERROR_CODE="${errorCodes[0]}"
@@ -41,7 +41,7 @@ function trap::onErrorInternal() {
 
   log::print "ERROR" "${ICON_ERROR:-}" "CMDERR" "Error code ${errorCodesString} for the command:"
   log::printTrappedBashCommand
-  log::printCallStack 2
+  log::printCallStack
 
   : before-exit
   core::exit 1 silent=true
@@ -53,6 +53,9 @@ function trap::onErrorInternal() {
 function trap::onExitInternal() {
   local exitCode="$?"
 
+  # disable errexit to avoid exiting before cleaning up
+  set +o errexit
+
   if [[ ${VALET_CONFIG_CORE_DUMP_ON_EXIT:-} == "true" || (${GLOBAL_EXPECTED_EXIT:-} != "true" && ${exitCode} != "0") ]]; then
     dumpSuffix="-${exitCode}" core::dump
   fi
@@ -63,11 +66,11 @@ function trap::onExitInternal() {
     if [[ ${VALET_CONFIG_WARNING_ON_UNEXPECTED_EXIT:-} == "true" && ! ${BASH_COMMAND:-} =~ ^(exit|return) ]]; then
       log::print "WARNING" "${ICON_EXIT:-}" "EXIT" "Unexpected exit with code ${exitCode}:"
       log::printTrappedBashCommand
-      log::printCallStack 2
+      log::printCallStack
     elif (( exitCode != 0 )); then
       log::print "ERROR" "${ICON_EXIT:-}" "EXIT" "Exiting with code ${exitCode}, stack:"
       log::printTrappedBashCommand
-      log::printCallStack 2
+      log::printCallStack
     fi
   fi
 
@@ -77,6 +80,8 @@ function trap::onExitInternal() {
 
   # always call cleanUp before exiting
   trap::onCleanUpInternal
+  echo "done ${BASHPID}">>/c/Users/jcaillon/data/repo/github.com/jcaillon/valet/tmp/log
+
 }
 
 # This function is called when the program is interrupted by the user (CTRL+C).
@@ -90,21 +95,26 @@ function trap::onInterruptInternal() {
       return 0
     fi
   fi
+  echo "interrupted ${BASHPID}">>/c/Users/jcaillon/data/repo/github.com/jcaillon/valet/tmp/log
 
   # reset the trap to not call this function again
   trap SIGINT SIGQUIT
 
   if [[ -z ${GLOBAL_STTY_SAVED_CONFIG:-} ]]; then
-    printf '\n' # Set cursor to the next line of '^C' (only if stty echo is on)
+    printf '\n' 1>&"${GLOBAL_FD_TUI}" # Set cursor to the next line of '^C' (only if stty echo is on)
   fi
   if [[ ${GLOBAL_WARN_ON_INTERRUPT_DISABLED:-} != "true" ]]; then
+    ls -l /proc/"${BASHPID}"/fd>>/c/Users/jcaillon/data/repo/github.com/jcaillon/valet/tmp/log
+    log::getCallStack stackToSkip=2
+    printf '%s\n' "${REPLY}" >>/c/Users/jcaillon/data/repo/github.com/jcaillon/valet/tmp/log
+
     log::print "WARNING" "${ICON_STOPPED:-}" "STOPPED" "Program interrupted by the user."
   fi
 
   if log::isDebugEnabled; then
     log::debug "Is your command stuck? Consider using the ⌜-x⌝ option to activate the profiler and identify what's wrong. Here is the current stack:"
     log::printTrappedBashCommand
-    log::printCallStack 2
+    log::printCallStack
   fi
 
   core::exit 1 silent=true
@@ -158,14 +168,7 @@ function trap::onCleanUpInternal() {
   # kill background processes if still running
   # we need to do this first because if one of the background is killed during "read"
   # it will restore the tty as it was when it entered read, effectively discarding our trap::restoreTerminal
-  if (( ${#GLOBAL_BACKGROUND_PIDS[@]} > 0 )); then
-    local pid
-    for pid in "${GLOBAL_BACKGROUND_PIDS[@]}"; do
-      log::debug "Killing background process with PID ${pid}."
-      kill -INT "${pid}" &>/dev/null || :
-      kill -HUP "${pid}" &>/dev/null || :
-    done
-  fi
+  trap::killBackgroundProcesses
 
   # restore the terminal as it was before running this program
   trap::restoreTerminal
@@ -202,6 +205,30 @@ function trap::restoreTerminal() {
     terminal::restoreSettings
     GLOBAL_TERMINAL_RAW_MODE_ENABLED=true
   fi
+}
+
+# Kill all background processes that are still running.
+function trap::killBackgroundProcesses() {
+  if [[ ${#GLOBAL_BACKGROUND_PROCESSES[@]} -eq 0 ]]; then
+    return 0
+  fi
+
+  local coprocName
+  for coprocName in "${!GLOBAL_BACKGROUND_PROCESSES[@]}"; do
+    log::debug "Killing background process ${coprocName} with PID ${GLOBAL_BACKGROUND_PROCESSES[${coprocName}]}."
+    kill -INT "${GLOBAL_BACKGROUND_PROCESSES[${coprocName}]}" &>/dev/null || :
+    kill -HUP "${GLOBAL_BACKGROUND_PROCESSES[${coprocName}]}" &>/dev/null || :
+    # TODO: wait for the process to exit (max 500ms then kill -9)
+    if [[ -n ${GLOBAL_BACKGROUND_PROCESSES_LOGS[${coprocName}]:-} ]]; then
+      log::info "===================="$'\n'"Redirected logs for background process ${coprocName}:"
+      log::printString "===================="
+      # shellcheck disable=SC1091
+      source fs
+      fs::readFile "${GLOBAL_BACKGROUND_PROCESSES_LOGS[${coprocName}]:-}"
+      log::printRaw REPLY
+      log::printString "===================="
+    fi
+  done
 }
 
 # This function is called when the program is required to pause (stop/suspend).
@@ -281,15 +308,17 @@ function command_not_found_handle() {
   fi
 
   # check for recursive call
-  if [[ -v GLOBAL_COMMAND_NOT_FOUND ]]; then
+  if ((${GLOBAL_COMMAND_NOT_FOUND:-0} > 1)); then
+    return 1
+  elif ((${GLOBAL_COMMAND_NOT_FOUND:-0} == 1)); then
     # we are here if the error happened in a log function and thus we couldn't print the error
-    printf '%s\n%s\n' "Command not found: ⌜${commandNotFound}⌝." "Error in a log function." >&2
-    log::getCallStack 2
-    printf '%s\n' "${REPLY}" >&2
+    printf '%s\n%s\n' "Command not found: ⌜${commandNotFound}⌝." "Error in a log function." >&"${GLOBAL_FD_LOG}"
+    log::getCallStack stackToSkip=2
+    printf '%s\n' "${REPLY}" >&"${GLOBAL_FD_LOG}"
   else
-    GLOBAL_COMMAND_NOT_FOUND=1
+    GLOBAL_COMMAND_NOT_FOUND=$((${GLOBAL_COMMAND_NOT_FOUND:-0} + 1))
     log::print "ERROR" "${ICON_ERROR:-}" "CMDMISS" "${errorMessage}"
-    log::printCallStack 2
+    log::printCallStack
   fi
 
   GLOBAL_EXPECTED_EXIT=true
@@ -328,12 +357,12 @@ function trap::onSubshellExitInternal() {
   if [[ ${GLOBAL_EXPECTED_EXIT:-} != "true" && ${GLOBAL_SUBSHELL_LOG_ON_ERROR_EXIT:-} == "true" && ${exitCode} -ne 0 ]]; then
     log::error "Exiting subshell depth ${BASH_SUBSHELL} with code ${exitCode}, stack:"
     log::printTrappedBashCommand
-    log::printCallStack 2
+    log::printCallStack
   elif log::isDebugEnabled; then
     if log::isTraceEnabled; then
       log::debug "Exiting subshell depth ${BASH_SUBSHELL} with code ${exitCode}, stack:"
       log::printTrappedBashCommand
-      log::printCallStack 2
+      log::printCallStack
     else
       log::debug "Exiting subshell depth ${BASH_SUBSHELL} with code ${exitCode}."
     fi
diff --git a/libraries.d/lib-coproc b/libraries.d/lib-coproc
--- a/libraries.d/lib-coproc
+++ b/libraries.d/lib-coproc
@@ -72,7 +72,7 @@ function coproc::runInParallel() {
   local -a -i pids=() runningPids=() exitCodes=()
   local -i index pid endedCoprocPid endedCoprocExitStatus endedCoprocIndex
   local -a logFiles=()
-  local logFile=""
+  local logFile="" coprocName
 
   for ((index = 0; index < ${#jobCommands[@]}; index++)); do
     if [[ ${redirectLogs} == "true" || ${printRedirectedLogs} == "true" ]]; then
@@ -81,7 +81,9 @@ function coproc::runInParallel() {
     fi
     logFiles+=("${logFile}")
 
-    coproc::run "${coprocNamePrefix}${index}" \
+    coprocName="${coprocNamePrefix}${index}"
+
+    coproc::run "${coprocName}" \
       initCommand="${jobCommands[index]}" \
       redirectLogsToFile="${logFile}" \
       logOnErrorExit="${logOnErrorExit}"
@@ -110,7 +112,7 @@ function coproc::runInParallel() {
       log::debug "The parallel coproc ${endedCoprocIndex} with PID ${endedCoprocPid} is completed with code ${endedCoprocExitStatus}."
 
       # remove the coproc from the list of running pids
-      coproc_removePidFromBackgroundPids "${endedCoprocPid}"
+      coproc_cleanBackgroundProcess "${coprocName}"
       local pidIndex
       for pidIndex in "${!runningPids[@]}"; do
         if [[ ${runningPids[pidIndex]} == "${endedCoprocPid}" ]]; then
@@ -231,7 +233,7 @@ function coproc::run() {
   shift 1
   eval "local a= ${*@Q}"
 
-  if [[ -v "${coprocVarName}" ]]; then
+  if [[ -v "GLOBAL_BACKGROUND_PROCESSES[${coprocVarName}]" ]]; then
     core::fail "The coproc ⌜${coprocVarName}⌝ is already running."
   fi
 
@@ -244,7 +246,9 @@ function coproc::run() {
   # wait for pid variable to be set by bash (we should never enter the loop)
   local -i loopNumber=0
   while [[ ! -v "${coprocVarName}_PID" && ${loopNumber} -lt 500 ]]; do
-    sleep 0.01
+    # shellcheck disable=SC1091
+    source bash
+    bash::sleep 0.01
     loopNumber+=1
   done
 
@@ -252,14 +256,21 @@ function coproc::run() {
   if ! eval "local pid=\${${coprocVarName}_PID:-}" || [[ -z ${pid} ]]; then
     core::fail "Failed to get the PID for coproc ⌜${coprocVarName}⌝."
   fi
-  GLOBAL_BACKGROUND_PIDS+=("${pid}")
+
+  GLOBAL_BACKGROUND_PROCESSES["${coprocVarName}"]="${pid}"
+
+  if [[ -n ${redirectLogsToFile} ]]; then
+    # shellcheck disable=SC2034
+    GLOBAL_BACKGROUND_PROCESSES_LOGS["${coprocVarName}"]="${redirectLogsToFile}"
+  fi
 
   # tell the coproc to resume (it is waiting for the main thread to retrieve its PID)
   coproc::sendMessage "${coprocVarName}" ":"
 
   # wait for readiness if requested
   if [[ ${waitForReadiness} == "true" ]]; then
-    if ! kill -0 "${pid}" 2>/dev/null || ! coproc::receiveMessage "${coprocVarName}"; then
+    coproc::receiveMessage "${coprocVarName}"
+    if ((REPLY_CODE != 0)); then
       core::fail "The coproc ⌜${coprocVarName}⌝ did not start correctly."
     elif [[ ${REPLY} != "ready" ]]; then
       core::fail "The coproc ⌜${coprocVarName}⌝ did not send the expected readiness message."
@@ -290,12 +301,11 @@ function coproc_program() {
   # the coproc must have its own set of temp files
   fs::setupSubshellTempFileGlobalVariable
 
-  # unset options or they will be visible from the subshell and might interfere
   local IFS=' '$'\t'$'\n'
-  unset -v ${!_OPTION_*}
 
   if [[ -n ${redirectLogsToFile} ]]; then
-    log::init "${redirectLogsToFile}"
+    exec 2>"${redirectLogsToFile}"
+    log::init 2
   fi
 
   # wait for the main process to retrieve our PID
@@ -355,17 +365,18 @@ function coproc_program() {
 # ```bash
 # coproc::sendMessage "myCoproc" "Hello, coproc!"
 # ```
+#
+# > This printf call can cause the whole shell to exit with code 141 if there is an issue with the coproc.
+# > You will want to run this in a subshell to avoid exiting the main shell if your coproc is unstable.
 function coproc::sendMessage() {
   local coprocVarName="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
 
-  if ! eval "local coprocFd=\${${coprocVarName}[1]:-}" || [[ -z ${coprocFd} ]]; then
-    return 1
+  if eval "local coprocFd=\${${coprocVarName}[1]:-}" && [[ -n ${coprocFd} ]]; then
+    # This printf call can cause the whole shell to exit with code 141 if there is an issue
+    if { printf '%s\0' "${2?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}" >&"${coprocFd}"; } 2>/dev/null; then
+      return 0
+    fi
   fi
-
-  if { printf '%s\0' "${2?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}" >&"${coprocFd}"; } 2>/dev/null; then
-    return 0
-  fi
-
   return 1
 }
 
@@ -391,46 +402,13 @@ function coproc::sendMessage() {
 function coproc::receiveMessage() {
   local coprocVarName="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
 
-  if ! eval "local coprocFd=\${${coprocVarName}[0]:-}" || [[ -z ${coprocFd} ]]; then
-    return 1
+  REPLY=""
+  if eval "local coprocFd=\${${coprocVarName}[0]:-}" && [[ -n ${coprocFd} ]]; then
+    if { IFS=$'\0' read -rd $'\0' -u "${coprocFd}" REPLY; } 2>/dev/null; then
+      return 0
+    fi
   fi
-
-  if { IFS=$'\0' read -rd $'\0' -u "${coprocFd}" REPLY; } 2>/dev/null; then
-    return 0
-  fi
-
   return 1
-}
-
-# ## coproc::wait
-#
-# This function waits for a coproc to finish.
-#
-# - $1: **coproc variable name** _as string_:
-#       The variable name to use for the coproc.
-#
-# Returns:
-# - $?: The exit status of the coproc (or 0 if the coproc is not running).
-#
-# ```bash
-# coproc::wait "myCoproc"
-# ```
-function coproc::wait() {
-  local coprocVarName="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
-
-  if ! eval "local pid=\${${coprocVarName}_PID:-}" || [[ -z ${pid} ]]; then
-    return 0
-  fi
-
-  log::debug "Waiting for coproc ⌜${coprocVarName}⌝ (PID: ${pid}) to finish."
-
-  local -i exitStatus=0
-  if ! wait -f "${pid}"; then
-    exitStatus="${PIPESTATUS[0]:-}"
-  fi
-
-  coproc_removePidFromBackgroundPids "${pid}"
-  return "${exitStatus}"
 }
 
 # ## coproc::isRunning
@@ -454,13 +432,45 @@ function coproc::wait() {
 function coproc::isRunning() {
   local coprocVarName="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
 
-  if ! eval "local pid=\${${coprocVarName}_PID:-}" || [[ -z ${pid} ]]; then
-    return 1
+  if eval "local pid=\${${coprocVarName}_PID:-}" && [[ -n ${pid} ]]; then
+    if kill -0 "${pid}" 2>/dev/null; then
+      return 0
+    fi
+  fi
+  return 1
+}
+
+# ## coproc::wait
+#
+# This function waits for a coproc to finish.
+#
+# - $1: **coproc variable name** _as string_:
+#       The variable name to use for the coproc.
+#
+# Returns:
+# - ${REPLY_CODE}: The exit status of the coproc (or -1 if the coproc is not running).
+#
+# ```bash
+# coproc::wait "myCoproc"
+# ```
+function coproc::wait() {
+  local coprocVarName="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
+
+  if [[ ! -v GLOBAL_BACKGROUND_PROCESSES[${coprocVarName}] ]]; then
+    REPLY_CODE=-1
+    return 0
+  fi
+  local pid="${GLOBAL_BACKGROUND_PROCESSES[${coprocVarName}]}"
+
+  log::debug "Waiting for coproc ⌜${coprocVarName}⌝ (PID: ${pid}) to finish."
+
+  local -i exitStatus=0
+  if ! wait -f "${pid}"; then
+    exitStatus="${PIPESTATUS[0]:-}"
   fi
 
-  if ! kill -0 "${pid}" 2>/dev/null; then
-    return 1
-  fi
+  coproc_cleanBackgroundProcess "${coprocVarName}"
+  REPLY_CODE="${exitStatus}"
 }
 
 # ## coproc::kill
@@ -476,27 +486,22 @@ function coproc::isRunning() {
 function coproc::kill() {
   local coprocVarName="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
 
-  if ! eval "local pid=\${${coprocVarName}_PID:-}" || [[ -z ${pid} ]]; then
+  if [[ ! -v GLOBAL_BACKGROUND_PROCESSES[${coprocVarName}] ]]; then
     return 0
   fi
+  local pid="${GLOBAL_BACKGROUND_PROCESSES[${coprocVarName}]}"
 
   log::debug "Killing coproc ⌜${coprocVarName}⌝ (PID: ${pid})."
 
-  if kill "${pid}" &>/dev/null; then
-    coproc_removePidFromBackgroundPids "${pid}"
-    unset -v "${coprocVarName}" "${coprocVarName}_PID"
-  fi
+  kill -INT "${pid}" &>/dev/null || :
+  kill -HUP "${pid}" &>/dev/null || :
+
+  coproc_cleanBackgroundProcess "${coprocVarName}"
 }
 
-# Remove the coproc pid from GLOBAL_BACKGROUND_PIDS
-function coproc_removePidFromBackgroundPids() {
-  local -i pid="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
-
-  local index
-  for index in "${!GLOBAL_BACKGROUND_PIDS[@]}"; do
-    if [[ ${GLOBAL_BACKGROUND_PIDS[index]} == "${pid}" ]]; then
-      unset -v 'GLOBAL_BACKGROUND_PIDS[index]'
-      break
-    fi
-  done
+# Remove the coproc from GLOBAL_BACKGROUND_PROCESSES
+function coproc_cleanBackgroundProcess() {
+  local coprocVarName="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
+  unset -v "GLOBAL_BACKGROUND_PROCESSES[${coprocVarName}]" "${coprocVarName}" "${coprocVarName}_PID"
 }
+
