:recycle: finishing huge refactoring

diff --git a/libraries.d/core b/libraries.d/core
--- a/libraries.d/core
+++ b/libraries.d/core
@@ -206,6 +206,10 @@ function fs::cleanTempFiles() {
     log::debug "Deleting temporary directory."
     rm -Rf "${GLOBAL_TEMPORARY_DIRECTORY}" 1>/dev/null || :
   fi
+  if [[ -n ${GLOBAL_WINDOWS_TEMPORARY_DIRECTORY:-} && -d ${GLOBAL_WINDOWS_TEMPORARY_DIRECTORY} ]]; then
+    log::debug "Deleting temporary windows directory."
+    rm -Rf "${GLOBAL_WINDOWS_TEMPORARY_DIRECTORY}" 1>/dev/null || :
+  fi
   rm -f "${GLOBAL_TEMPORARY_FILE_PREFIX}"* 1>/dev/null || :
   unset TEMPORARY_FILE_NUMBER TEMPORARY_DIRECTORY_NUMBER
 }
@@ -447,7 +451,7 @@ function log::createPrintFunction() {
     done
 
     wrapStatement='
-    string::wrapText "${RETURNED_VALUE}" '"${wrapTextColumns}"' '"'${wrapPaddingCharacters}'"' '"$((wrapTextColumns - wrapPaddingLength))"''
+    string::wrapWords "${RETURNED_VALUE}" '"${wrapTextColumns}"' '"'${wrapPaddingCharacters}'"' '"$((wrapTextColumns - wrapPaddingLength))"''
   else
     wrapPaddingLength=0
   fi
@@ -853,7 +857,7 @@ function log::printCallStack() {
 # >>> String utilities
 #===============================================================
 
-# ## string::wrapText
+# ## string::wrapWords
 #
 # Allows to soft wrap the given text at the given width.
 # Wrapping is done at word boundaries.
@@ -882,14 +886,14 @@ function log::printCallStack() {
 # - `RETURNED_VALUE`: the wrapped text
 #
 # ```bash
-# string::wrapText "This is a long text that should be wrapped at 20 characters." 20 '  ' 5
+# string::wrapWords "This is a long text that should be wrapped at 20 characters." 20 '  ' 5
 # echo "${RETURNED_VALUE}"
 # ```
 #
 # > - This function is written in pure bash and is faster than calling the fold command.
 # > - This function effectively trims all the extra spaces in the text (leading, trailing but also in the middle).
 # > - It considers escape sequence for text formatting and does not count them as visible characters.
-function string::wrapText() {
+function string::wrapWords() {
   local text="${1}"
   local -i width="${2:-${_OPTION_WRAP_WIDTH:-${GLOBAL_COLUMNS}}}"
   local leftPaddingChars="${3:-${_OPTION_PADDING_CHARS:-}}"
@@ -1292,9 +1296,12 @@ function array::fuzzyFilterSortQuicksort() {
 #   - 0 if the function was successfully re-exported
 #   - 1 if the function does not exist
 # - `RETURNED_VALUE`: the modified function definition
+# - `RETURNED_VALUE2`: the original function
 #
 # ```bash
 # bash::getFunctionDefinitionWithGlobalVars "myFunction" "myFunctionWithGlobalVars" "MY_VAR1" "MY_VAR2"
+# eval "${RETURNED_VALUE}"
+# myFunctionWithGlobalVars
 # ```
 function bash::getFunctionDefinitionWithGlobalVars() {
   local functionName="${1}"
@@ -1302,10 +1309,10 @@ function bash::getFunctionDefinitionWithGlobalVars() {
   shift 2
 
   local IFS=''
-  local functionDefinition
   declare -f "${functionName}" 1>"${GLOBAL_TEMPORARY_STDOUT_FILE}" || return 1
-  read -rd '' functionDefinition <"${GLOBAL_TEMPORARY_STDOUT_FILE}" || [[ -n ${functionDefinition} ]]
-  functionDefinition="${functionDefinition/"${functionName}"/"${newFunctionName}"}"
+  read -rd '' RETURNED_VALUE2 <"${GLOBAL_TEMPORARY_STDOUT_FILE}" || [[ -n ${RETURNED_VALUE2} ]]
+  local functionDefinition
+  functionDefinition="${RETURNED_VALUE2/"${functionName}"/"${newFunctionName}"}"
 
   # find the mapping between the positional parameters and the new global variable names
   local -A globalVars=()
@@ -1334,6 +1341,32 @@ function bash::getFunctionDefinitionWithGlobalVars() {
   done
 
   RETURNED_VALUE="${modifiedFunctionDefinition}"
+}
+
+#===============================================================
+# >>> Time utilities
+#===============================================================
+
+# ## time::getProgramElapsedMicroseconds
+#
+# Get the elapsed time in µs since the program started.
+#
+# Returns:
+#
+# - `RETURNED_VALUE`: the elapsed time in µs since the program started.
+#
+# ```bash
+# core::getElapsedProgramTime
+# echo "${RETURNED_VALUE}"
+# time::convertMicrosecondsToHuman "${RETURNED_VALUE}"
+# echo "Human time: ${RETURNED_VALUE}"
+# ```
+#
+# > We split the computation in seconds and milliseconds to avoid overflow on 32-bit systems.
+# > The 10# forces the base 10 conversion to avoid issues with leading zeros.
+# > Fun fact: this function will fail in 2038 on 32-bit systems because the number of seconds will overflow.
+function time::getProgramElapsedMicroseconds() {
+  RETURNED_VALUE=$(((${EPOCHREALTIME%%\.*} - GLOBAL_PROGRAM_STARTED_AT_SECOND) * 1000000 + (10#${EPOCHREALTIME##*\.} - 10#${GLOBAL_PROGRAM_STARTED_AT_MICROSECOND})))
 }
 
 #===============================================================
@@ -1539,28 +1572,6 @@ function core::getVersion() {
   # shellcheck source=lib-fs
   source fs
   fs::readFile "${GLOBAL_INSTALLATION_DIRECTORY}/version"
-}
-
-# ## core::getProgramElapsedMicroseconds
-#
-# Get the elapsed time in µs since the program started.
-#
-# Returns:
-#
-# - `RETURNED_VALUE`: the elapsed time in µs since the program started.
-#
-# ```bash
-# core::getElapsedProgramTime
-# echo "${RETURNED_VALUE}"
-# string::microsecondsToHuman "${RETURNED_VALUE}"
-# echo "Human time: ${RETURNED_VALUE}"
-# ```
-#
-# > We split the computation in seconds and milliseconds to avoid overflow on 32-bit systems.
-# > The 10# forces the base 10 conversion to avoid issues with leading zeros.
-# > Fun fact: this function will fail in 2038 on 32-bit systems because the number of seconds will overflow.
-function core::getProgramElapsedMicroseconds() {
-  RETURNED_VALUE=$(((${EPOCHREALTIME%%\.*} - GLOBAL_PROGRAM_STARTED_AT_SECOND) * 1000000 + (10#${EPOCHREALTIME##*\.} - 10#${GLOBAL_PROGRAM_STARTED_AT_MICROSECOND})))
 }
 
 #===============================================================
diff --git a/libraries.d/lib-bash b/libraries.d/lib-bash
--- a/libraries.d/lib-bash
+++ b/libraries.d/lib-bash
@@ -137,7 +137,7 @@ function bash::runInParallel() {
       done
 
       if ((nbJobsCompleted == 0)); then
-        exe::sleep "${timeoutBetweenChecks}"
+        bash::sleep "${timeoutBetweenChecks}"
       fi
 
       if ((${#exitCodes[@]} == ${#jobNames[@]})); then
@@ -220,4 +220,199 @@ function bash::injectCodeInFunction() {
 
   RETURNED_VALUE="${modifiedFunctionDefinition}"
   RETURNED_VALUE2="${functionDefinition:-}"
+}
+
+# ## bash::sleep
+#
+# Sleep for the given amount of time.
+# This is a pure bash replacement of sleep.
+#
+# - $1: **time** _as float_:
+#       the time to sleep in seconds (can be a float)
+#
+# ```bash
+# bash::sleep 1.5
+# ```
+#
+# > The sleep command is not a built-in command in bash, but a separate executable. When you use sleep, you are creating a new process.
+function bash::sleep() {
+  local timeout="${1}"
+  # when connected to a terminal, we can just read the stdout
+  # which will never be written to, and use a timeout on read
+  if [[ -t 2 ]]; then
+    read -rt "${timeout}" -u 2 || :
+    return 0
+  elif command -v mkfifo 1>/dev/null; then
+    if [[ -z ${IO_SLEEP_FIFO:-} ]]; then
+      fs::createTempFile && IO_SLEEP_FIFO="${RETURNED_VALUE}"
+      rm "${IO_SLEEP_FIFO}"
+      mkfifo -m 700 "${IO_SLEEP_FIFO}"
+      exec 6<>"${IO_SLEEP_FIFO}"
+      rm "${IO_SLEEP_FIFO}"
+    fi
+    read -rt "${timeout}" -u 6 || :
+  else
+    # when everything else failed...
+    sleep "${timeout}"
+  fi
+}
+
+# ## bash::readStdIn
+#
+# Read the content of the standard input.
+# Will immediately return if the standard input is empty.
+#
+# Returns:
+#
+# - `RETURNED_VALUE`: The content of the standard input.
+#
+# ```bash
+# bash::readStdIn && local stdIn="${RETURNED_VALUE}"
+# ```
+function bash::readStdIn() {
+  RETURNED_VALUE=""
+  local IFS=''
+  if read -t 0 -u 0 -rd ''; then
+    read -u 0 -rd '' RETURNED_VALUE || [[ -n ${RETURNED_VALUE} ]] || RETURNED_VALUE=""
+  else
+    RETURNED_VALUE=""
+  fi
+}
+
+# ## bash::countArgs
+#
+# Returns the number of arguments passed.
+#
+# A convenient function that can be used to:
+#
+# - count the files/directories in a directory
+#   `bash::countArgs "${PWD}"/* && local numberOfFiles="${RETURNED_VALUE}"`
+# - count the number of variables starting with VALET_
+#   `bash::countArgs "${!VALET_@}" && local numberOfVariables="${RETURNED_VALUE}"`
+#
+# - $@: **arguments** _as any_:
+#       the arguments to count
+#
+# Returns:
+#
+# - `RETURNED_VALUE`: The number of arguments passed.
+#
+# ```bash
+# bash::countArgs 1 2 3
+# ```
+function bash::countArgs() {
+  RETURNED_VALUE="$#"
+}
+
+# ## bash::getMissingVariables
+#
+# This function returns the list of undeclared variables for the given names.
+#
+# - $@: **variable names** _as string_:
+#       the list of variable names to check.
+#
+# Returns:
+#
+# - $?
+#   - 0 if there are variable undeclared
+#   - 1 otherwise.
+# - `RETURNED_ARRAY`: the list of undeclared variables.
+#
+# ```bash
+# if bash::getMissingVariables "var1" "var2"; then
+#   printf 'The following variables are not declared: %s' "${RETURNED_ARRAY[*]}"
+# fi
+# ```
+function bash::getMissingVariables() {
+  RETURNED_ARRAY=()
+  local var
+  for var in "$@"; do
+    if [[ ! -v "${var}" ]]; then
+      RETURNED_ARRAY+=("${var}")
+    fi
+  done
+  if [[ ${#RETURNED_ARRAY[@]} -gt 0 ]]; then
+    return 0
+  fi
+  return 1
+}
+
+# ## bash::getMissingCommands
+#
+# This function returns the list of not existing commands for the given names.
+#
+# - $@: **command names** _as string_:
+#       the list of command names to check.
+#
+# Returns:
+#
+# - $?
+#   - 0 if there are not existing commands
+#   - 1 otherwise.
+# - `RETURNED_ARRAY`: the list of not existing commands.
+#
+# ```bash
+# if bash::getMissingCommands "command1" "command2"; then
+#   printf 'The following commands do not exist: %s' "${RETURNED_ARRAY[*]}"
+# fi
+# ```
+function bash::getMissingCommands() {
+  RETURNED_ARRAY=()
+  local cmd
+  for cmd in "$@"; do
+    if ! command -v "${cmd}" &>/dev/null; then
+      RETURNED_ARRAY+=("${cmd}")
+    fi
+  done
+  if [[ ${#RETURNED_ARRAY[@]} -gt 0 ]]; then
+    return 0
+  fi
+  return 1
+}
+
+# ## bash::isCommand
+#
+# Check if the given command exists.
+#
+# - $1: **command name** _as string_:
+#       the command name to check.
+#
+# Returns:
+#
+# - $?
+#   - 0 if the command exists
+#   - 1 otherwise.
+#
+# ```bash
+# if bash::isCommand "command1"; then
+#   printf 'The command exists.'
+# fi
+# ```
+function bash::isCommand() {
+  if command -v "${1:-}" &>/dev/null; then
+    return 0
+  fi
+  return 1
+}
+
+# ## system::isRoot
+#
+# Check if the script is running as root.
+#
+# Returns:
+#
+# - $?
+#   - 0 if the script is running as root
+#   - 1 otherwise.
+#
+# ```bash
+# if system::isRoot; then
+#   printf 'The script is running as root.'
+# fi
+# ```
+function system::isRoot() {
+  if [[ ${EUID:-${UID}} -eq 0 ]]; then
+    return 0
+  fi
+  return 1
 }
diff --git a/libraries.d/lib-curl b/libraries.d/lib-curl
--- a/libraries.d/lib-curl
+++ b/libraries.d/lib-curl
@@ -7,11 +7,11 @@ source exe
 # shellcheck source=lib-fs
 source fs
 
-# ## curl::toFile
+# ## curl::download
 #
-# This function is a wrapper around curl.
+# This function is a wrapper around curl to save a request result in a file.
 # It allows you to check the http status code and return 1 if it is not acceptable.
-# It exe::invokes curl with the following options (do not repeat them): -sSL -w "%{response_code}" -o ${2}.
+# It invokes curl with the following options (do not repeat them): -sSL -w "%{response_code}" -o ${2}.
 #
 # - $1: **fail** _as bool_:
 #       true/false to indicate if the function should fail in case the execution fails
@@ -32,10 +32,10 @@ source fs
 # - `RETURNED_VALUE2`: the http status code
 #
 # ```bash
-# curl::toFile true 200,201 "/filePath" "https://example.com"
-# curl::toFile false 200 "/filePath2" "https://example2.com" || core::fail "The curl command failed."
+# curl::download true 200,201 "/filePath" "https://example.com"
+# curl::download false 200 "/filePath2" "https://example2.com" || core::fail "The curl command failed."
 # ```
-function curl::toFile() {
+function curl::download() {
   local failIfFails="${1:-false}"
   local acceptableStatusCodes="${2:-200,201,202,204,301,304,308}"
   local outputFile="${3}"
@@ -90,11 +90,11 @@ function curl::toFile() {
   return ${exitCode}
 }
 
-# ## curl::toVar
+# ## curl::request
 #
-# This function is a wrapper around curl.
+# This function is a wrapper around curl to save the content of a request in a variable.
 # It allows you to check the http status code and return 1 if it is not acceptable.
-# It exe::invokes curl with the following options (do not repeat them): -sSL -w "%{response_code}" -o "tempfile".
+# It invokes curl with the following options (do not repeat them): -sSL -w "%{response_code}" -o "tempfile".
 #
 # - $1: **fail** _as bool_:
 #       true/false to indicate if the function should fail in case the execution fails
@@ -114,10 +114,10 @@ function curl::toFile() {
 # - `RETURNED_VALUE3`: the http status code
 #
 # ```bash
-# curl::toVar true 200 https://example.com -X POST -H 'Authorization: token'
-# curl::toVar false 200,201 https://example.com || core::fail "The curl command failed."
+# curl::request true 200 https://example.com -X POST -H 'Authorization: token'
+# curl::request false 200,201 https://example.com || core::fail "The curl command failed."
 # ```
-function curl::toVar() {
+function curl::request() {
   local failIfFails="${1:-false}"
   local acceptableStatusCodes="${2:-}"
   shift 2
@@ -127,7 +127,7 @@ function curl::toVar() {
 
   local -i exitCode=0
   local errors httpStatusCode
-  curl::toFile "${failIfFails}" "${acceptableStatusCodes}" "${GLOBAL_TEMPORARY_WORK_FILE}" "$@" || exitCode=$?
+  curl::download "${failIfFails}" "${acceptableStatusCodes}" "${GLOBAL_TEMPORARY_WORK_FILE}" "$@" || exitCode=$?
   errors="${RETURNED_VALUE}"
   httpStatusCode="${RETURNED_VALUE2}"
 
