:construction_worker: working on tui

diff --git a/libraries.d/lib-terminal b/libraries.d/lib-terminal
--- a/libraries.d/lib-terminal
+++ b/libraries.d/lib-terminal
@@ -76,14 +76,7 @@ function terminal::getCursorPosition() {
 # terminal::switchToFullScreen
 # ```
 function terminal::switchToFullScreen() {
-  if [[ ! -t ${GLOBAL_FD_TUI} ]]; then
-    core::fail "This function can only be used in an interactive session. Did you already called terminal::switchBackFromFullScreen?"
-  fi
-
-  _INTERACTIVE_FULL_SCREEN_MODE=true
-
-  # disable echoing when we type something
-  terminal::setRawMode
+  _TERMINAL_FULL_SCREEN_MODE=true
 
   # switch to the alternate screen, hide the cursor and clear the screen
   printf '%s' "${ESC__ENABLE_ALTERNATE_BUFFER_SCREEN}${ESC__CURSOR_HIDE}${ESC__ERASE_SCREEN}" 1>&"${GLOBAL_FD_TUI}"
@@ -100,13 +93,10 @@ function terminal::switchToFullScreen() {
 # terminal::switchBackFromFullScreen
 # ```
 function terminal::switchBackFromFullScreen() {
-  _INTERACTIVE_FULL_SCREEN_MODE=false
+  _TERMINAL_FULL_SCREEN_MODE=false
 
   # restore the terminal state
   printf '%s' "${ESC__ERASE_SCREEN}${ESC__TEXT_RESET}${ESC__DISABLE_ALTERNATE_BUFFER_SCREEN}" 1>&"${GLOBAL_FD_TUI}"
-
-  # restore stty
-  terminal::restoreSettings
 }
 
 # ## terminal::setRawMode
@@ -119,16 +109,19 @@ function terminal::switchBackFromFullScreen() {
 # terminal::setRawMode
 # ```
 function terminal::setRawMode() {
-  if [[ -z ${_INTERACTIVE_STTY_SAVED_CONFIG:-} ]]; then
+  if [[ -z ${GLOBAL_STTY_SAVED_CONFIG:-} ]]; then
     bash::getBuiltinOutput stty -g || core::fail "Unable to get the current terminal configuration. Please make sure that ⌜stty⌝ is available in your PATH."
-    _INTERACTIVE_STTY_SAVED_CONFIG="${RETURNED_VALUE%%$'\n'}"
+    GLOBAL_STTY_SAVED_CONFIG="${RETURNED_VALUE%%$'\n'}"
+  fi
+  if [[ ${_TERMINAL_RAW_MODE_ENABLED:-} != "true" ]]; then
     # we try to set specific settings and if it fails, we just set raw mode
     stty icrnl -inlcr -ixon -ixoff \
       nl0 cr0 tab0 ff0 -onlret \
       -icanon -echo -echok -echonl -echoe -echoke -ctlecho -tostop \
       erase ^B werase ^W \
       min 1 time 0 &>/dev/null || \
-      stty raw -echo || :
+      stty raw -echo || core::fail "Failed to set the terminal in raw mode, check stty version."
+    _TERMINAL_RAW_MODE_ENABLED=true
   fi
 }
 
@@ -137,23 +130,14 @@ function terminal::setRawMode() {
 # Restore the terminal options to their original state.
 # Should be called after `terminal::setRawMode`.
 #
-# - $1: force _as bool_:
-#       (optional) force the restoration of the stty configuration.
-#       By default, the restoration is only done if we are not in full screen mode when called.
-#       (defaults to false)
-#
 # ```bash
 # terminal::restoreSettings
 # ```
 # shellcheck disable=SC2120
 function terminal::restoreSettings() {
-  if [[ ${_INTERACTIVE_FULL_SCREEN_MODE:-${GLOBAL_EXPORTED_FOR_PROMPT:-}} == "true" && ${1:-} != "true" ]]; then
-    # don't restore if we do not force it and we are either in full screen or exported mode
-    return 0
-  fi
-  if [[ -n ${_INTERACTIVE_STTY_SAVED_CONFIG:-} ]]; then
-    stty "${_INTERACTIVE_STTY_SAVED_CONFIG}" &>/dev/null || :
-    unset -v _INTERACTIVE_STTY_SAVED_CONFIG
+  if [[ ${_TERMINAL_RAW_MODE_ENABLED:-} == "true" ]]; then
+    stty "${GLOBAL_STTY_SAVED_CONFIG}" &>/dev/null || :
+    unset -v _TERMINAL_RAW_MODE_ENABLED
   fi
 }
 
@@ -579,10 +563,6 @@ function terminal::waitForKeyPress() {
 #
 # This allows to use the `-e` option with the read command and receive events for special key press.
 #
-# Key binding is a mess because binding is based on the sequence of characters that gets
-# generated by the terminal when a key is pressed and this is not standard across all terminals.
-# We do our best here to cover most cases but it is by no mean perfect.
-# A good base documentation was <https://en.wikipedia.org/wiki/ANSI_escape_code#Terminal_input_sequences>.
 #
 # This function should be called before using terminal::waitForKeyPress.
 #
@@ -596,6 +576,13 @@ function terminal::waitForKeyPress() {
 # terminal::rebindKeymap
 # ```
 #
+# > Key binding is a mess because binding is based on the sequence of characters that gets
+# > generated by the terminal when a key is pressed and this is not standard across all terminals.
+# > We do our best here to cover most cases but it is by no mean perfect.
+# > A good base documentation was <https://en.wikipedia.org/wiki/ANSI_escape_code#Terminal_input_sequences>.
+# > This means that certain keys cannot be bound, like SHIFT+ENTER. For this, you will
+# > need to use a terminal that allows to remap such keys and send a specific sequence
+# > of characters that you can bind in bash.
 # > `showkey -a` is a good program to see the sequence of characters sent by the terminal.
 function terminal::rebindKeymap() {
   local callBackFunction="${1?"The function ⌜${FUNCNAME:-?}⌝ requires more than $# arguments."}"
@@ -794,7 +781,7 @@ function terminal::restoreBindings() {
   if [[ -z ${_INTERACTIVE_SAVED_BINDINGS_FILE:-} ]]; then
     return 0
   fi
-  if [[ ${GLOBAL_EXPORTED_FOR_PROMPT:-} != "true" ]]; then
+  if [[ ${GLOBAL_SOURCED_FOR_PROMPT:-} != "true" ]]; then
     # there is no need to restore if we are not in exported mode, the bindings are local to this execution
     return 0
   fi
diff --git a/libraries.d/lib-tui b/libraries.d/lib-tui
--- a/libraries.d/lib-tui
+++ b/libraries.d/lib-tui
@@ -2,21 +2,84 @@
 # author: github.com/jcaillon
 # description: This script can be sourced by commands to provide convenient functions.
 
+# shellcheck source=lib-terminal
+source terminal
 
 function tui::startMainLoop() {
   # set trap so that interrupt signal sets GLOBAL_SESSION_INTERRUPTED to true
-  terminal::setInterruptTrap
+  # terminal::setInterruptTrap
   # setup the terminal to be ready for readline
   terminal::setRawMode
   # before starting to wait for inputs, we clear up the key pressed
   terminal::clearKeyPressed
-  # rebind some keys to call the callback function prompt_onKeyBindingPress
-  terminal::rebindKeymap prompt_onKeyBindingPress
   terminal::rerouteLogs
 
+  tui_startKeyPressListener
 
+  local IFS=" "
+
+  # main loop
+  while [[ -t ${GLOBAL_FD_TUI} || ${GLOBAL_SESSION_INTERRUPTED} != "true" ]]; do
+    if [[ ! -v _TUI_COPROC_KEY_PRESS_LISTENER_PID ]]; then
+      log::warning "Key press listener coproc is not already running, re-starting it."
+      tui_startKeyPressListener
+    fi
+    # read the key pressed from the key press listener coproc
+    if IFS=$'\0' read -rd $'\0' RETURNED_VALUE <&"${_TUI_COPROC_KEY_PRESS_LISTENER[0]}"; then
+      log::info "Received key press: ${RETURNED_VALUE}"
+    fi
+  done
+
+  tui_stopKeyPressListener
 
   terminal::restoreLogs
   terminal::restoreSettings
   terminal::restoreInterruptTrap
+}
+
+function tui_startKeyPressListener() {
+  # if the key press listener is not already running, we start it
+  if [[ ! -v _TUI_COPROC_KEY_PRESS_LISTENER ]]; then
+    if [[ ! -v _TUI_USER_INPUT_FD ]]; then
+      exec {_TUI_USER_INPUT_FD}<&0
+    fi
+    log::debug "Starting key press listener coproc."
+    { coproc _TUI_COPROC_KEY_PRESS_LISTENER { tui_keyPressListener 2>&"${LOG_FD}"; } } 2>/dev/null
+  fi
+}
+
+function tui_stopKeyPressListener() {
+  # if the key press listener is running, we stop it
+  if [[ -v _TUI_COPROC_KEY_PRESS_LISTENER_PID ]]; then
+    log::debug "Stopping key press listener coproc."
+    kill "${_TUI_COPROC_KEY_PRESS_LISTENER_PID}" &>/dev/null || :
+    unset _TUI_COPROC_KEY_PRESS_LISTENER _TUI_COPROC_KEY_PRESS_LISTENER_PID
+  else
+    log::debug "Key press listener coproc is not running."
+  fi
+}
+
+function tui_keyPressListener() {
+  # rebind some keys to call the callback function
+  terminal::rebindKeymap tui_keyPressListener_handleKeyBinding
+
+  exec 0<&"${_TUI_USER_INPUT_FD}" || log::fail "Failed to redirect stdin to the user input fd."
+  if [[ ! -t 0 ]]; then
+    log::fail "stdin is not a terminal"
+  fi
+
+  while kill -0 "${GLOBAL_PROGRAM_MAIN_PID}"; do
+    if terminal::waitForKeyPress; then
+      printf "%s\0" "${LAST_KEY_PRESSED}"
+    fi
+  done
+}
+
+function tui_keyPressListener_handleKeyBinding() {
+  # make sure we see any error happening in this function, since it is 
+  # executed as a callback of the readline process and we redirected the stderr
+  # to /dev/null to avoid a bug with readline (see terminal::waitForKeyPress)
+  # exec 2>&"${LOG_FD}"
+
+  printf "!%s\0" "${1}"
 }
