:recycle: refacto test functions

diff --git a/libraries.d/lib-test b/libraries.d/lib-test
--- a/libraries.d/lib-test
+++ b/libraries.d/lib-test
@@ -2,12 +2,26 @@
 # author: github.com/jcaillon
 # description: This script can be sourced by commands to provide convenient functions.
 
+# ## test::title
+#
+# Call this function to add an H3 title in the report file.
+#
+# - $1: **title** _as string_:
+#       The title of the test.
+#
+# ```bash
+# test::title "Testing something"
+# ```
+function test::title() {
+  printf "%s\n\n" "### ${1:-"Test"}" >>"${GLOBAL_TEST_REPORT_FILE}"
+}
+
 # ## test::commentTest
 #
 # Call this function to add a paragraph in the report file.
 #
 # - $1: **comment** _as string_:
-#       the text to add in the report file
+#       The text to add in the report file.
 #
 # ```bash
 # test::commentTest "This is a comment."
@@ -16,17 +30,165 @@ function test::commentTest() {
   printf "%s\n\n" "${1:-}" >>"${GLOBAL_TEST_REPORT_FILE}"
 }
 
+# ## test::exec
+#
+# Call this function to execute a command and write the command and its output to the report file.
+# The command can fail, in which case the returned exit code is written to the report file.
+# However, the command must not call `exit` (in which case, use test::execExiting).
+#
+# - $@: **command** _as string_:
+#       The command to execute.
+#
+# ```bash
+# test::exec echo "Hello, world!"
+# ```
+function test::exec() {
+  test_execInternal false "$@"
+}
+
+# ## test::execExiting
+#
+# Call this function to execute a command that can call `exit` and write the command and its output to the report file.
+# The command is executed in a subshell to catch the exit.
+#
+# - $@: **command** _as string_:
+#       The command to execute.
+#
+# ```bash
+# test::execExiting exit 3
+# ```
+function test::execExiting() {
+  test_execInternal true "$@"
+}
+
+# ## test_execInternal (private)
+#
+# This function is called by test::exec and test::execExiting to execute a command and
+# write the command and its output to the report file.
+#
+# - $1: **canExit** _as boolean_:
+#       Whether the command can call `exit`.
+# - $@: **command** _as string_:
+#       The command to execute.
+#
+# ```bash
+# test_execInternal false echo "Hello, world!"
+# ```
+function test_execInternal() {
+  local canExit="${1}"
+  shift 1
+  local arg
+  local reportSection="Prompt:"$'\n'$'\n'"\`\`\`bash"$'\n'
+  for arg in "$@"; do
+    if [[ ${arg} == *[[:space:]]* ]]; then
+      reportSection+="\"${arg}\" "
+    else
+      reportSection+="${arg} "
+    fi
+  done
+  reportSection="${reportSection% }"$'\n'"\`\`\`"$'\n'$'\n'
+
+  printf '%s' "${reportSection}" >>"${GLOBAL_TEST_REPORT_FILE}"
+
+  # reset the standard output and error output files
+  # It is necessary to first close the file descriptors before resetting the files
+  exec 1>&-
+  exec 2>&-
+  : >"${GLOBAL_TEST_STANDARD_OUTPUT_FILE}"
+  : >"${GLOBAL_TEST_STANDARD_ERROR_FILE}"
+  exec 1>"${GLOBAL_TEST_STANDARD_OUTPUT_FILE}"
+  exec 2>"${GLOBAL_TEST_STANDARD_ERROR_FILE}"
+
+  # execute the command
+  local -i exitCode=0
+  if [[ ${canExit} == "true" ]]; then
+    if ! ("$@") 1>>"${GLOBAL_TEST_STANDARD_OUTPUT_FILE}" 2>>"${GLOBAL_TEST_STANDARD_ERROR_FILE}"; then
+      exitCode=${PIPESTATUS[0]:-}
+    fi
+  else
+    if ! "$@" 1>>"${GLOBAL_TEST_STANDARD_OUTPUT_FILE}" 2>>"${GLOBAL_TEST_STANDARD_ERROR_FILE}"; then
+      exitCode=$?
+    fi
+  fi
+
+  if (( exitCode != 0 )); then
+    printf '%s\n\n' "Exited with code: \`${exitCode}\`" >>"${GLOBAL_TEST_REPORT_FILE}"
+  fi
+
+  test::flushFdToCodeBlock 1 true
+  test::flushFdToCodeBlock 2 true
+}
+
+# ## test::flushFdToCodeBlock
+#
+# This function write the captured standard and error outputs to the report file
+# and reset these file descriptors.
+#
+# - $1: **fdNumber** _as int_:
+#       The file descriptor number to flush (1 or 2).
+# - $2: **blockTitle** _as boolean_:
+#       (optional) Can be set using the variable `_OPTION_BLOCK_TITLE`.
+#       Whether to add a title to the code block.
+#       (defaults to false)
+#
+# ```bash
+# test::flushFdToCodeBlock 1 true
+# ```
+function test::flushFdToCodeBlock() {
+  local -i fdNumber="${1}"
+  local blockTitle="${2:-${_OPTION_BLOCK_TITLE:-false}}"
+  local file
+  local codeBlockName
+  if (( fdNumber == 1 )); then
+    file="${GLOBAL_TEST_STANDARD_OUTPUT_FILE}"
+    codeBlockName="Standard output"
+  else
+    file="${GLOBAL_TEST_STANDARD_ERROR_FILE}"
+    codeBlockName="Error output"
+  fi
+  if [[ ! -s "${file}" ]]; then
+    return 0
+  fi
+  local text IFS=''
+  read -rd '' text <"${file}" || :
+  text="${text//${GLOBAL_VALET_HOME}/\$GLOBAL_VALET_HOME}"
+  text="${text//${GLOBAL_TEST_CURRENT_DIRECTORY}/.}"
+  text="${text//${GLOBAL_TEMPORARY_DIRECTORY_PREFIX}/\/tmp/valet}"
+  text="${text//${GLOBAL_TEMPORARY_FILE_PREFIX}/\/tmp/valet}"
+
+  if [[ ${blockTitle} == "true" ]]; then
+    # shellcheck disable=SC2016
+    printf '**%s**:\n\n```text\n%s\n```\n\n' "${codeBlockName}" "${text%$'\n'}" >>"${GLOBAL_TEST_REPORT_FILE}"
+  else
+    # shellcheck disable=SC2016
+    printf '```text\n%s\n```\n\n' "${text%$'\n'}" >>"${GLOBAL_TEST_REPORT_FILE}"
+  fi
+
+  # shellcheck disable=SC2093
+  eval " exec ${fdNumber}>&-; : >'${file}'; exec ${fdNumber}>'${file}';"
+}
+
+
+function test::flush() {
+  test::flushFdToCodeBlock 1 true
+  test::flushFdToCodeBlock 2 true
+}
+
 # ## test::endTest
 #
-# Call this function after each test to write the test results to the report file.
-# This create a new H3 section in the report file with the test description and the exit code.
+# Call this function after a test to write a test result section to the report file.
+# This create a new H3 section in the report file with the given test description,
+# the exit code, and the standard and error outputs (if any).
+#
+#
 #
 # - $1: **title** _as string_:
-#       the title of the test
+#       The title of the test.
 # - $2: **exit code** _as int_:
-#       the exit code of the test
+#       The exit code of the test.
 # - $3: comment _as string_:
-#       (optional) a text to explain what is being tested
+#       (optional) Can be set using the variable `_OPTION_COMMENT`.
+#       A text to explain what is being tested.
 #       (defaults to "")
 #
 # ```bash
@@ -35,79 +197,29 @@ function test::commentTest() {
 function test::endTest() {
   local testTitle="${1:-}"
   local exitCode="${2:-}"
-  local testDescription="${3:-}"
+  local testDescription="${3:-${_OPTION_COMMENT:-}}"
 
-  {
-    # write the test title
-    printf "%s\n\n" "### ${testTitle:-test}"
+  # write the test title
+  local reportSection="### ${testTitle:-test}"
 
-    # write the test description if any
-    if [[ -n "${testDescription}" ]]; then
-      printf "%s\n\n" "${testDescription}"
-    fi
+  # write the test description if any
+  if [[ -n "${testDescription}" ]]; then
+    reportSection+=$'\n'$'\n'"${testDescription}"
+  fi
 
-    # write the exit code
-    printf "%s\n\n" "Exit code: \`${exitCode}\`"
+  # write the exit code
+  reportSection+=$'\n'$'\n'"Exit code: \`${exitCode}\`"
 
-    # write the standard output if any
-    if [[ -s "${GLOBAL_TEST_STANDARD_OUTPUT_FILE}" ]]; then
-      printf "%s\n\n%s\n" "**Standard** output:" "\`\`\`plaintext"
-      test::echoFileSubstitutingPath "${GLOBAL_TEST_STANDARD_OUTPUT_FILE}"
-      printf "\n%s\n\n" "\`\`\`"
-    fi
+  printf '%s\n\n' "${reportSection}" >>"${GLOBAL_TEST_REPORT_FILE}"
 
-    # write the error output if any
-    if [[ -s "${GLOBAL_TEST_STANDARD_ERROR_FILE}" ]]; then
-      printf "%s\n\n%s\n" "**Error** output:" "\`\`\`log"
-      test::echoFileSubstitutingPath "${GLOBAL_TEST_STANDARD_ERROR_FILE}"
-      printf "\n%s\n\n" "\`\`\`"
-    fi
-
-  } >>"${GLOBAL_TEST_REPORT_FILE}"
-
-  # reset the standard output and error output files
-  : >"${GLOBAL_TEST_STANDARD_OUTPUT_FILE}"
-  : >"${GLOBAL_TEST_STANDARD_ERROR_FILE}"
-}
-
-# This function is used to print the content of a file with some substitutions.
-# The substitutions are:
-# - replace the GLOBAL_VALET_HOME with $GLOBAL_VALET_HOME
-# - replace the current test directory with a dot
-# - replace a line with ${TMPDIR}/valet-*/ (temp directory) by /valet/
-#
-# This allows to have consistent results across different execution environments for the tests.
-#
-# Usage:
-#   myCommandThatProducesLinesWithValetDirectoryPath 2> "${GLOBAL_TEST_TEMP_FILE}"
-#   selfTestUtils_echoFileSubstitutingPath "${GLOBAL_TEST_TEMP_FILE}" 1>&2
-function test::echoFileSubstitutingPath() {
-  local file="${1}"
-  local line
-  local -i firstLine=1
-  local IFS
-  # IFS='' read -rd '' RETURNED_VALUE <"${GLOBAL_TEMPORARY_STDOUT_FILE}" || :
-  while IFS=$'\n' read -rd $'\n' line || [[ -n ${line:-} ]]; do
-    if [[ firstLine -eq 1 ]]; then
-      firstLine=0
-    else
-      echo
-    fi
-    line="${line//${GLOBAL_VALET_HOME}/\$GLOBAL_VALET_HOME}"
-    line="${line//${GLOBAL_TEST_CURRENT_DIRECTORY}/.}"
-    line="${line//${GLOBAL_TEMPORARY_PREFIX}*.valet/\/tmp/valet}"
-    line="${line//${GLOBAL_TEMPORARY_IN_MEM_PREFIX}*.valet/\/tmp/valet}"
-    if [[ ${line} =~ "after "[0-9]{1,}s.$ ]]; then
-      line="${line/%after */after Xs.}"
-    fi
-    printf '%s' "${line}"
-  done <"${file}"
+  test::flushFdToCodeBlock 1 true
+  test::flushFdToCodeBlock 2 true
 }
 
 # Replaces the line numbers from an error log in the given file with XXX.
 #
 # - $1: **file path** _as string_:
-#       the path of the file in which the output is stored
+#       The path of the file in which the output is stored.
 #
 # ```bash
 # test::echoFileWithLineNumberSubstitution myFile.log
