:bug: fix echo disabled when stty is called in a subshell

diff --git a/libraries.d/lib-terminal b/libraries.d/lib-terminal
--- a/libraries.d/lib-terminal
+++ b/libraries.d/lib-terminal
@@ -116,13 +116,7 @@ function terminal::setRawMode() {
     core::fail "stdin is not a terminal, cannot reset mode."
   fi
   if [[ -z ${GLOBAL_STTY_SAVED_CONFIG:-} ]]; then
-    if stty -g <&"${GLOBAL_FD_ORIGINAL_STDIN:-0}" &>"${GLOBAL_TEMPORARY_STDOUT_FILE}"; then
-      IFS='' read -rd '' REPLY <"${GLOBAL_TEMPORARY_STDOUT_FILE}" || :
-    else
-      core::fail "Unable to get the current terminal configuration. Please make sure that ⌜stty⌝ is available in your PATH."
-    fi
-    GLOBAL_STTY_SAVED_CONFIG="${REPLY%%$'\n'}"
-    log::debug "Saved terminal stty initial settings: ${GLOBAL_STTY_SAVED_CONFIG}."
+    terminal::saveSettings
   fi
   # we try to set specific settings and if it fails, we just set raw mode
   {
@@ -134,6 +128,29 @@ function terminal::setRawMode() {
       stty raw -echo || core::fail "Failed to set the terminal in raw mode, check stty version."
   } <&"${GLOBAL_FD_ORIGINAL_STDIN:-0}"
   GLOBAL_TERMINAL_RAW_MODE_ENABLED=true
+}
+
+# ## terminal::saveSettings
+#
+# Save the current terminal options (`stty -g`) so they can be restored later.
+# Call `terminal::restoreSettings` to restore the original settings.
+#
+# ```bash
+# terminal::saveSettings
+# ```
+function terminal::saveSettings() {
+  if [[ ! -t ${GLOBAL_FD_ORIGINAL_STDIN} && ${GLOBAL_TEST_FORCE_FD_OPEN:-} != "true" ]]; then
+    core::fail "stdin is not a terminal, cannot reset mode."
+  fi
+  if [[ -z ${GLOBAL_STTY_SAVED_CONFIG:-} ]]; then
+    if stty -g <&"${GLOBAL_FD_ORIGINAL_STDIN:-0}" &>"${GLOBAL_TEMPORARY_STDOUT_FILE}"; then
+      IFS='' read -rd '' REPLY <"${GLOBAL_TEMPORARY_STDOUT_FILE}" || :
+    else
+      core::fail "Unable to get the current terminal configuration. Please make sure that ⌜stty⌝ is available in your PATH."
+    fi
+    GLOBAL_STTY_SAVED_CONFIG="${REPLY%%$'\n'}"
+    log::debug "Saved terminal stty initial settings: ${GLOBAL_STTY_SAVED_CONFIG}."
+  fi
 }
 
 # ## terminal::restoreSettings
